export const bokmal = [

    ["Alle døråpninger, før man går frem, skal man se over, skal man speide over; for man vet ikke sikkert hvor uvenner sitter på benkene der inne.", "Stanza 1"],
    ["Heil de som gir! En gjest er kommet; hvor skal han sitte? Travel er den som på kanten av krakken skal prøve lykken.", "Stanza 2"],
    ["Ild trenger den som inn er kommet og er frossen om knærne; mat og klær trenger den mann som har reist over fjellet.", "Stanza 3"],
    ["Vann trenger den som til måltid kommer, håndkle og vennlig nøding; godt ord skal han ha, om han kan få det, og taushet mens andre taler.", "Stanza 4"],
    ["Vett trenger den som vidt reiser; hjemme er alt lett. Til spott blir den som ingenting vet og sitter blant kloke folk.", "Stanza 5"],
    ["Med sitt vett skal man ikke skryte, heller være varsom i sinn; når en klok og taus gjest kommer til gården, skjer det sjelden den varme ulykke.", "Stanza 6"],
    ["Den varsomme gjest som til måltid kommer, tier og lytter; med ørene hører han, med øynene speider han: slik utforsker hver vis mann.", "Stanza 7"],
    ["Sæl er den som får ros og godvilje for seg selv; for det er vanskelig å eie det man må finne i en annens bryst.", "Stanza 8"],
    ["Sæl er den som selv har ros og vett så lenge han lever; for onde råd har ofte kommet ut av en annens bryst.", "Stanza 9"],
    ["Bedre bør bærer ingen på veien enn mye mannevett; bedre enn gull er det i fremmed land, det er den fattiges tilflukt.", "Stanza 10"],
    ["Bedre bør bærer ingen på veien enn mye mannevett; dårligere niste finnes ikke for reisen enn overmål av øl.", "Stanza 11"],
    ["Ikke så godt som man sier, er ølet for menneskenes barn; for jo mer han drikker, jo mindre vet mannen hva som styrer hans sinn.", "Stanza 12"],
    ["Glemselens hegre heter han som over drikkelaget svever; han stjeler mannens vett. Med fjærene til den fuglen ble jeg bundet i Gunnløds gård.", "Stanza 13"],
    ["Drukken ble jeg, jeg ble overmåte drukken hos den kloke Fjalar; det er det beste med drikking, at hver mann får sitt vett igjen.", "Stanza 14"],
    ["Taus og tankefull skal en kongssønn være og modig i kamp; glad og munter skal hver mann være, helt til døden ham henter.", "Stanza 15"],
    ["Den ukloke mann tror han skal leve evig hvis han skyr kampen; men alderdommen gir ham ingen fred, selv om spydene sparer ham.", "Stanza 16"],
    ["Tåpen gaper når han kommer på besøk, han mumler eller stirrer; men med en gang han får en dram, vises det straks hva som bor i ham.", "Stanza 17"],
    ["Bare den vet som vidt har reist og vandret mye, hva slags sinn som bor i hver mann; han har selv forstand.", "Stanza 18"],
    ["Hold ikke på begeret, men drikk mjød med måte; si det nødvendige eller ti. Ingen vil kalle deg ufolkelig om du går tidlig til sengs.", "Stanza 19"],
    ["Den grådige mann, med mindre han styrer sitt sinn, spiser seg til døden; ofte bringer magen den ukloke spott når han er blant kloke folk.", "Stanza 20"],
    ["Buskapen vet når den skal gå hjem, og forlater da beitet; men den ukloke mann kjenner aldri målet for sin egen mage.", "Stanza 21"],
    ["En ussel mann med dårlig sinnelag spotter alt han ser; han vet ikke det han burde vite: at han ikke er feilfri selv.", "Stanza 22"],
    ["Den ukloke mann våker hele natten og grubler over alt; da er han trett når morgenen kommer, og alt hans jammmer er som før.", "Stanza 23"],
    ["Den ukloke mann tror at alle som ler mot ham er hans venner; han merker ikke, når han sitter blant kloke, at de taler ille om ham.", "Stanza 24"],
    ["Den ukloke mann tror at alle som ler mot ham er hans venner; når han så kommer på tinget, finner han få som taler hans sak.", "Stanza 25"],
    ["Den ukloke mann tror han vet alt når han sitter i en trygg krok; men han vet ikke hva han skal svare når menn setter ham på prøve.", "Stanza 26"],
    ["Den ukloke mann, når han kommer blant folk, gjør best i å tie; ingen vet at han ingenting kan, med mindre han taler for mye. Den som intet vet, merker ikke selv når han snakker over seg.", "Stanza 27"],
    ["Klok virker den som forstår å spørre og vet å svare; menneskenes barn kan ikke dölge det som går for seg blant folk.", "Stanza 28"],
    ["Mye unyttig snakker den som aldri tier, med ord uten mening; den snare tunge som ingen tøyle kjenner, skravler ofte ulykke over seg selv.", "Stanza 29"],
    ["Man skal ikke gjøre narr av andre, selv om de kommer på besøk; mang en mann virker klok om han ikke blir spurt og får sitte med tørr hud på benken.", "Stanza 30"],
    ["Klok virker gjesten som spotter en annen gjest og så stikker av; men den som ler ved måltidet, vet ikke sikkert om han ler blant fiender.", "Stanza 31"],
    ["Menn er ofte vennlige mot hverandre, men trettes likevel ved måltidet; denne splid vil alltid finnes: at gjest kjemper mot gjest.", "Stanza 32"],
    ["Morgenvat (frokost) skal man ofte ta før man går på besøk, med mindre man skal til en venn; ellers sitter man og stirrer sulten, og kan lite ta del i praten.", "Stanza 33"],
    ["En stor omvei er det til en dårlig venn, selv om huset hans ligger ved veien; men til en god venn fører strake stier, selv om han bor langt borte.", "Stanza 34"],
    ["Gå skal man, en gjest skal ikke være alltid på samme sted; det kjære blir kjedelig om man sitter for lenge på en annens benk.", "Stanza 35"],
    ["Eget hjem er best, selv om det er lite; hver mann er herre i sitt hus. To geiter og et flettet tak er bedre enn å tigge.", "Stanza 36"],
    ["Eget hjem er best, selv om det er lite; hver mann er herre i sitt hus. Hjertet blør på den som må be om mat til hvert mål.", "Stanza 37"],
    ["Fra sine våpen på marken skal man ikke vike en fotbredd; for man vet aldri når man på veien kan trenge sitt spyd.", "Stanza 38"],
    ["Jeg fant ingen mann så gavmild eller gjestfri at han ikke tok imot en gave, eller så raus med sitt gods at takk var ham uvelkommen.", "Stanza 39"],
    ["Sitt gods, som man har vunnet, skal man ikke spare for mye; ofte spares det til fienden som var tenkt for vennen: Mye går verre enn man tror.", "Stanza 40"],
    ["Med våpen og klær skal venner glede hverandre, det er mest synlig på en selv; å gi og gi igjen gjør vennskapet varig, om det ellers går godt.", "Stanza 41"],
    ["Sin venn skal man være venn, og gjengjelde gave med gave; latter skal man møte med latter, men svik med løgn.", "Stanza 42"],
    ["Sin venn skal man være venn, ham selv og hans venn; men ingen manns uvenns venn skal man noensinne være.", "Stanza 43"],
    ["Vet du, om du har en venn som du stoler godt på og du vil ha godt av ham, skal du dele tankene dine med ham og bytte gaver, gå ofte og besøk ham.", "Stanza 44"],
    ["Har du derimot en annen som du stoler dårlig på, og du vil likevel ha godt av ham, skal du tale fagre ord til ham, men tenke svikaktig og gjengjelde løgn med løgn.", "Stanza 45"],
    ["Det er også slik med den du mistror og som du aner svik hos: Du skal le med ham og tale mot din vilje; gaven skal gjengjeldes med likt.", "Stanza 46"],
    ["Ung var jeg engang, jeg vandret alene og villfór på veien; rik følte jeg meg da jeg møtte en annen: Mann er manns gammen (glede).", "Stanza 47"],
    ["Gavmilde, tapre menn lever best, de kjenner sjelden sorg; men den feige mann frykter alt, og den gjerrige gruer seg alltid for gaver.", "Stanza 48"],
    ["Klærne mine ga jeg på marken til to tremenn; kjemper syntes de å være da de fikk fillete klær: Skamfull er den nakne mann.", "Stanza 49"],
    ["Furu dør som står på en naken plett, verken bark eller nåler beskytter den; slik er mennesket som ingen elsker: Hvordan skal han leve lenge?", "Stanza 50"],
    ["Heitere enn ild brenner blant falske venner kjærligheten i fem dager; men den slukner når den sjette kommer, og hele vennskapet faller fra hverandre.", "Stanza 51"],
    ["Ikke bare store ting skal man gi; ofte kjøper man seg ros med lite. Med et halvt brød og en skråstilt krukke vant jeg meg en kumpan.", "Stanza 52"],
    ["Små sandkorn, små sjøer, smått er menneskenes vett; ikke alle mennesker er like kloke, hvert mål er halvvegs.", "Stanza 53"],
    ["Middels klok bør hver mann være, aldri altfor vis; det livet er fagreste å leve for de som vet vel hva de vet.", "Stanza 54"],
    ["Middels klok bør hver mann være, aldri altfor vis; for en vis manns hjerte er sjelden glad om han er blitt altfor klok.", "Stanza 55"],
    ["Middels klok bør hver mann være, aldri altfor vis; sin skjebne bør ingen vite på forhånd, da er sinnet mest fritt for sorg.", "Stanza 56"],
    ["Brann tennes av brann til den er utbrent, ild blir av ild vakt; mann blir av mann kjent gjennom tale, men av ensomhet blir man dum.", "Stanza 57"],
    ["Tidlig skal han stå opp som vil ha en annens eie eller liv; sjelden fanger sovende ulv et bytte, eller sovende mann seieren.", "Stanza 58"],
    ["Tidlig skal han stå opp som har få arbeidsfolk, og selv gå til arbeidet; mye forsømmes av den som sover bort morgenen: Den flittige er halvveis rik.", "Stanza 59"],
    ["Om tørt tre og om bjørkebark vet mannen å ta mål, og om veden som skal ligge på lager for uker og måneder.", "Stanza 60"],
    ["Vasket og mett skal man ri til tings, selv om man ikke er så godt kledd; sine sko og broker skal ingen skamme seg over, og heller ikke hesten, om man ikke har en god en.", "Stanza 61"],
    ["Snapper og snapper når han kommer til havet, gjør ørnen ved den gamle flod; slik er mannen som kommer blant mange og har få som taler hans sak.", "Stanza 62"],
    ["Spørre og svare skal hver klok mann som vil kalles vis; én får vite det, men ikke en annen: Vet tre det, så vet hele verden det.", "Stanza 63"],
    ["Sin makt skal hver vis mann bruke med måte; for man finner det ut når man kommer blant de tapre, at ingen er den aller fremste.", "Stanza 64"],
    ["Ord som man taler til en annen, må man ofte betale dyrt for.", "Stanza 65"],
    ["Altfor tidlig kom jeg til mange steder, og for sent til noen; ølet var drukket eller ikke brygget: Sjelden kommer den uvelkomne til rette tid.", "Stanza 66"],
    ["Her og der hadde man bedt meg hjem om jeg ikke hadde trengt mat ved måltidet, eller om to skinker hadde hengt hos den trofaste vennen der jeg hadde spist én.", "Stanza 67"],
    ["Ild er det beste for menneskenes barn, og solens skinn; sin helse, om man kan beholde den, og et ulastelig liv.", "Stanza 68"],
    ["En mann er ikke helt ulykkelig selv om han er syk; noen er rike på sønner, noen på frender, noen på mye godt, noen på velgjorte verk.", "Stanza 69"],
    ["Bedre er det å leve enn ikke å leve; den levende får alltid kua. Jeg så den rikes ild brenne, men utenfor døren lå han død.", "Stanza 70"],
    ["Den halte kan ri, den håndløse kan gjete, den døve kan kjempe og duge; å være blind er bedre enn å brennes: En død mann er til ingen nytte.", "Stanza 71"],
    ["En sønn er bedre, selv om han er sent født etter at faren er borte; sjelden står bautasteiner ved veien om de ikke er reist av frende for frende.", "Stanza 72"],
    ["To er tungens morder; hodet er hjertets fiende. I hver neve venter jeg den skjulte armen under kappen.", "Stanza 73"],
    ["På natten stoler den som stoler på sitt forråd; korte er skipsplankene, ustadig er høstnatten. Været skifter ofte på fem dager, og enda mer på en måned.", "Stanza 74"],
    ["Den vet ingenting som ingenting vet: Mange blir tåper av rikdom. En mann er rik, en annen fattig; anklag ham ikke for dårskap av den grunn.", "Stanza 75"],
    ["Fe dør, frender dør, en selv dør på samme vis; men ordet om deg dør aldri for den som har vunnet et godt navn.", "Stanza 76"],
    ["Fe dør, frender dør, en selv dør på samme vis; jeg vet ett som aldri dør: dommen over hver død mann.", "Stanza 77"],
    ["Fulle kve så jeg hos Fitjungs sønner, nå bærer de tiggerstaven; slik er rikdom som et øyekast: Den er den mest ustadige av venner.", "Stanza 78"],
    ["Den ukloke mann, om han får rikdom eller en kvinnes kjærlighet, da vokser stoltheten, men ikke vettet: Han går stadig videre i sitt hovmod.", "Stanza 79"],
    ["Det er nå prøvd, det du spør runene om, de som stammer fra guder, som de høye makter skapte og stortaleren malte: Han gjør best i å tie.", "Stanza 80"],
    ["Om kvelden skal man dagen prise, kona når hun er brent, sverd når det er prøvd, møy når hun er gift, isen når man er over, ølet når det er drukket.", "Stanza 81"],
    ["I vind skal man ved felle, i godt vær ro på havet, i mørket tale med møy (mange er dagens øyne); skip er til å fare med, skjold til å verne, sverd til å hogge og møy til å kysse.", "Stanza 82"],
    ["Ved ild skal man øl drikke, på isen gli, kjøpe mager hest og rustent sverd; hesten skal fores hjemme, men hunden hos en annen.", "Stanza 83"],
    ["En møys ord skal ingen tro, heller ikke det en kvinne taler; for på et dreiende hjul ble deres hjerter skapt, og ustadighet ble lagt i deres bryst.", "Stanza 84"],
    ["Bristende bue, brennende lue, gapende ulv, gispende kråke, gryntende svin, rotløst tre, voksende bølge, kokende kjele,", "Stanza 85"],
    ["flyvende pil, fallende flod, isen av en natt, ringlagt slange, brude-tale i sengen eller knust sverd, lekende bjørn eller kongebarn,", "Stanza 86"],
    ["sykt kalv, selvvilling trell, volvens smiger, den nyslagne på valen,", "Stanza 87"],
    ["halvbrent hus, spillvåken hest (for én fot gjør hesten unyttig): ingen være så tillitsfull at han tror på alt dette.", "Stanza 88"],
    ["Sin brors morder, om man møter ham på veien, brennende hus, rask hest (da er et øk mest nyttig): hvem er så tillitsfull at han tror på alt dette!", "Stanza 89"],
    ["Å tro på kjærligheten til kvinner som har svik i sinne, er som å ri med uskodde hester på glatt is, med kåte toåringer, eller i hard storm med et styreløst skip, eller som en halt som i tøvær skal fange reinsdyr på fjellet.", "Stanza 90"],
    ["Åpent vil jeg nå tale, for jeg kjenner begge: ustadig er menns sinn mot kvinner; når vi taler fagreste, tenker vi falskest: det dårer selv den kloke.", "Stanza 91"],
    ["Fagert skal man tale og gods by, om man vil vinne en kvinnes kjærlighet; prise den fagre møys kropp: den som smigrer, han vinner.", "Stanza 92"],
    ["For kjærligheten skal aldri en mann laste en annen; ofte fenger den kloke det som ikke rører tåpen: den fagre skikkelsen.", "Stanza 93"],
    ["Aldri skal en mann laste en annen for dårskap som rammer mange; verdens gang gjør ofte kloke menn til tåper gjennom begjærets makt.", "Stanza 94"],
    ["Hugen (tanken) alene vet hva som bor nær hjertet, han alene kjenner sitt sinn; ingen plage er verre for en klok mann enn å ikke være til fred med seg selv.", "Stanza 95"],
    ["Det erfarte jeg selv da jeg satt i sivet og ventet på min kjære; liv og sjel var den kloke møy for meg, og likevel fikk jeg henne ikke.", "Stanza 96"],
    ["Billings møy fant jeg på sengen, solvithvit, sovende; en jarls glede syntes meg ingenting verd om jeg ikke fikk leve ved den kroppen.", "Stanza 97"],
    ["'Mot kvelden, Odin, skal du komme om du vil vinne møya; det er høyst usømmelig om ikke vi alene deler en slik lønn.'", "Stanza 98"],
    ["Jeg vendte tilbake og trodde meg elsket, sikker i min villfarelse; jeg trodde jeg hadde vunnet all hennes gunst og glede.", "Stanza 99"],
    ["Da jeg neste gang kom, var hele krigerflokken våken; med brennende fakler og båret ved: slik var veien sperret for meg.", "Stanza 100"],
    ["Og om morgenen, da jeg kom igjen, var sal-vaktas flokk sovnet; en bikkje fant jeg på den gode benken til kvinnen, bundet der i hennes sted.", "Stanza 101"],
    ["Mang en fager møy, om man kjenner henne nøye, er falsk i sinn mot menn; det fikk jeg prøve da jeg det kloke møy lokket til elskov: All slags skam la den listige på meg, og jeg fikk ikke kvinnen.", "Stanza 102"],
    ["Hjemme skal man være glad og mot gjester munter, sindig med seg selv; den som vil være vis, må ha mye kunnskap og ofte minnes det gode.", "Stanza 103"],
    ["Den gamle jetten (Suttung) oppsøkte jeg, nå er jeg tilbake; lite fikk jeg der ved å tie. Med mange ord talte jeg til min fordel i Suttungs saler.", "Stanza 104"],
    ["Gunnlød ga meg på den gylne stol en drikk av det dyre mjødet; dårlig lønn lot jeg henne få etterpå for hennes ærlige sinn, for hennes tunge kjærlighet.", "Stanza 105"],
    ["Rati lot jeg gnage vei og bore gjennom steinen; over og under meg var jettenes veier: Slik satte jeg hodet mitt i pant.", "Stanza 106"],
    ["Den kjøpte skikkelsen har jeg brukt vel, den vise mangler sjelden råd; for Odrøre er nå kommet opp til gudenes bolig.", "Stanza 107"],
    ["Tvilrådig er jeg om jeg hadde kommet tilbake fra jettenes gårder, om jeg ikke hadde brukt Gunnlød, den gode kvinne, som la armen sin rundt meg.", "Stanza 108"],
    ["Dagen etter gikk rimtusser for å spørre i Den Høyes hall etter Den Høye; de spurte om Bølverk var hos guden, eller om Suttung hadde drept ham.", "Stanza 109"],
    ["Ring-ed, sier man, har Odin svoret; hvem skal man nå stole på? Suttung har han sviktet ved drikken og latt Gunnlød sitte igjen i gråt.", "Stanza 110"],
    ["Det er tid for å tale fra talerstolen ved Urds brønn; jeg så og tidde, jeg så og tenkte, jeg lyttet til menns tale.", "Stanza 111"],
    ["Om runer hørte jeg dem råde, heller ikke manglet det på råd; i Den Høyes hall, i Den Høyes saler, hørte jeg dem tale slik:", "Stanza 112"],
    ["Jeg råder deg, Loddfåvne, ta imot rådet; du har nytte om du tar det, hell om du følger det: Stå ikke opp om natten, med mindre du skal speide eller gå på do ute.", "Stanza 113"],
    ["Jeg råder deg, Loddfåvne, ta imot rådet: Sov ikke i armene til en trollkyndig kvinne, så hun ikke fanger deg med sine lemmer.", "Stanza 114"],
    ["Hun gjør det slik at du ikke bryr deg om tinget eller kongens tale; mat nekter du og menneskers glede, full av sorg går du til søvns.", "Stanza 115"],
    ["Jeg råder deg, Loddfåvne, ta imot rådet: Lokk aldri en annen manns kone til hemmelig elskov.", "Stanza 116"],
    ["Jeg råder deg, Loddfåvne, ta imot rådet: Skal du reise over fjell eller fjord, utstyr deg godt med niste.", "Stanza 117"],
    ["Jeg råder deg, Loddfåvne, ta imot rådet: La aldri en ond mann få vite din ulykke; for av en ond mann får du aldri lønn for din gode tillit.", "Stanza 118"],
    ["Jeg så en mann bli dødelig såret av ordene til en ond kvinne; en falsk tunge ble hans bane, selv om han ikke var skyldig.", "Stanza 119"],
    ["Jeg råder deg, Loddfåvne, ta imot rådet: Har du en venn du stoler på, dra ofte og besøk ham; for kratt vokser og høyt gress på veien som ingen går.", "Stanza 120"],
    ["Jeg råder deg, Loddfåvne, ta imot rådet: En god mann skal du vinne deg til glede, og lær deg legemidler å kjenne.", "Stanza 121"],
    ["Jeg råder deg, Loddfåvne, ta imot rådet: Vær aldri den første til å bryte båndet med din venn; sorg eter hjertet om du ikke kan si din hele hug til noen.", "Stanza 122"],
    ["Jeg råder deg, Loddfåvne, ta imot rådet: Ord skal du aldri skifte med en uvettig tåpe.", "Stanza 123"],
    ["For av en ond mann vil du aldri få godt som lønn; men en god mann vil gjøre deg verdifull ved sin ros.", "Stanza 124"],
    ["Delt sinnelag er det når man sier alt sitt sinn til en annen; alt er bedre enn å være falsk: Ingen venn er den som bare taler etter munnen.", "Stanza 125"],
    ["Jeg råder deg, Loddfåvne, ta imot rådet: Selv med tre ord skal du ikke krangle med en dårligere mann; ofte feller den dårligere den bedre, når denne drar sverdet.", "Stanza 126"],
    ["Jeg råder deg, Loddfåvne, ta imot rådet: Vær ikke skomaker eller skaftmaker, uten for deg selv; for hvis skoen sitter dårlig eller skaftet er skjevt, vil man ønske deg alt ondt.", "Stanza 127"],
    ["Jeg råder deg, Loddfåvne, ta imot rådet: Hvor du enn ser urett, nevn det som urett, og gi dine fiender ingen fred.", "Stanza 128"],
    ["Jeg råder deg, Loddfåvne, ta imot rådet: Gled deg aldri over det onde, men vær det gode hengiven.", "Stanza 129"],
    ["Jeg råder deg, Loddfåvne, ta imot rådet: Se ikke opp i kamp (for menneskenes barn blir som vanvittige), så menn ikke forhekser deg.", "Stanza 130"],
    ["Jeg råder deg, Loddfåvne, ta imot rådet: Vil du vinne en kvinnes kjærlighet, hold fast dine løfter; ingen blir lei av det gode om han får det.", "Stanza 131"],
    ["Jeg råder deg, Loddfåvne, ta imot rådet: Vær varsom, men ikke for redd; vær mest varsom med ølet og med en annen manns kone.", "Stanza 132"],
    ["Jeg råder deg, Loddfåvne, ta imot rådet: Spott aldri en gjest eller en vandrer, og le ikke av ham.", "Stanza 133"],
    ["Jeg råder deg, Loddfåvne, ta imot rådet: Le aldri av en gråhåret taler; ofte er det godt, det de gamle sier. Fra rynket hud kommer ofte kloke ord.", "Stanza 134"],
    ["Ofte henger de mellom hudene, dingler under skinnene og slenger blant de visne.", "Stanza 135"],
    ["Jeg råder deg, Loddfåvne, ta imot rådet: Skjell ikke ut gjesten og jag ham ikke på dør; vær god mot de fattige.", "Stanza 136"],
    ["Sterk er den dørstolpen som skal åpne seg for alle; gi en ring, ellers vil man ønske deg hver ulykke.", "Stanza 137"],
    ["Jeg vet at jeg hang på det vindblåste treet i ni hele netter, såret med spyd og gitt til Odin, jeg selv til meg selv.", "Stanza 138"],
    ["På det treet som ingen vet hvor røttene rinner av.", "Stanza 139"],
    ["De rakte meg verken brød eller drikkehorn; jeg speidet ned, jeg tok opp runene, skrikende tok jeg dem, og falt så ned derfra.", "Stanza 140"],
    ["Da begynte jeg å gro og være vis, å vokse og trives vel; ord fulgte ord til nytt ord, verk fulgte verk til nytt verk.", "Stanza 141"],
    ["Runer skal du finne og lesbare staver, svært store staver, svært mektige staver, som stortaleren malte og de høye makter skapte og gudenes Hroptr ristet.", "Stanza 142"],
    ["Odin blant aser, for alver Daínn, Dvalin for dverger, Allsvinn for jotner; jeg selv ristet noen for menneskenes barn.", "Stanza 143"],
    ["Vet du hvordan man skal riste? Vet du hvordan man skal råde? Vet du hvordan man skal male? Vet du hvordan man skal prøve? Vet du hvordan man skal be? Vet du hvordan man skal ofre? Vet du hvordan man skal sende? Vet du hvordan man skal slette?", "Stanza 144"],
    ["Bedre er ikke bedt enn for mye ofret, en gave ser alltid etter gjengjeld; bedre er ikke sendt enn for mye slettet. Slik ristet Thundr før folkenes historie, der han steg opp da han kom tilbake.", "Stanza 145"],
    ["De sangene kjenner jeg som ingen dronning kan og ingen manns sønn. 'Hjelp' heter den første, for den hjelper deg i strid og sorg og i alle kvaler.", "Stanza 146"],
    ["En annen kjenner jeg som menneskenes barn trenger, de som vil leve som leger: å helbrede sår og lindre sykdom.", "Stanza 147"],
    ["En tredje kjenner jeg: hvis jeg har stor nød for å lenke mine fiender, så sløver jeg eggen på motstandernes våpen; verken våpen eller svik hjelper dem da.", "Stanza 148"],
    ["En fjerde kjenner jeg: hvis menn legger bånd på mine lemmer, så synger jeg slik at jeg kan gå; lenken springer fra føttene og båndet fra hendene.", "Stanza 149"],
    ["En femte kjenner jeg: hvis jeg ser en pil fly som vil skade i hæren, så flyr den ikke så fort at jeg ikke stanser den om jeg får se den med øynene.", "Stanza 150"],
    ["En sjette kjenner jeg: hvis en mann vil skade meg med røttene til et fremmed tre, så treffer ulykken han selv og ikke meg.", "Stanza 151"],
    ["En sjuende kjenner jeg: hvis jeg ser salen brenne rundt mine benkekamerater, så brenner den ikke så hett at jeg ikke berger den; den trolldommen kan jeg synge.", "Stanza 152"],
    ["En åttende kjenner jeg, som er nyttig for alle å lære: hvor hat vokser mellom fyrstesønner, der kan jeg raskt døyve det.", "Stanza 153"],
    ["En niende kjenner jeg: hvis nød tvinger meg til å berge mitt skip på havet, så stiller jeg vinden på bølgene og luller hele havet i søvn.", "Stanza 154"],
    ["En tiende kjenner jeg: hvis jeg ser gandreid-kvinner leke i luften, så gjør jeg slik at de forviller seg fra sine egne huder og sin egen hug.", "Stanza 155"],
    ["En ellevte kjenner jeg: hvis jeg skal lede gamle venner til strid, så synger jeg under skjoldene, og de drar med makt; hele til strid, hele fra strid, de kommer hele overalt.", "Stanza 156"],
    ["Et tolvte kjenner jeg: hvis jeg ser en hengte mann i et tre, så rister og maler jeg runer slik at mannen går og taler med meg.", "Stanza 157"],
    ["Et trettende kjenner jeg: hvis jeg øser vann over en ung kriger, så vil han ikke falle selv om han drar i kamp; ingen sverd hogger ham.", "Stanza 158"],
    ["Et fjortende kjenner jeg: hvis jeg skal telle opp guder for folk, aser og alver, så kjenner jeg alle vel; sjelden kjenner en uvittig dem slik.", "Stanza 159"],
    ["Et femtende kjenner jeg, som dvergen Tjodreir sang foran Dellings dører: han sang kraft til aser, ære til alver og vett til Hroptr.", "Stanza 160"],
    ["Et sekstende kjenner jeg: hvis jeg vil ha en klok møys elskov og lyst, så vender jeg sinnet til den hvitarmede kvinne og snur hele hennes hjerte.", "Stanza 161"],
    ["Et syttende kjenner jeg, slik at den unge møy aldri vil skille seg fra meg; disse sangene, Loddfåvne, vil du lenge mangle.", "Stanza 162"],
    ["Et attende kjenner jeg, som jeg aldri lærer til møy eller manns kone, uten til den ene som min arm favner eller som er min søster; alt er bedre når bare én vet det.", "Stanza 163"],
    ["Nå er Den Høyes tale talt i Den Høyes hall, nyttig for menneskenes barn, unyttig for jotnenes sønner. Heil den som talte! Heil den som kjenner! Nytte har den som lærte! Heil de som lyttet!", "Stanza 164"]

];