export const dansk = [

    ["Alle døråbninger, før man går ind, skal man betragte og spejde om; for uvist er det, hvor uvenner sidder på bænkene derinde.", "Stanza 1"],
    ["Hil de givende! En gæst er kommet; hvor skal han sidde? Hastig er den, som på tærsklen skal prøve sin lykke.", "Stanza 2"],
    ["Ild har han brug for, som ind er kommet og er frossen om knæene; mad og klæder har den mand behov for, som har rejst over fjeldet.", "Stanza 3"],
    ["Vand har han brug for, som til måltid kommer, håndklæde og venlig hilsen; et godt ord skal han have, om han kan få det, og tavshed mens andre taler.", "Stanza 4"],
    ["Vid har han brug for, som vidt rejser; hjemme er alt let. Til spot bliver den, som intet ved og sidder blandt kloge folk.", "Stanza 5"],
    ["Med sit vid skal man ikke prale, hellere være varsom i sind; når en klog og tavs gæst kommer til gården, sker der sjældent ulykke.", "Stanza 6"],
    ["Den varsomme gæst, som til måltid kommer, tier og lytter; med ørerne hører han, med øjnene spejder han: sådan prøver enhver vis mand.", "Stanza 7"],
    ["Sæl er den, som får lovord og godvilje hos sig selv; for det er tungt at eje det, man må finde i en andens bryst.", "Stanza 8"],
    ["Sæl er den, som selv har lovord og vid så længe han lever; for ilde råd har ofte lydt fra en andens bryst.", "Stanza 9"],
    ["Bedre byrde bærer ingen på vejen end meget mandevid; bedre end guld er det i fremmed land, det er den fattiges tilflugt.", "Stanza 10"],
    ["Bedre byrde bærer ingen på vejen end meget mandevid; værre niste findes ikke for rejsen end for meget drik.", "Stanza 11"],
    ["Ikke så godt som folk siger, er øllet for menneskenes børn; for jo mere han drikker, jo mindre ved manden, hvad der råder over hans sind.", "Stanza 12"],
    ["Glemsels-hejren hedder han, som over drikkelaget svæver; han stjæler viddet fra manden. Med de fjer blev jeg bunden i Gunnløds gård.", "Stanza 13"],
    ["Drukken blev jeg, jeg blev over-drukken hos den kloge Fjalar; det er det bedste ved drikken, at enhver får sit vid tilbage.", "Stanza 14"],
    ["Tavs og tænksom skal en kongesøn være og modig i kamp; glad og munter skal enhver mand være, lige til døden ham henter.", "Stanza 15"],
    ["Den uforstandige mand tror, han skal leve evigt, hvis han skyr kampen; men alderdommen giver ham ingen fred, selvom spydene sparer ham.", "Stanza 16"],
    ["Tåben gaber, når han kommer på besøg, han mumler eller stirrer; men så snart han får en dram, ses det straks, hvad der bor i ham.", "Stanza 17"],
    ["Kun den ved, som vidt har rejst og vandret meget, hvad for et sind der bor i hver mand; han har selv vid.", "Stanza 18"],
    ["Hold ikke på skålen, men drik mjød med måde; tal det nødvendige eller ti. Ingen vil kalde dig ufolkelig, om du går tidligt til sengs.", "Stanza 19"],
    ["Den grådige mand, medmindre han styrer sit sind, æder sig til døde; ofte fører maven den uforstandige til spot, når han er blandt kloge folk.", "Stanza 20"],
    ["Kvæget ved, hvornår det skal gå hjem, og forlader da græsset; men den uforstandige mand kender aldrig målet for sin egen mave.", "Stanza 21"],
    ["En ussel mand med dårligt sind ler ad alt, hvad han ser; han ved ikke det, han burde vide: at han ikke selv er uden fejl.", "Stanza 22"],
    ["Den uforstandige mand våger hele natten og spekulerer på alt; han er træt, når morgenen kommer, og alle hans bekymringer er som før.", "Stanza 23"],
    ["Den uforstandige mand tror, at alle som ler mod ham, er hans venner; han mærker ikke, når han sidder blandt kloge, at de taler ilde om ham.", "Stanza 24"],
    ["Den uforstandige mand tror, at alle som ler mod ham, er hans venner; men når han kommer på tinget, finder han få, som taler hans sag.", "Stanza 25"],
    ["Den uforstandige mand tror, han ved alt, når han sidder i en sikker krog; men han ved ikke, hvad han skal svare, når mænd sætter ham på prøve.", "Stanza 26"],
    ["Den uforstandige mand, når han kommer blandt folk, gør bedst i at tie; ingen ved, at han intet kan, medmindre han taler for meget. Den, som intet ved, mærker ikke selv, når han snakker over sig.", "Stanza 27"],
    ["Klog synes den, som forstår at spørge og ved at svare; menneskenes børn kan ikke skjule det, som sker blandt folk.", "Stanza 28"],
    ["Meget unyttigt snakker den, som aldrig tier, med ord uden mening; den hurtige tunge, som ingen tøjle kender, taler ofte ulykke over sig selv.", "Stanza 29"],
    ["Man skal ikke gøre grin med andre, selvom de kommer på besøg; mangen mand virker klog, hvis han ikke bliver spurgt og får lov at sidde med tør hud på bænken.", "Stanza 30"],
    ["Klog synes gæsten, som spotter en anden gæst og så flygter; men den, som ler ved måltidet, ved ikke sikkert, om han ler blandt fjender.", "Stanza 31"],
    ["Mænd er ofte venlige mod hinanden, men strides alligevel ved måltidet; denne splid vil altid findes: at gæst kæmper mod gæst.", "Stanza 32"],
    ["Morgenvad (morgenmad) skal man ofte spise, før man går på besøg, medmindre man skal til en ven; ellers sidder man og stirrer sulten og kan ikke tage del i samtalen.", "Stanza 33"],
    ["En stor omvej er der til en dårlig ven, selvom hans hus ligger ved vejen; men til en god ven fører lige stier, selvom han bor langt borte.", "Stanza 34"],
    ["Gå skal man, en gæst skal ikke altid blive på samme sted; det kære bliver kedeligt, hvis man sidder for længe på en andens bænk.", "Stanza 35"],
    ["Eget hjem er bedst, selvom det er lille; enhver er herre i sit eget hus. To geder og et flettet tag er bedre end at tigge.", "Stanza 36"],
    ["Eget hjem er bedst, selvom det er lille; enhver er herre i sit eget hus. Hjertet bløder på den, som må bede om mad til hvert måltid.", "Stanza 37"],
    ["Fra sine våben på marken skal man ikke vige en fodsbred; for man ved aldrig, hvornår man på vejen kan få brug for sit spyd.", "Stanza 38"],
    ["Jeg fandt ingen mand så gavmild eller gæstfri, at han ikke tog imod en gave, eller så ødsel med sit gods, at tak var ham uvelkommen.", "Stanza 39"],
    ["Sit gods, som man har vundet, skal man ikke spare for meget; ofte gemmes det til fjenden, som var tænkt til vennen: Meget går værre, end man tror.", "Stanza 40"],
    ["Med våben og klæder skal venner glæde hinanden, det er mest synligt på én selv; gave og gengave gør venskabet varigt, om det ellers går vel.", "Stanza 41"],
    ["Sin ven skal man være ven og gengælde gave med gave; latter skal man møde med latter, men svig med løgn.", "Stanza 42"],
    ["Sin ven skal man være ven, ham selv og hans ven; men ingen mands uvens ven skal man nogensinde være.", "Stanza 43"],
    ["Ved du, om du har en ven, som du stoler godt på, og du vil have gavn af ham, skal du dele tanker med ham og bytte gaver, gå ofte og besøg ham.", "Stanza 44"],
    ["Har du derimod en anden, som du stoler dårligt på, og du vil alligevel have gavn af ham, skal du tale fagre ord til ham, men tænke svigagtigt og gengælde løgn med løgn.", "Stanza 45"],
    ["Det er også sådan med den, du mistror, og som du aner svig hos: Du skal le med ham og tale mod din vilje; gaven skal gengældes med lighed.", "Stanza 46"],
    ["Ung var jeg engang, jeg vandrede alene og foer vild på vejen; rig følte jeg mig, da jeg mødte en anden: Mand er mands gammen (glæde).", "Stanza 47"],
    ["Gavmilde, tapre mænd lever bedst, de kender sjældent sorg; men den feje mand frygter alt, og den gerrige gruer altid for gaver.", "Stanza 48"],
    ["Mine klæder gav jeg på marken til to trémænd; kæmper syntes de at være, da de fik klæder: Skamfuld er den nøgne mand.", "Stanza 49"],
    ["Fyrren dør, som står på et øde sted, hverken bark eller nåle beskytter den; sådan er mennesket, som ingen elsker: Hvordan skal han leve længe?", "Stanza 50"],
    ["Hedere end ild brænder blandt falske venner kærligheden i fem dage; men den slukkes, når den sjette kommer, og hele venskabet falder fra hinanden.", "Stanza 51"],
    ["Ikke kun store ting skal man give; ofte køber man sig ros med lidt. Med et halvt brød og en skråstillet krukke vandt jeg mig en fælle.", "Stanza 52"],
    ["Små sandkorn, små søer, småt er menneskenes vid; ikke alle mennesker er lige kloge, hvert mål er halvvejs.", "Stanza 53"],
    ["Middelmådig klog bør enhver mand være, aldrig alt for vis; det liv er smukkest at leve for dem, der ved vel, hvad de ved.", "Stanza 54"],
    ["Middelmådig klog bør enhver mand være, aldrig alt for vis; for en vis mands hjerte er sjældent glad, hvis han er blevet alt for klog.", "Stanza 55"],
    ["Middelmådig klog bør enhver mand være, aldrig alt for vis; sin skæbne bør ingen vide på forhånd, da er sindet mest frit for sorg.", "Stanza 56"],
    ["Brand tændes af brand, til den er udbrændt, ild bliver af ild vakt; mand bliver af mand kendt gennem tale, men af ensomhed bliver man dum.", "Stanza 57"],
    ["Tidligt skal han stå op, som vil have en andens eje eller liv; sjældent fanger sovende ulv et bytte, eller sovende mand sejren.", "Stanza 58"],
    ["Tidligt skal han stå op, som har få folk, og selv gå til arbejdet; meget forsømmes af den, der sover morgenstunden væk: Den flittige er halvvejs rig.", "Stanza 59"],
    ["Om tørt træ og om birkebark ved manden at tage mål, og om brændet, som skal ligge på lager for uger og måneder.", "Stanza 60"],
    ["Vasket og mæt skal man ride til tings, selvom man ikke er så godt klædt; sine sko og bukser skal ingen skamme sig over, og heller ikke hesten, om man ikke har en god en.", "Stanza 61"],
    ["Snapper og snapper, når han kommer til havet, gør ørnen ved den gamle flod; sådan er manden, som kommer blandt mange og har få, der taler hans sag.", "Stanza 62"],
    ["Spørge og svare skal enhver klok mand, som vil kaldes vis; én får det at vide, men ikke en anden: Ved tre det, så ved hele verden det.", "Stanza 63"],
    ["Sin magt skal enhver vis mand bruge med måde; for man finder ud af, når man kommer blandt de tapre, at ingen er den allerfremmeste.", "Stanza 64"],
    ["Ord, som man taler til en anden, må man ofte betale dyrt for.", "Stanza 65"],
    ["Alt for tidligt kom jeg til mange steder, og for sent til nogle; øllet var drukket eller ikke brygget: Sjældent kommer den uvelkomne til rette tid.", "Stanza 66"],
    ["Her og der havde man budt mig hjem, hvis jeg ikke havde haft brug for mad ved måltidet, eller hvis to skinker havde hængt hos den trofaste ven, hvor jeg havde spist én.", "Stanza 67"],
    ["Ild er det bedste for menneskenes børn, og solens skin; sin helse, om man kan beholde den, og et ulasteligt liv.", "Stanza 68"],
    ["En mand er ikke helt ulykkelig, selvom han er syg; nogle er rige på sønner, nogle på frænder, nogle på meget godt, nogle på velgjorte værker.", "Stanza 69"],
    ["Bedre er det at leve end ikke at leve; den levende får altid koen. Jeg så den riges ild brænde, men uden for døren lå han død.", "Stanza 70"],
    ["Den halte kan ride, den håndløse kan hyrde, den døve kan kæmpe og duge; at være blind er bedre end at brændes: En død mand er til ingen nytte.", "Stanza 71"],
    ["En søn er bedre, selvom han er sent født, efter at faren er væk; sjældent står bautasten ved vejen, hvis de ikke er rejst af frænde for frænde.", "Stanza 72"],
    ["To er tungens morder; hovedet er hjertets fjende. I hver næve venter jeg den skjulte arm under kappen.", "Stanza 73"],
    ["På natten stoler den, som stoler på sit forråd; korte er skibsplankerne, ustadig er efterårsnatten. Vejret skifter ofte på fem dage og endnu mere på en måned.", "Stanza 74"],
    ["Den ved intet, som intet ved: Mange bliver tåber af rigdom. En mand er rig, en anden fattig; anklag ham ikke for dårskab af den grund.", "Stanza 75"],
    ["Fæ dør, frænder dør, man dør selv på samme vis; men ordet om dig dør aldrig, for den som har vundet et godt ry.", "Stanza 76"],
    ["Fæ dør, frænder dør, man dør selv på samme vis; jeg ved ét, som aldrig dør: dommen over hver død mand.", "Stanza 77"],
    ["Fulde stalde så jeg hos Fitjungs sønner, nu bærer de tiggerstaven; sådan er rigdom som et øjekast: Den er den mest ustadige af venner.", "Stanza 78"],
    ["Den uforstandige mand, om han får rigdom eller en kvindes kærlighed, da vokser stoltheden, men ikke viddet: Han går stadig videre i sit hovmod.", "Stanza 79"],
    ["Det er nu prøvet, det du spørger runerne om, de som stammer fra guder, som de høje magter skabte og stortaleren malede: Han gør bedst i at tie.", "Stanza 80"],
    ["Om aftenen skal man dagen prise, konen når hun er brændt, sværdet når det er prøvet, møen når hun er gift, isen når man er over, øllet når det er drukket.", "Stanza 81"],
    ["I vind skal man ved fælde, i godt vejr ro på havet, i mørket tale med møer (mange er dagens øjne); skibe er til at fare med, skjold til at værne, sværd til at hugge og møer til at kysse.", "Stanza 82"],
    ["Ved ild skal man øl drikke, på isen glide, købe mager hest og rustent sværd; hesten skal fodres hjemme, men hunden hos en anden.", "Stanza 83"],
    ["En møs ord skal ingen tro, heller ikke hvad en kvinde taler; for på et drejende hjul blev deres hjerter skabt, og ustadighed lagt i deres bryst.", "Stanza 84"],
    ["Bristende bue, brændende lue, gabende ulv, gispende krage, gryntende svin, rodløst træ, voksende bølge, kogende kedel,", "Stanza 85"],
    ["flyvende pil, faldende flod, isen af en nat, ringlagt slange, brudetale i sengen eller knust sværd, legende bjørn eller kongebarn,", "Stanza 86"],
    ["sygt kalv, selvvilling træl, vølvens smiger, den nyslagne på valpladsen,", "Stanza 87"],
    ["halvbrændt hus, hurtig hest (for én fod gør hesten unyttig): ingen være så tillidsfuld, at han tror på alt dette.", "Stanza 88"],
    ["Sin broders morder, om man møder ham på vejen, brændende hus, hurtig hest (da er en økse mest nyttig): hvem er så tillidsfuld, at han tror på alt dette!", "Stanza 90"],
    ["At tro på kærlighed fra kvinder med svig i sinde er som at ride med uskoede heste på glat is, med kåde toårs-heste, eller i hård storm med et styreløst skib, eller som en halt, der i tøvejr skal fange rener på fjeldet.", "Stanza 91"],
    ["Åbent vil jeg nu tale, for jeg kender begge: ustadigt er mænds sind mod kvinder; når vi taler fagreste, tænker vi falskest: det dårer selv den kloke.", "Stanza 92"],
    ["Fagert skal man tale og gods byde, hvis man vil vinde en kvindes kærlighed; prise den fagre møs krop: den som smigrer, han vinder.", "Stanza 93"],
    ["For kærlighed skal aldrig en mand laste en anden; ofte fanger den kloke det, som ikke rører tåben: den fagre skikkelse.", "Stanza 94"],
    ["Aldrig skal en mand laste en anden for dårskab, som rammer mange; verdens gang gør ofte kloke mænd til tåber gennem begærets magt.", "Stanza 95"],
    ["Sindet alene ved, hvad der bor nær hjertet, det alene kender sin hu; ingen plage er værre for en klok mand end ikke at være tilfreds med sig selv.", "Stanza 96"],
    ["Det erfarede jeg selv, da jeg sad i sivet og ventede på min kære; liv og sjæl var den kloke mø for mig, og alligevel fik jeg hende ikke.", "Stanza 97"],
    ["Billings mø fandt jeg på sengen, solvithvid, sovende; en jarls glæde syntes mig intet værd, hvis jeg ikke fik leve ved den krop.", "Stanza 98"],
    ["'Mod aften, Odin, skal du komme, hvis du vil vinde møen; det er højst usømmeligt, hvis ikke vi alene deler en sådan løn.'", "Stanza 99"],
    ["Jeg vendte tilbage og troede mig elsket, sikker i min vildfarelse; jeg troede, jeg havde vundet al hendes gunst og glæde.", "Stanza 100"],
    ["Og om morgenen, da jeg kom atter, var sal-vagten vågnet; en hund fandt jeg på den gode seng hos kvinden, bunden der i hendes sted.", "Stanza 101"],
    ["Mangen fager mø, om man kender hende nøjere, er falsk i sind mod mænd; det erfarede jeg, da jeg den kloge mø lokkede til elskov: Al slags skam lagde den listige på mig, og jeg vandt ikke kvinden.", "Stanza 102"],
    ["Hjemme skal man være glad og mod gæster munter, sindig med sig selv; den som vil være vis, må have megen kundskab og ofte mindes det gode.", "Stanza 103"],
    ["Den gamle jætte (Suttung) søgte jeg op, nu er jeg tilbage; lidt vandt jeg der ved at tie. Med mange ord talte jeg til min fordel i Suttungs sale.", "Stanza 104"],
    ["Gunnlød gav mig på den gyldne stol en drik af den dyre mjød; dårlig løn lod jeg hende få bagefter for hendes ærlige sind, for hendes tunge elskov.", "Stanza 105"],
    ["Rati lod jeg gnave vej og bore gennem stenen; over og under mig var jætte-vejene: Således satte jeg mit hoved i pant.", "Stanza 106"],
    ["Den købte skikkelse har jeg brugt vel, den vise skorter sjældent på råd; for Odrører er nu kommet op til gudernes bolig.", "Stanza 107"],
    ["Tvivlrådig er jeg, om jeg var kommet tilbage fra jætte-gårdene, hvis jeg ikke havde brugt Gunnlød, den gode kvinde, som lagde armen om mig.", "Stanza 108"],
    ["Dagen efter gik rimturserne for at spørge i Den Højes hal efter Den Høje; de spurgte om Bølværk var hos guderne, eller om Suttung havde dræbt ham.", "Stanza 109"],
    ["Ring-ed, siger de, har Odin svoret; hvem skal man nu tro på? Suttung har han svigtet ved drikken og ladet Gunnlød sidde tilbage i gråd.", "Stanza 110"],
    ["Tid er det at tale fra talerstolen ved Urds brønd; jeg så og tav, jeg så og tænkte, jeg lyttede til mændenes tale.", "Stanza 111"],
    ["Om runer hørte jeg dem råde, heller ikke skortede det på råd; i Den Højes hal, i Den Højes sale, hørte jeg dem tale således:", "Stanza 112"],
    ["Jeg råder dig, Loddfåvne, tag imod rådet; du har nytte om du tager det, held om du følger det: Stå ikke op om natten, medmindre du skal spejde eller gå ud i ærinde.", "Stanza 113"],
    ["Jeg råder dig, Loddfåvne, tag imod rådet: Sov ikke i armene på en troldkyndig kvinde, så hun ikke fanger dig med sine lemmer.", "Stanza 114"],
    ["Hun gør det således, at du ikke bryder dig om tinget eller kongens tale; mad nægter du og menneskers glæde, fuld af sorg går du til søvns.", "Stanza 115"],
    ["Jeg råder dig, Loddfåvne, tag imod rådet: Lok aldrig en anden mands kone til lønlig elskov.", "Stanza 116"],
    ["Jeg råder dig, Loddfåvne, tag imod rådet: Skal du rejse over fjeld eller fjord, udrust dig vel med niste.", "Stanza 117"],
    ["Jeg råder dig, Loddfåvne, tag imod rådet: Lad aldrig en ond mand få vide din ulykke; for af en ond mand får du aldrig løn for din gode tillid.", "Stanza 118"],
    ["Jeg så en mand blive dødeligt såret af ordene fra en ond kvinde; en falsk tunge blev hans bane, og det uden sand klage.", "Stanza 119"],
    ["Jeg råder dig, Loddfåvne, tag imod rådet: Har du en ven du stoler på, drag ofte og besøg ham; for krat vokser og højt græs på vejen, som ingen går.", "Stanza 120"],
    ["Jeg råder dig, Loddfåvne, tag imod rådet: En god mand skal du vinde dig til glæde, og lær dig lægemidler at kende.", "Stanza 121"],
    ["Jeg råder dig, Loddfåvne, tag imod rådet: Vær aldrig den første til at bryde båndet med din ven; sorg æder hjertet, hvis du ikke kan sige din hele hu til nogen.", "Stanza 122"],
    ["Jeg råder dig, Loddfåvne, tag imod rådet: Ord skal du aldrig skifte med en uvittig tåbe.", "Stanza 123"],
    ["For af en ond mand vil du aldrig få godt som løn; men en god mand vil gøre dig værdifuld ved sin ros.", "Stanza 124"],
    ["Delt sindelag er det, når man siger alt sit sind til en anden; alt er bedre end at være falsk: Ingen ven er den, som bare taler efter munden.", "Stanza 125"],
    ["Jeg råder dig, Loddfåvne, tag imod rådet: Selv med tre ord skal du ikke skændes med en ringere mand; ofte fælder den dårligere den bedre, når denne drager sværdet.", "Stanza 126"],
    ["Jeg råder dig, Loddfåvne, tag imod rådet: Vær ikke skomager eller skaftmager, uden for dig selv; for hvis skoen sidder dårligt eller skaftet er skævt, vil man ønske dig alt ondt.", "Stanza 127"],
    ["Jeg råder dig, Loddfåvne, tag imod rådet: Hvor du end ser uret, nævn det som uret, og giv dine fjender ingen fred.", "Stanza 128"],
    ["Jeg råder dig, Loddfåvne, tag imod rådet: Glæd dig aldrig over det onde, men vær det gode hengiven.", "Stanza 129"],
    ["Jeg råder dig, Loddfåvne, tag imod rådet: Se ikke op i kamp (for menneskenes børn bliver som vanvittige), så mænd ikke fortryller dig.", "Stanza 130"],
    ["Jeg råder dig, Loddfåvne, tag imod rådet: Vil du vinde en kvindes kærlighed, hold fast dine løfter; ingen bliver træt af det gode, hvis han får det.", "Stanza 131"],
    ["Jeg råder dig, Loddfåvne, tag imod rådet: Vær varsom, men ikke for bange; vær mest varsom med drikken og med en anden mands kone.", "Stanza 132"],
    ["Jeg råder dig, Loddfåvne, tag imod rådet: Spot aldrig en gæst eller en vandrer, og le ikke af ham.", "Stanza 133"],
    ["Jeg råder dig, Loddfåvne, tag imod rådet: Le aldrig af en gråhåret taler; ofte er det godt, det de gamle siger. Fra rynket hud kommer ofte kloge ord.", "Stanza 134"],
    ["Ofte hænger de mellem huderne, dingler under skindene og slæber blandt de visne.", "Stanza 135"],
    ["Jeg råder dig, Loddfåvne, tag imod rådet: Skæld ikke ud på gæsten og jag ham ikke på dør; vær god mod de fattige.", "Stanza 136"],
    ["Stærk er den dørstolpe, som skal åbne sig for alle; giv en ring, ellers vil man ønske dig hver ulykke.", "Stanza 137"],
    ["Jeg ved, at jeg hang på det vindblæste træ i ni hele nætter, såret med spyd og givet til Odin, jeg selv til mig selv.", "Stanza 138"],
    ["På det træ, som ingen ved, hvor rødderne rinder af.", "Stanza 139"],
    ["De rækker mig hverken brød eller drikkehorn; jeg spejdede ned, jeg tog runerne op, skrigende tog jeg dem, og faldt så ned derfra.", "Stanza 140"],
    ["Da begyndte jeg at gro og være vis, at vokse og trives vel; ord fulgte ord til nyt ord, værk fulgte værk til nyt værk.", "Stanza 141"],
    ["Runer skal du finde og læsbare stave, meget store stave, meget mægtige stave, som stortaleren malede og de høje magter skabte og gudernes Hroptr ristede.", "Stanza 142"],
    ["Odin blandt aser, for alfer Daínn, Dvalin for dværge, Allsvinn for jætter; jeg selv ristede nogle for menneskenes børn.", "Stanza 143"],
    ["Ved du, hvordan man skal riste? Ved du, hvordan man skal råde? Ved du, hvordan man skal male? Ved du, hvordan man skal prøve? Ved du, hvordan man skal bede? Ved du, hvordan man skal ofre? Ved du, hvordan man skal sende? Ved du, hvordan man skal slette?", "Stanza 144"],
    ["Bedre er intet bedt end for meget ofret, en gave ser altid efter gengæld; bedre er intet sendt end for meget slettet. Således ristede Thundr før folkenes historie, dér hvor han steg op, da han kom tilbage.", "Stanza 145"],
    ["De sange kender jeg, som ingen dronning kan og ingen mands søn. 'Hjælp' hedder den første, for den hjælper dig i strid og sorg og i alle kvaler.", "Stanza 146"],
    ["En anden kender jeg, som menneskenes børn har brug for, de som vil leve som læger: at helbrede sår og lindre sygdom.", "Stanza 147"],
    ["En tredje kjenner jeg: hvis jeg har stor nød for at lænke mine fjender, så sløver jeg æggen på modstandernes våben; hverken våben eller svig hjælper dem da.", "Stanza 148"],
    ["En fjerde kender jeg: hvis mænd lægger bånd på mine lemmer, så synger jeg således, at jeg kan gå; lænken springer fra fødderne og båndet fra hænderne.", "Stanza 149"],
    ["En femte kender jeg: hvis jeg ser en pil flyve, som vil skade i hæren, så flyver den ikke så hurtigt, at jeg ikke standser den, om jeg får øje på den.", "Stanza 150"],
    ["En sjette kender jeg: hvis en mand vil skade mig med rødderne af et fremmed træ, så rammer ulykken ham selv og ikke mig.", "Stanza 151"],
    ["En syvende kender jeg: hvis jeg ser salen brænde omkring mine bænkekammerater, så brænder den ikke så hedt, at jeg ikke redder den; den galder kan jeg synge.", "Stanza 152"],
    ["En ottende kender jeg, som er nyttig for alle at lære: hvor had vokser mellem fyrstesønner, dér kan jeg hurtigt dæmpe det.", "Stanza 153"],
    ["En niende kender jeg: hvis nød tvinger mig til at redde mit skib på havet, så stiller jeg vinden på bølgerne og luller hele havet i søvn.", "Stanza 154"],
    ["En tiende kender jeg: hvis jeg ser gandreid-kvinder lege i luften, så gør jeg således, at de forvilder sig fra deres egne huder og deres eget sind.", "Stanza 155"],
    ["En ellevte kender jeg: hvis jeg skal lede gamle venner til strid, så synger jeg under skjoldene, og de drager med magt; hele til strid, hele fra strid, de kommer hele overalt.", "Stanza 156"],
    ["Et tolvte kender jeg: hvis jeg ser en hængt mand i et træ, så rister og maler jeg runer således, at manden går og taler med mig.", "Stanza 157"],
    ["Et trettende kender jeg: hvis jeg øser vand over en ung kriger, så vil han ikke falde, selvom han drager i kamp; intet sværd hugger ham.", "Stanza 158"],
    ["Et fjortende kender jeg: hvis jeg skal tælle guder op for folk, aser og alfer, så kender jeg alle vel; sjældent kender en uvittig dem således.", "Stanza 159"],
    ["Et femtende kender jeg, som dværgen Tjodreir sang foran Dellings døre: han sang kraft til aser, ære til alfer og visdom til Hroptr.", "Stanza 160"],
    ["Et sekstende kender jeg: hvis jeg vil have en klok møs elskov og lyst, så vender jeg sindet hos den hvidarmede kvinde og vender hele hendes hjerte.", "Stanza 161"],
    ["Et syttende kender jeg, så den unge mø aldrig vil skille sig fra mig; disse sange, Loddfåvne, vil du længe mangle.", "Stanza 162"],
    ["Et attende kender jeg, som jeg aldrig lærer til mø eller mands kone, undtagen til den ene, som min arm favner, eller som er min søster; alt er bedre, når kun én ved det.", "Stanza 163"],
    ["Nu er Den Højes tale talt i Den Højes hal, nyttig for menneskenes børn, unyttig for jætternes sønner. Held til den, der talte! Held til den, der kender! Nytte har den, der lærte! Held til dem, der lyttede!", "Stanza 164"]
];