export const deutsch = [

    ["An jeder Tür, bevor man eintritt, soll man spähend schauen, soll man spähend gaffen; denn man weiß nicht sicher, wo Feinde sitzen auf den Bänken drinnen.", "Stanza 1"],
    ["Heil dem Geber! Ein Gast ist gekommen: Wo soll er sitzen? Eilig hat es der, der auf dem Estrich sein Glück versuchen soll.", "Stanza 2"],
    ["Feuer braucht, wer hereingekommen ist und an den Knien friert; Speise und Kleidung braucht der Mann, der über den Berg gereist ist.", "Stanza 3"],
    ["Wasser braucht, wer zur Mahlzeit kommt, ein Handtuch und freundliche Nötigung; einen guten Namen, wenn er ihn erlangen kann, und Schweigen nach der Rede.", "Stanza 4"],
    ["Witz braucht, wer weit reist; zu Hause ist alles leicht. Zum Spott wird, wer nichts weiß und bei Klugen sitzt.", "Stanza 5"],
    ["Mit seinem Stolz soll man nicht prahlen, eher vorsichtig im Geiste sein; wenn ein kluger und schweigsamer Gast zum Hof kommt, geschieht dem Vorsichtigen selten Unheil.", "Stanza 6"],
    ["Der vorsichtige Gast, der zur Mahlzeit kommt, schweigt und horcht; mit den Ohren lauscht er, mit den Augen späht er: So erkundet sich jeder Weise.", "Stanza 7"],
    ["Beglückt ist, wer sich selbst Lob und Gunst erwirbt; denn schwer ist das zu besitzen, was man im Busen eines anderen finden muss.", "Stanza 8"],
    ["Heil ist der, der selbst Lob und Klugheit besitzt, solange er lebt; denn übler Rat ist oft aus dem Busen eines anderen gekommen.", "Stanza 9"],
    ["Keine bessere Last trägt ein Mann auf dem Wege als vieles Wissen; besser als Gold ist es in der Fremde, es ist der Zufluchtsort des Armen.", "Stanza 10"],
    ["Keine bessere Last trägt ein Mann auf dem Wege als vieles Wissen; keine schlechtere Wegzehrung gibt es für die Reise als übermäßiges Trinken.", "Stanza 11"],
    ["Nicht so gut ist, wie man sagt, das Bier für die Menschenkinder; denn je mehr er trinkt, desto weniger weiß der Mann, was seinen Verstand beherrscht.", "Stanza 12"],
    ["Der Reiher des Vergessens heißt er, der über dem Gelage schwebt; er stiehlt den Verstand des Mannes. Mit den Federn dieses Vogels wurde ich in Gunnlöðs Garten gefesselt.", "Stanza 13"],
    ["Trunken wurde ich, ich wurde übermäßig trunken bei dem klugen Fjalarr; das ist das Beste am Trinken, dass jeder danach seinen Verstand wiederbekommt.", "Stanza 14"],
    ["Schweigsam und bedächtig soll ein Königssohn sein und kühn im Kampf; froh und heiter soll jeder Mann sein, bis er den Tod erwartet.", "Stanza 15"],
    ["Der unkluge Mann glaubt, er werde ewig leben, wenn er den Kampf meidet; doch das Alter gibt ihm keinen Frieden, selbst wenn die Speere ihn verschonen.", "Stanza 16"],
    ["Der Tor gafft, wenn er zu Besuch kommt, er schwätzt oder starrt; doch sobald er einen Schluck trinkt, zeigt sich sofort, was in ihm steckt.", "Stanza 17"],
    ["Nur der weiß, der weit gereist ist und viel gewandert, welcher Geist in jedem Mann wohnt; er selbst hat Verstand.", "Stanza 18"],
    ["Halte den Becher nicht fest, doch trink das Met in Maßen; sprich Notwendiges oder schweige. Niemand wird dich der Unhöflichkeit bezichtigen, wenn du früh schlafen gehst.", "Stanza 19"],
    ["Der gierige Mann, es sei denn, er zügelt seinen Verstand, isst sich zu Tode; oft bringt der Bauch dem Unklugen Spott ein, wenn er unter Klugen ist.", "Stanza 20"],
    ["Das Vieh weiß, wann es heimgehen soll, und verlässt dann die Weide; aber der unkluge Mann kennt nie das Maß seines Bauches.", "Stanza 21"],
    ["Ein elender Mann mit bösartigem Sinn verspottet alles; er weiß nicht das, was er wissen müsste: dass er selbst nicht ohne Fehler ist.", "Stanza 22"],
    ["Der unkluge Mann wacht die ganze Nacht und grübelt über alles nach; so ist er am Morgen erschöpft, und all sein Jammer ist wie zuvor.", "Stanza 23"],
    ["Der unkluge Mann glaubt, dass alle, die ihn anlachen, seine Freunde seien; er merkt nicht, wenn er unter Klugen sitzt, dass sie schlecht über ihn reden.", "Stanza 24"],
    ["Der unkluge Mann glaubt, dass alle, die ihn anlachen, seine Freunde seien; wenn er dann zum Thing kommt, findet er nur wenige Fürsprecher.", "Stanza 25"],
    ["Der unkluge Mann glaubt alles zu wissen, wenn er in einem sicheren Winkel sitzt; aber er weiß nicht, was er antworten soll, wenn ihn Männer prüfen.", "Stanza 26"],
    ["Der unkluge Mann, wenn er unter Leute kommt, tut am besten daran zu schweigen; niemand weiß, dass er nichts kann, es sei denn, er redet zu viel. Wer nichts weiß, merkt nicht einmal, wenn er zu viel spricht.", "Stanza 27"],
    ["Klug scheint der, der zu fragen versteht und auch zu antworten weiß; die Menschenkinder können nicht verbergen, was unter ihnen vorgeht.", "Stanza 28"],
    ["Vieles Unnütze spricht, wer nie schweigt, mit bedeutungslosen Worten; die schnelle Zunge, die keinen Zügel kennt, schwätzt sich oft Unheil herbei.", "Stanza 29"],
    ["Man soll keinen anderen zum Gespött machen, auch wenn er zu Besuch kommt; mancher scheint klug, wenn er nicht gefragt wird und mit trockener Haut auf der Bank sitzt.", "Stanza 30"],
    ["Klug scheint der Gast, der den Gast verspottet und sich dann davonstiehlt; doch wer beim Mahle spottet, weiß nicht sicher, ob er nicht unter Feinden lacht.", "Stanza 31"],
    ["Männer sind oft untereinander freundlich und streiten doch beim Mahle; diese Zwietracht wird es immer geben: Gast kämpft gegen Gast.", "Stanza 32"],
    ["Frühstücken soll man oft, bevor man zu Besuch geht, es sei denn, man geht zu einem Freund; sonst sitzt man da, starrt hungrig und gafft, und kann kaum an der Rede teilnehmen.", "Stanza 33"],
    ["Ein weiter Umweg ist es zum falschen Freund, auch wenn sein Haus am Wege liegt; aber zum guten Freund führt ein gerader Pfad, selbst wenn er weit weg wohnt.", "Stanza 34"],
    ["Man soll gehen, ein Gast soll nicht immer am selben Ort bleiben; das Liebenswerte wird lästig, wenn man zu lange auf fremden Bänken sitzt.", "Stanza 35"],
    ["Ein eigenes Heim ist besser, auch wenn es klein ist; jeder ist Herr in seinem Haus. Zwei Ziegen und ein strohgedecktes Dach sind besser als Betteln.", "Stanza 36"],
    ["Ein eigenes Heim ist besser, auch wenn es klein ist; jeder ist Herr in seinem Haus. Das Herz blutet dem, der um seine Nahrung bitten muss für jede Mahlzeit.", "Stanza 37"],
    ["Von seinen Waffen auf dem Felde soll man keinen Fußbreit zurückweichen; denn man weiß nie, wann man auf dem Wege des Speeres bedarf.", "Stanza 38"],
    ["Ich fand keinen so freigiebigen Mann oder so gastfreundlich, dass ihm ein Geschenk nicht willkommen wäre, oder so großzügig mit seinem Besitz, dass ihm ein Dank nicht lieb wäre.", "Stanza 39"],
    ["Seines Reichtums, den man erworben hat, soll man nicht zu sehr entbehren; oft wird dem Feind gespart, was für den Freund gedacht war: Vieles geht schlimmer, als man denkt.", "Stanza 40"],
    ["Mit Waffen und Gewändern sollen Freunde sich erfreuen, das ist an einem selbst am sichtbarsten; Geben und Erwidern macht die Freundschaft dauerhaft, wenn es sonst gut ausgeht.", "Stanza 41"],
    ["Seinem Freund soll man Freund sein und Geschenk mit Geschenk vergelten; Lachen soll man mit Lachen erwidern, aber Falschheit mit Betrug.", "Stanza 42"],
    ["Seinem Freund soll man Freund sein, ihm selbst und seinem Freund; aber keines Feindes Freund soll man jemals sein.", "Stanza 43"],
    ["Weißt du, wenn du einen Freund hast, dem du gut vertraust, und du Gutes von ihm willst, so sollst du Gedanken mit ihm teilen und Geschenke tauschen, ihn oft besuchen gehen.", "Stanza 44"],
    ["Hast du aber einen anderen, dem du schlecht vertraust, und du willst doch Gutes von ihm haben, sollst du freundlich zu ihm sprechen, aber falsch dabei denken und Trug mit Lüge vergelten.", "Stanza 45"],
    ["Das ist es auch mit dem, dem du misstraust und bei dem du Argwohn hegst: Du sollst ihn anlächeln und gegen deine Absicht reden; wie die Gabe ist, so soll die Vergeltung sein.", "Stanza 46"],
    ["Jung war ich einst, ich wanderte allein und verlor den Weg; reich fühlte ich mich, als ich einen anderen traf: Der Mensch ist des Menschen Freude.", "Stanza 47"],
    ["Freigiebige, tapfere Männer leben am besten, sie kennen selten Sorge; aber der furchtsame Mann fürchtet alles, und der Geizige bangt stets um Geschenke.", "Stanza 48"],
    ["Meine Kleider gab ich im Feld zwei Holzmännern; Helden schienen sie, als sie die Lumpen trugen: Beschämt ist der nackte Mann.", "Stanza 49"],
    ["Es vertrocknet die Tanne, die auf einer kahlen Stelle steht, weder Rinde noch Nadeln schützen sie; so ist der Mensch, den niemand liebt: Wie soll er lange leben?", "Stanza 50"],
    ["Heißer als Feuer brennt unter falschen Freunden die Liebe für fünf Tage; aber sie erlischt, wenn der sechste kommt, und die ganze Freundschaft verfällt.", "Stanza 51"],
    ["Nicht nur Großes soll man geben; oft erkauft man sich mit Wenigem Lob. Mit einem halben Brot und einem Neigekrug gewann ich mir einen Gefährten.", "Stanza 52"],
    ["Kleine Sandkörner, kleine Seen, klein ist der Verstand der Menschen; nicht alle Menschen sind gleich klug, jedes Maß ist halb.", "Stanza 53"],
    ["Mittelmäßig klug sollte jeder Mann sein, niemals zu weise; denen ist das Leben am schönsten, die wohl wissen, was sie wissen.", "Stanza 54"],
    ["Mittelmäßig klug sollte jeder Mann sein, niemals zu weise; denn das Herz eines Weisen ist selten froh, wenn er allzu weise geworden ist.", "Stanza 55"],
    ["Mittelmäßig klug sollte jeder Mann sein, niemals zu weise; sein Schicksal lerne niemand im Voraus kennen, so bleibt der Sinn am freiesten von Sorge.", "Stanza 56"],
    ["Brand entzündet sich an Brand, bis er ausgebrannt ist, Feuer wird von Feuer entfacht; der Mann wird durch den Mann im Gespräch erkannt, aber durch Starrsinn wird man dumm.", "Stanza 57"],
    ["Früh aufstehen soll, wer eines anderen Besitz oder Leben begehren will; selten fängt der schlafende Wolf eine Beute oder der schlummernde Mann den Sieg.", "Stanza 58"],
    ["Früh aufstehen soll, wer nur wenige Arbeiter hat, und selbst an die Arbeit gehen; vieles versäumt, wer den Morgen verschläft: Der Fleißige ist halb reich.", "Stanza 59"],
    ["Von trockenem Holz und von Birkenrinde weiß der Mann das Maß zu nehmen, und vom Holz, das im Vorrat liegen soll für Wochen und Monate.", "Stanza 60"],
    ["Gewaschen und gesättigt reite man zum Thing, auch wenn man nicht so gut gekleidet ist; seiner Schuhe und Hosen schäme sich niemand, und auch nicht des Pferdes, wenn man kein gutes besitzt.", "Stanza 61"],
    ["Schnappt und schnobert, wenn er zum Meere kommt, der Adler an der alten Flut; so ist der Mann, der unter viele kommt und nur wenige Fürsprecher hat.", "Stanza 62"],
    ["Fragen und Antworten soll jeder Kluge, der weise genannt werden will; einer darf es wissen, ein zweiter nicht: Wenn drei es wissen, weiß es die ganze Welt.", "Stanza 63"],
    ["Seine Macht soll jeder weise Mann mit Maßen gebrauchen; denn man findet es heraus, wenn man unter Tapfere kommt, dass niemand der Allertapferste ist.", "Stanza 64"],
    ["Worte, die man zu einem anderen spricht, muss man oft teuer bezahlen.", "Stanza 65"],
    ["Viel zu früh kam ich an viele Orte, und zu spät an manche; das Bier war getrunken oder noch nicht gebraut: Selten kommt der Unwillkommene zur rechten Zeit.", "Stanza 66"],
    ["Hier und da hätte man mich eingeladen, wenn ich zur Mahlzeit kein Fleisch gebraucht hätte, oder wenn zwei Schinken gehangen hätten bei dem treuen Freund, wo ich einen gegessen hatte.", "Stanza 67"],
    ["Feuer ist das Beste für die Menschenkinder und der Sonne Schein; seine Gesundheit, wenn man sie behalten kann, und ein lasterfreies Leben.", "Stanza 68"],
    ["Ein Mann ist nicht völlig unselig, auch wenn er krank ist; mancher ist an Söhnen reich, mancher an Verwandten, mancher an viel Gutem, mancher an wohlgetanen Werken.", "Stanza 69"],
    ["Besser ist es zu leben als nicht zu leben; der Lebende bekommt immer die Kuh. Ich sah des Reichen Feuer brennen, doch draußen vor der Tür lag er tot.", "Stanza 70"],
    ["Der Lahme kann reiten, der Handlose kann hüten, der Taube kann fechten und taugt; blind zu sein ist besser als verbrannt zu werden: Ein Toter nützt zu gar nichts.", "Stanza 71"],
    ["Ein Sohn ist besser, auch wenn er spät geboren wird, nachdem der Vater dahin ist; selten stehen Bautasteine am Wege, wenn sie nicht der Verwandte für den Verwandten errichtet.", "Stanza 72"],
    ["Zwei sind der Zunge Mörder; das Haupt ist des Herzens Feind. In jeder Faust erwarte ich den verborgenen Arm unter dem Mantel.", "Stanza 73"],
    ["Auf die Nacht freut sich, wer auf seine Vorräte vertraut; kurz sind die Schiffsplanken, unbeständig ist die Herbstnacht. Das Wetter wandelt sich oft in fünf Tagen, und noch mehr in einem Monat.", "Stanza 74"],
    ["Der weiß nichts, der gar nichts weiß: Mancher wird durch Reichtum zum Narren. Ein Mann ist reich, der andere arm; beschuldigt ihn deshalb nicht der Torheit.", "Stanza 75"],
    ["Besitz stirbt, Sippen sterben, man selbst stirbt ebenso; aber der Ruhm stirbt nimmermehr für jeden, der sich einen guten erwarb.", "Stanza 76"],
    ["Besitz stirbt, Sippen sterben, man selbst stirbt ebenso; ich weiß eines, das ewig lebt: das Urteil über jeden Toten.", "Stanza 77"],
    ["Volle Hürden sah ich bei den Söhnen des Fitjungr, nun tragen sie den Bettelstab; so ist der Reichtum wie der Blick eines Auges: Er ist der unbeständigste aller Freunde.", "Stanza 78"],
    ["Der unkluge Mann, wenn er Reichtum erwirbt oder die Liebe einer Frau, dem wächst der Stolz, aber nicht der Verstand: Er geht immer weiter in seinem Dünkel.", "Stanza 79"],
    ["Das ist nun geprüft, was du bei den Runen fragst, die von Göttern stammen, die die hohen Mächte schufen und der Erzredner malte: Er tut am besten, wenn er schweigt.", "Stanza 80"],
    ["Am Abend soll man den Tag loben, die Frau, wenn sie verbrannt ist, das Schwert, wenn es geprüft ist, das Mädchen, wenn es verheiratet ist, das Eis, wenn man hinüber ist, das Bier, wenn es getrunken ist.", "Stanza 81"],
    ["Im Wind soll man Holz fällen, bei gutem Wetter auf das Meer rudern, in der Dunkelheit mit Mädchen plaudern (denn viele Augen sind am Tage); ein Schiff ist zum Fahren da, ein Schild zum Schützen, ein Schwert zum Schlagen und ein Mädchen zum Küssen.", "Stanza 82"],
    ["Bei Feuer soll man Bier trinken, auf dem Eis gleiten, ein mageres Pferd kaufen und ein rostiges Schwert; das Ross soll man zu Hause füttern, den Hund aber bei einem anderen.", "Stanza 83"],
    ["Den Worten eines Mädchens soll niemand vertrauen, noch dem, was eine Frau spricht; denn auf einem drehenden Rad wurde ihr Herz erschaffen, und Wankelmut in ihre Brust gelegt.", "Stanza 84"],
    ["Einem brechenden Bogen, einer brennenden Flamme, einem gähnenden Wolf, einer krächzenden Krähe, einem grunsenden Schwein, einem wurzellosen Baum, einer wachsenden Woge, einem kochenden Kessel,", "Stanza 85"],
    ["einem fliegenden Pfeil, einer fallenden Flut, dem Eis einer Nacht, einer geringelten Schlange, den Bettreden einer Frau oder einem zerbrochenen Schwert, einem Spiel eines Bären oder einem KönigsKind,", "Stanza 86"],
    ["einem kranken Kalb, einem eigenwilligen Knecht, der Schmeichelei einer Seherin, dem frisch Erschlagenen auf dem Feld,", "Stanza 87"],
    ["einem halbverbrannten Haus, einem schnellen Ross (denn ein Fuß macht das Pferd nutzlos): Niemand sei so vertrauensselig, dass er all diesen Dingen traut.", "Stanza 88"],
    ["Seines Bruders Mörder, wenn man ihm auf dem Wege begegnet, einem brennenden Haus, einem schnellen Pferd (da ist ein Ross am nützlichsten): Wer so vertrauensselig ist, dass er all dem traut!", "Stanza 89"],
    ["Der Liebe der Frauen, die Falschheit im Sinn haben, zu vertrauen, ist wie mit unbeschlagenen Pferden auf glattem Eis zu reiten, mit ungestümen Zweijährigen, oder in schwerem Sturm mit einem steuerlosen Schiff, oder wie ein Lahmer, der im Tauwetter ein Rentier auf dem Felsen fangen will.", "Stanza 90"],
    ["Offen will ich nun sprechen, denn ich kenne beide: Wankelmütig ist der Männer Sinn gegen Frauen; wenn wir am schönsten sprechen, denken wir am falschesten: Das betört selbst die Klügste.", "Stanza 91"],
    ["Schön soll sprechen und Gut bieten, wer die Liebe einer Frau gewinnen will; den Körper des schönen Mädchens preisen: Wer schmeichelt, der gewinnt.", "Stanza 92"],
    ["Wegen der Liebe soll niemals ein Mann einen anderen tadeln; oft fesselt den Klugen, was den Toren nicht rührt: die liebreizende Gestalt.", "Stanza 93"],
    ["Niemals soll ein Mann wegen einer Torheit einen anderen tadeln, die vielen Menschen widerfährt; der Weltenlauf macht oft aus klugen Männern Toren durch die Macht der Begierde.", "Stanza 94"],
    ["Der Geist allein weiß, was dem Herzen nahe ist, er allein kennt seinen Sinn; keine Plage ist schlimmer für einen klugen Mann, als mit sich selbst nicht im Reinen zu sein.", "Stanza 95"],
    ["Das erfuhr ich selbst, als ich im Röhricht saß und auf meine Liebe wartete; Leib und Seele war mir das kluge Mädchen, und doch erlangte ich sie nicht.", "Stanza 96"],
    ["Billings Mädchen fand ich auf dem Lager, sonnenweiß, schlafend; die Freuden eines Jarls schienen mir nichts wert, wenn ich nicht bei diesem Körper lebte.", "Stanza 97"],
    ["'Gegen Abend, Odin, sollst du kommen, wenn du das Mädchen gewinnen willst; es ist höchst unschicklich, wenn nicht wir allein ein solches Geheimnis teilen.'", "Stanza 98"],
    ["Ich kehrte zurück und glaubte mich zu lieben, sicher in meinem Wahn; ich dachte, ich hätte all ihre Gunst und Freude gewonnen.", "Stanza 99"],
    ["Als ich das nächste Mal kam, war die ganze wackere Kriegerschar wach; mit brennenden Fackeln und getragenem Holz: So war mir der Weg verwehrt.", "Stanza 100"],
    ["Und am Morgen, als ich wieder kam, war die Saalwache eingeschlafen; eine Hündin fand ich auf dem guten Lager der Frau, dort angebunden statt ihrer selbst.", "Stanza 101"],
    ["Manch schönes Mädchen, wenn man es genau erkennt, ist gegen Männer falsch gesinnt; das erfuhr ich, als ich das kluge Weib zu locken suchte: Jede Schmach häufte die Listige auf mich, und ich gewann das Mädchen nicht.", "Stanza 102"],
    ["Froh soll man zu Hause sein und gegen Gäste heiter, umsichtig bei sich selbst; wer weise sein will, muss vieles wissen und Gutes oft gedenken.", "Stanza 103"],
    ["Den alten Riesen suchte ich auf, nun bin ich zurück; wenig gewann ich dort durch Schweigen. Mit vielen Worten sprach ich zu meinem Vorteil in Suttungs Sälen.", "Stanza 104"],
    ["Gunnlöð gab mir auf dem goldenen Stuhl einen Trunk des teuren Mets; schlechten Lohn ließ ich sie danach haben für ihren ehrlichen Sinn, für ihre schwere Liebe.", "Stanza 105"],
    ["Rati ließ ich den Weg nagen und den Stein durchbohren; über und unter mir waren der Riesen Wege: So setzte ich mein Haupt aufs Spiel.", "Stanza 106"],
    ["Die erkaufte Gestalt habe ich gut genutzt, dem Weisen fehlt es selten an Mut; denn Óðrerir ist nun heraufgekommen zum Wohnsitz der Götter.", "Stanza 107"],
    ["Zweifelhaft wäre es mir, ob ich wiedergekommen wäre aus der Riesen Gehegen, wenn ich Gunnlöð nicht genutzt hätte, die gute Frau, die ihren Arm um mich legte.", "Stanza 108"],
    ["Am nächsten Tag gingen die Hrimthursen, um in des Hohen Halle nach dem Hohen zu fragen; sie fragten, ob Bölverkr bei den Göttern sei oder ob Suttung ihn erschlagen hätte.", "Stanza 109"],
    ["Einen Ring-Eid, so sagt man, hat Odin geschworen; wer soll seinem Vertrauen noch trauen? Den Suttung hat er beim Trunk betrogen und Gunnlöð weinend zurückgelassen.", "Stanza 110"],
    ["Zeit ist es, auf dem Stuhl des Redners zu thronen, an Urds Brunnen; ich sah und schwieg, ich sah und dachte, ich horchte auf der Männer Rede.", "Stanza 111"],
    ["Von Runen hörte ich raten, noch fehlte es nicht an Rat; in des Hohen Halle, in des Hohen Sälen, hörte ich sie so sprechen:", "Stanza 112"],
    ["Ich rate dir, Loddfáfnir, nimm den Rat an; du hast Nutzen, wenn du ihn annimmst, Heil, wenn du ihn befolgst: Steh nachts nicht auf, es sei denn zum Ausspähen oder um draußen Notdurft zu verrichten.", "Stanza 113"],
    ["Ich rate dir, Loddfáfnir, nimm den Rat an: Schlafe nicht im Schoß einer Zauberin, dass sie dich nicht mit ihren Gliedern fesselt.", "Stanza 114"],
    ["Sie bewirkt dann, dass du weder Thing noch des Königs Rede achtest; die Speise verweigerst du und die Freude der Menschen, voller Sorge gehst du schlafen.", "Stanza 115"],
    ["Ich rate dir, Loddfáfnir, nimm den Rat an: Verführe niemals eines anderen Frau zum heimlichen Liebesgeflüster.", "Stanza 116"],
    ["Ich rate dir, Loddfáfnir, nimm den Rat an: Wenn du über Berge oder Fjorde reisen willst, versieh dich gut mit Speise.", "Stanza 117"],
    ["Ich rate dir, Loddfáfnir, nimm den Rat an: Lass niemals einen bösen Mann dein Unglück wissen; denn von einem bösen Mann erhältst du nie Vergeltung für dein gutes Vertrauen.", "Stanza 118"],
    ["Ich sah einen Mann durch die Worte einer bösen Frau tödlich verwundet; eine falsche Zunge wurde ihm zum Tod, und das ohne wahre Anklage.", "Stanza 119"],
    ["Ich rate dir, Loddfáfnir, nimm den Rat an: Wenn du einen Freund hast, dem du gut vertraust, so reise oft zu ihm; denn Gestrüpp wächst und hohes Gras auf dem Weg, den niemand geht.", "Stanza 120"],
    ["Ich rate dir, Loddfáfnir, nimm den Rat an: Einen guten Mann gewinne dir zur Freude und lerne Heilmittel kennen.", "Stanza 121"],
    ["Ich rate dir, Loddfáfnir, nimm den Rat an: Sei niemals der Erste, der die Verbindung zu deinem Freund abbricht; Sorge frisst das Herz, wenn du niemandem deinen ganzen Geist offenbaren kannst.", "Stanza 122"],
    ["Ich rate dir, Loddfáfnir, nimm den Rat an: Worte sollst du niemals mit einem unvernünftigen Toren wechseln.", "Stanza 123"],
    ["Denn von einem bösen Mann wirst du niemals Gutes als Lohn erhalten; aber ein guter Mann wird dich durch sein Lob wertvoll machen.", "Stanza 124"],
    ["Geteilte Gesinnung ist es, wenn man einem anderen seinen ganzen Geist sagt; alles ist besser, als falsch zu sein: Kein Freund ist der, der nur nach dem Munde redet.", "Stanza 125"],
    ["Ich rate dir, Loddfáfnir, nimm den Rat an: Auch mit drei Worten sollst du nicht mit einem schlechteren Mann streiten; oft besiegt der Schlechtere den Besseren, wenn dieser das Schwert zieht.", "Stanza 126"],
    ["Ich rate dir, Loddfáfnir, nimm den Rat an: Sei kein Schuhmacher oder Schaftmacher, außer für dich selbst; denn wenn der Schuh schlecht sitzt oder der Schaft krumm ist, wird man dir Übles wünschen.", "Stanza 127"],
    ["Ich rate dir, Loddfáfnir, nimm den Rat an: Wo immer du Unrecht erkennst, nenne es Unrecht und gib deinen Feinden keinen Frieden.", "Stanza 128"],
    ["Ich rate dir, Loddfáfnir, nimm den Rat an: Erfreue dich niemals am Bösen, sondern sei dem Guten zugetan.", "Stanza 129"],
    ["Ich rate dir, Loddfáfnir, nimm den Rat an: Blicke nicht im Kampf nach oben (denn die Menschenkinder werden wie von Wahnsinn gepackt), damit die Männer dich nicht verhexen.", "Stanza 130"],
    ["Ich rate dir, Loddfáfnir, nimm den Rat an: Wenn du die Liebe einer Frau gewinnen willst, so halte deine Versprechen fest; niemand wird müde des Guten, wenn er es bekommt.", "Stanza 131"],
    ["Ich rate dir, Loddfáfnir, nimm den Rat an: Sei vorsichtig, doch nicht zu ängstlich; sei am vorsichtigsten mit dem Bier und mit der Frau eines anderen.", "Stanza 132"],
    ["Ich rate dir, Loddfáfnir, nimm den Rat an: Spotte niemals über einen Gast oder einen Wanderer, und lache ihn nicht aus.", "Stanza 133"],
    ["Ich rate dir, Loddfáfnir, nimm den Rat an: Lache niemals über einen greisen Sprecher; oft ist es gut, was die Alten sagen. Aus runzligen Häuten kommen oft kluge Worte.", "Stanza 134"],
    ["Oft hängen sie zwischen den Fellen, baumeln unter den Häuten und schlenkern unter den Welken.", "Stanza 135"],
    ["Ich rate dir, Loddfáfnir, nimm den Rat an: Beschimpfe den Gast nicht und jage ihn nicht vor das Tor; sei gütig zu den Armen.", "Stanza 136"],
    ["Stark ist der Türpfosten, der sich für alle öffnen soll; gib einen Ring, oder man wird dir jedes Unheil wünschen.", "Stanza 137"],
    ["Ich weiß, dass ich hing am windigen Baum neun ganze Nächte, vom Speer verwundet und Odin geweiht, ich selbst mir selbst.", "Stanza 138"],
    ["An jenem Baum, von dem niemand weiß, aus welcher Wurzel er entspringt.", "Stanza 139"],
    ["Man reichte mir weder Brot noch den Trinkhorn; ich spähte nach unten, ich nahm die Runen auf, schreiend nahm ich sie, und fiel von dort wieder herab.", "Stanza 140"],
    ["Dann begann ich zu fruchten und weise zu sein, zu wachsen und wohl zu gedeihen; Wort folgte mir aus dem Wort zum Wort, Werk folgte mir aus dem Werk zum Werk.", "Stanza 141"],
    ["Runen wirst du finden und lesbare Stäbe, sehr starke Stäbe, sehr mächtige Stäbe, die der Erzredner malte und die hohen Mächte schufen und die Hroptr der Götter ritzte.", "Stanza 142"],
    ["Odin bei den Asen, für die Alfen Daínn, Dvalinn für die Zwerge, Alsviðr für die Riesen; ich selbst ritzte einige für die Menschenkinder.", "Stanza 143"],
    ["Weißt du, wie man ritzen soll? Weißt du, wie man raten soll? Weißt du, wie man malen soll? Weißt du, wie man prüfen soll? Weißt du, wie man bitten soll? Weißt du, wie man opfern soll? Weißt du, wie man senden soll? Weißt du, wie man tilgen soll?", "Stanza 144"],
    ["Besser ist nicht gebeten als zu viel geopfert, eine Gabe blickt immer nach Vergeltung; besser ist nicht gesendet als zu viel getilgt. So ritzte Thundr vor der Geschichte der Völker, wo er herkam, als er wiederkehrte.", "Stanza 145"],
    ["Jene Lieder kenne ich, die keine Königin kennt und keines Menschen Kind. 'Hilfe' heißt das erste, denn es hilft dir in Streitigkeiten und Sorgen und in allen Qualen.", "Stanza 146"],
    ["Ein zweites kenne ich, das die Menschenkinder brauchen, die als Ärzte leben wollen: Wunden zu heilen und Krankheiten zu lindern.", "Stanza 147"],
    ["Ein drittes kenne ich: Wenn ich große Not habe, meine Feinde zu fesseln, so stumpfe ich die Klingen meiner Gegner ab; weder Waffen noch List helfen ihnen dann.", "Stanza 148"],
    ["Ein viertes kenne ich: Wenn Männer mir Bande an die Glieder legen, so singe ich, dass ich gehen kann; die Fessel springt von den Füßen und das Band von den Händen.", "Stanza 149"],
    ["Ein fünftes kenne ich: Wenn ich einen Pfeil fliegen sehe, der im Heer schaden will, so fliegt er nicht so schnell, dass ich ihn nicht stoppe, wenn ich ihn mit den Augen erblicke.", "Stanza 150"],
    ["Ein sechstes kenne ich: Wenn ein Mann mich schädigen will durch Wurzeln eines fremden Baumes, so trifft das Unheil, das er mir zugedacht, ihn selbst und nicht mich.", "Stanza 151"],
    ["Ein siebtes kenne ich: Wenn ich den Saal brennen sehe um meine Gefährten, so brennt er nicht so heiß, dass ich ihn nicht rette; diesen Zauber kenne ich zu singen.", "Stanza 152"],
    ["Ein achtes kenne ich, das für alle nützlich ist zu lernen: Wo Hass zwischen Fürstensöhnen aufwächst, da kann ich ihn schnell schlichten.", "Stanza 153"],
    ["Ein neuntes kenne ich: Wenn mich Not zwingt, mein Schiff auf der Flut zu retten, so stille ich den Wind auf den Wellen und schläfere das ganze Meer ein.", "Stanza 154"],
    ["Ein zehntes kenne ich: Wenn ich Zaunreiterinnen in der Luft spielen sehe, so bewirke ich, dass sie verwirrt von ihren eigenen Gestalten und ihrem eigenen Geist heimkehren.", "Stanza 155"],
    ["Ein elftes kenne ich: Wenn ich alte Freunde in die Schlacht führen soll, so singe ich unter die Schilde, und sie ziehen mit Macht; heil in die Schlacht, heil aus der Schlacht, sie kommen heil überall an.", "Stanza 156"],
    ["Ein zwölftes kenne ich: Wenn ich an einem Baum einen Gehenkten sehe, so ritze und male ich Runen, dass der Mann geht und mit mir spricht.", "Stanza 157"],
    ["Ein dreizehntes kenne ich: Wenn ich einen jungen Krieger mit Wasser weihe, so wird er nicht fallen, wenn er ins Volk zieht; kein Schwert erschlägt ihn.", "Stanza 158"],
    ["Ein vierzehntes kenne ich: Wenn ich vor dem Volk die Götter aufzählen soll, Asen und Alfen, so kenne ich alle wohl; selten kennt sie ein Unwissender so.", "Stanza 159"],
    ["Ein fünfzehntes kenne ich, das der Zwerg Thjódreir vor Dellings Türen sang: Er sang den Asen Kraft, den Alfen Ruhm und dem Hroptr Verstand.", "Stanza 160"],
    ["Ein sechzehntes kenne ich: Wenn ich eines klugen Mädchens Liebe und Lust haben will, so wende ich den Sinn der weißarmigen Frau und kehre ihr ganzes Herz um.", "Stanza 161"],
    ["Ein siebzehntes kenne ich, dass das junge Mädchen mich niemals meiden will; diese Lieder, Loddfáfnir, wirst du lange entbehren.", "Stanza 162"],
    ["Ein achtzehntes kenne ich, das ich niemals einem Mädchen oder einer Frau lehre, außer der einen, die mein Arm umschlingt oder die meine Schwester ist; alles ist besser, wenn es nur einer weiß.", "Stanza 163"],
    ["Nun sind des Hohen Reden in des Hohen Halle gesprochen, nützlich den Menschenkindern, unnütz den Riesensöhnen. Heil dem, der sprach! Heil dem, der kennt! Nutzen hat, wer lernte! Heil denen, die horchten!", "Stanza 164"]


];