export const french = [

    ["Toutes les portes, avant d'aller de l'avant, doivent être examinées, doivent être inspectées ; car on ne sait jamais où des ennemis sont assis dans la salle.", "Stanza 1"],
    ["Salut aux hôtes ! Un invité est entré, où doit-il s'asseoir ? Bien impatient est celui qui, sur le seuil, doit tenter sa chance.", "Stanza 2"],
    ["Du feu a besoin celui qui est entré et qui a les genoux raidis ; de nourriture et de vêtements d'homme a besoin celui qui a voyagé par les montagnes.", "Stanza 3"],
    ["D'eau a besoin celui qui vient au repas, d'une serviette et d'un accueil bienveillant ; de paroles aimables, s'il peut en obtenir, et d'un silence attentif.", "Stanza 4"],
    ["D'esprit a besoin celui qui voyage loin ; tout est facile à la maison. On devient la risée de tous quand on ne sait rien et qu'on siège parmi les sages.", "Stanza 5"],
    ["De son propre esprit, nul ne doit se vanter, mieux vaut être prudent dans sa pensée ; quand un homme sage et silencieux vient à la ferme, le malheur frappe rarement l'avisé.", "Stanza 6"],
    ["L'invité prudent qui vient au repas se tait et écoute ; de ses oreilles il entend, de ses yeux il observe : ainsi tout homme sage s'informe.", "Stanza 7"],
    ["Heureux est celui qui obtient pour lui-même louange et bienveillance ; car il est difficile de posséder ce qui est caché dans le sein d'un autre.", "Stanza 8"],
    ["Heureux est celui qui possède en lui-même louange et sagesse tant qu'il vit ; car de mauvais conseils ont souvent été puisés dans le sein d'un autre.", "Stanza 9"],
    ["On ne porte pas de meilleur fardeau sur la route qu'un grand bon sens ; c'est mieux que l'or en terre inconnue, c'est le refuge du malheureux.", "Stanza 10"],
    ["On ne porte pas de meilleur fardeau sur la route qu'un grand bon sens ; on ne porte pas de pire provision pour le chemin qu'un excès de bière.", "Stanza 11"],
    ["La bière n'est pas aussi bonne qu'on le dit pour les fils des hommes ; car plus un homme boit, moins il a de contrôle sur son esprit.", "Stanza 12"],
    ["Héron de l'oubli s'appelle celui qui plane sur les beuveries, il dérobe l'esprit des hommes ; par les plumes de cet oiseau j'ai été enchaîné dans la demeure de Gunnlöd.", "Stanza 13"],
    ["Ivre j'ai été, j'ai été plus qu'ivre chez le sage Fjalar ; la meilleure chose dans la beuverie est que chacun retrouve son bon sens après.", "Stanza 14"],
    ["Silencieux et pensif doit être le fils d'un prince, et hardi au combat ; joyeux et gaillard doit être tout homme jusqu'à ce qu'il reçoive la mort.", "Stanza 15"],
    ["L'homme lâche croit qu'il vivra toujours s'il évite les combats ; mais la vieillesse ne lui donne aucun repos, même si les lances l'épargnent.", "Stanza 16"],
    ["Le sot béant, quand il vient chez les gens, marmonne ou reste figé ; mais qu'il boive une gorgée, et aussitôt on voit tout son esprit.", "Stanza 17"],
    ["Seul celui-là sait, qui a beaucoup voyagé et parcouru bien des lieux, quel esprit anime chaque homme ; il est lui-même doué de raison.", "Stanza 18"],
    ["Ne t'attarde pas sur la coupe, bois avec mesure, dis ce qui est utile ou tais-toi ; personne ne te reprochera un manque de manières si tu vas tôt te coucher.", "Stanza 19"],
    ["L'homme glouton, à moins qu'il n'ait du bon sens, mange jusqu'à se rendre malade ; souvent le ventre devient la risée des sages quand il appartient à un homme stupide.", "Stanza 20"],
    ["Les troupeaux savent quand ils doivent rentrer et quittent alors le pâturage ; mais l'homme insensé ne connaît jamais la mesure de son propre ventre.", "Stanza 21"],
    ["L'homme misérable et malveillant se rit de toute chose ; il ne sait pas ce qu'il devrait savoir : qu'il n'est pas lui-même sans défauts.", "Stanza 22"],
    ["L'homme insensé veille toutes les nuits et se tourmente pour tout ; il est épuisé quand vient le matin, et ses soucis sont les mêmes qu'auparavant.", "Stanza 23"],
    ["L'homme ignorant croit que tous ceux qui lui sourient sont ses amis ; il ne remarque pas, assis parmi les sages, que l'on parle contre lui.", "Stanza 24"],
    ["L'homme ignorant croit que tous ceux qui lui sourient sont ses amis ; il s'en aperçoit quand il vient à l'assemblée : il y trouve peu de défenseurs.", "Stanza 25"],
    ["L'homme ignorant croit tout savoir s'il se tient dans son coin ; mais il ne sait que répondre si les hommes le mettent à l'épreuve.", "Stanza 26"],
    ["L'homme ignorant, quand il vient parmi les gens, ferait mieux de se taire ; personne ne saura qu'il ne sait rien, à moins qu'il ne parle trop.", "Stanza 27"],
    ["Sage semble celui qui sait interroger et répondre à son tour ; les fils des hommes ne peuvent cacher ce qui circule parmi le peuple.", "Stanza 28"],
    ["Celui qui ne se tait jamais profère bien des paroles vides ; la langue prompte, si on ne la bride, se chante souvent ses propres malheurs.", "Stanza 29"],
    ["On ne doit pas se moquer d'un hôte, même s'il vient de loin ; beaucoup semblent sages s'ils ne sont pas questionnés et s'ils restent au sec.", "Stanza 30"],
    ["Il semble sage, l'invité qui s'esquive pour éviter les moqueries ; mais celui qui rit au repas ne sait pas s'il rit au milieu de ses ennemis.", "Stanza 31"],
    ["Bien des hommes sont affables les uns envers les autres, mais se querellent à table ; il y aura toujours de la discorde : l'hôte s'en prend à l'hôte.", "Stanza 32"],
    ["Il faut prendre ses repas de bonne heure, à moins d'aller en visite ; sinon on reste assis à béer comme un affamé, incapable d'interroger.", "Stanza 33"],
    ["Le chemin est long vers le mauvais ami, même s'il habite sur la route ; mais vers le bon ami, il y a des raccourcis, même s'il demeure au loin.", "Stanza 34"],
    ["Il faut partir, ne pas être invité toujours au même endroit ; l'ami devient importun s'il reste trop longtemps sur les bancs d'un autre.", "Stanza 35"],
    ["Mieux vaut un chez-soi, si petit soit-il, on est maître chez soi ; posséder deux chèvres et une salle au toit de chaume vaut mieux que de mendier.", "Stanza 36"],
    ["Mieux vaut un chez-soi, si petit soit-il, on est maître chez soi ; le cœur saigne à celui qui doit mendier sa nourriture pour chaque repas.", "Stanza 37"],
    ["De ses armes, on ne doit pas s'écarter d'un pas en plein champ ; car on ne sait jamais quand on aura besoin d'une lance sur son chemin.", "Stanza 38"],
    ["Je n'ai jamais trouvé d'homme si généreux ou si prodigue de ses vivres qu'il refuse un cadeau, ni d'homme si dépensier qu'une récompense lui soit désagréable.", "Stanza 39"],
    ["De son bien, que l'on a acquis, on ne doit pas se priver ; souvent on épargne pour celui qu'on déteste ce qu'on destinait à celui qu'on aime : beaucoup de choses vont moins bien qu'on ne l'espère.", "Stanza 40"],
    ["Par les armes et les vêtements, les amis doivent se réjouir mutuellement, cela se voit sur soi-même ; ceux qui donnent et ceux qui rendent restent amis le plus longtemps, si l'affaire tourne bien.", "Stanza 41"],
    ["À son ami, il faut être ami et rendre don pour don ; il faut rendre rire pour rire et tromperie pour mensonge.", "Stanza 42"],
    ["À son ami, il faut être ami, à lui et à son ami ; mais de l'ami de son ennemi, personne ne doit être l'ami.", "Stanza 43"],
    ["Sache que si tu as un ami en qui tu as pleine confiance et dont tu veux obtenir du bien, tu dois mêler ton esprit au sien, échanger des cadeaux et aller le voir souvent.", "Stanza 44"],
    ["Si tu en as un autre en qui tu as peu de confiance, mais dont tu veux obtenir du bien, tu dois lui dire de belles paroles mais penser avec ruse et rendre tromperie pour mensonge.", "Stanza 45"],
    ["Il en va de même pour celui en qui tu as peu de confiance et dont tu suspectes les intentions : tu dois lui rire au nez, parler contre ta pensée ; les cadeaux rendus doivent être semblables aux cadeaux reçus.", "Stanza 46"],
    ["J'étais jeune autrefois, je voyageais seul, et je m'égarais en chemin ; je me suis cru riche quand j'ai trouvé un autre : l'homme est la joie de l'homme.", "Stanza 47"],
    ["Les hommes généreux et hardis vivent le mieux, ils nourrissent rarement de soucis ; mais l'homme lâche redoute toute chose, et l'avare gémit toujours sur ses cadeaux.", "Stanza 48"],
    ["Mes vêtements, je les ai donnés en plein champ à deux hommes de bois ; ils se sont crus des guerriers quand ils ont eu des habits : la honte est pour l'homme nu.", "Stanza 49"],
    ["Le pin dépérit, celui qui se tient sur une hauteur dénudée, ni l'écorce ni les aiguilles ne le protègent ; ainsi est l'homme que personne n'aime, pourquoi vivrait-il longtemps ?", "Stanza 50"],
    ["Plus chaud que le feu entre de mauvais amis brûle la paix pendant cinq jours ; mais elle s'éteint quand vient le sixième, et toute l'amitié s'envenime.", "Stanza 51"],
    ["Il ne faut pas toujours donner de grands cadeaux ; souvent on s'achète des louanges avec peu. Avec un demi-pain et une coupe penchée, je me suis fait un compagnon.", "Stanza 52"],
    ["Petits sont les grains de sable, petites les mers, petit est l'esprit des hommes ; car tous les hommes ne sont pas également sages, l'humanité est partout incomplète.", "Stanza 53"],
    ["Moyennement sage doit être tout homme, jamais trop sage ; la vie est la plus belle pour ceux qui savent beaucoup de choses, mais avec mesure.", "Stanza 54"],
    ["Moyennement sage doit être tout homme, jamais trop sage ; car le cœur d'un homme sage est rarement joyeux si celui qui le possède est tout à fait savant.", "Stanza 55"],
    ["Moyennement sage doit être tout homme, jamais trop sage ; que personne ne connaisse son destin à l'avance, ainsi l'esprit sera le plus libre de soucis.", "Stanza 56"],
    ["Le tison s'enflamme au tison jusqu'à ce qu'il soit brûlé, le feu s'allume au feu ; l'homme s'instruit au contact de l'homme, mais s'abrutit dans l'isolement.", "Stanza 57"],
    ["Il doit se lever tôt, celui qui veut prendre la vie ou les biens d'un autre ; rarement le loup couché attrape sa proie, ni l'homme endormi la victoire.", "Stanza 58"],
    ["Il doit se lever tôt, celui qui a peu de serviteurs, et vaquer lui-même à sa tâche ; beaucoup de temps perd celui qui dort le matin, l'ardeur fait la moitié de la richesse.", "Stanza 59"],
    ["Des bûches sèches et des morceaux d'écorce, l'homme en connaît la mesure, ainsi que du bois qui peut suffire pour un trimestre ou un semestre.", "Stanza 60"],
    ["Lave-toi, mange à ta faim avant d'aller à l'assemblée, même si tes habits sont pauvres ; ne rougis pas de tes chausses ni de tes souliers, ni de ton cheval, même s'il n'est pas de prix.", "Stanza 61"],
    ["L'aigle crie et se courbe quand il arrive sur la mer ancienne ; ainsi fait l'homme qui se trouve dans une foule sans défenseurs pour l'aider.", "Stanza 62"],
    ["Questionner et répondre, voilà ce que doit faire quiconque veut passer pour sage ; qu'un seul sache, mais pas deux : si trois le savent, le monde entier le sait.", "Stanza 63"],
    ["Sa puissance, tout homme avisé doit l'exercer avec mesure ; quand il se trouve parmi les braves, il voit bien que nul n'est le plus fort de tous.", "Stanza 64"],
    ["Pour les paroles que l'on dit à un autre, on en paie souvent un prix amer.", "Stanza 65"],
    ["Trop tôt je suis venu souvent en visite, et parfois trop tard ; la bière était bue ou n'était pas brassée : l'importun arrive rarement à l'heure.", "Stanza 66"],
    ["On m'inviterait partout à manger si je n'avais pas besoin de nourriture, ou si deux jambons pendaient chez l'ami où j'en ai mangé un seul.", "Stanza 67"],
    ["Le feu est ce qu'il y a de mieux pour les fils des hommes, ainsi que la vue du soleil ; la santé, si on peut la garder, et vivre une vie sans tache.", "Stanza 68"],
    ["On n'est pas tout à fait malheureux même si l'on est malade ; l'un est heureux par ses fils, l'autre par ses parents, l'un par sa richesse, l'autre par ses bonnes œuvres.", "Stanza 69"],
    ["Mieux vaut être vivant que mort, au vivant revient la vache ; j'ai vu le feu brûler chez le riche, mais lui-même gisait mort devant sa porte.", "Stanza 70"],
    ["Le boiteux peut monter à cheval, le manchot peut mener le troupeau, le sourd peut se battre et réussir ; mieux vaut être aveugle que brûlé (mort) : un cadavre n'est bon à rien.", "Stanza 71"],
    ["Un fils vaut mieux, même s'il est né tard après la mort de son père ; on voit rarement des pierres dressées au bord des routes si ce n'est un parent qui les a placées.", "Stanza 72"],
    ["Deux sont les ennemis de la langue, la tête est l'ennemie du cœur ; dans chaque main, j'attends une épée cachée sous le manteau.", "Stanza 74"],
    ["L'insensé ne sait pas que l'argent fait de beaucoup des singes ; l'un est riche, l'autre pauvre, il ne faut pas en blâmer l'homme.", "Stanza 75"],
    ["Les richesses meurent, les parents meurent, on meurt soi-même de la même façon ; mais la renommée ne meurt jamais pour celui qui s'en est acquis une bonne.", "Stanza 76"],
    ["Les richesses meurent, les parents meurent, on meurt soi-même de la même façon ; je sais une chose qui ne meurt jamais : le jugement sur chaque mort.", "Stanza 77"],
    ["Des étables pleines j'ai vues chez les fils de Fitjung, maintenant ils portent le bâton de mendiant ; la richesse est comme un clin d'œil, c'est le plus changeant des amis.", "Stanza 78"],
    ["L'homme stupide, s'il gagne de l'argent ou les faveurs d'une femme, voit son orgueil croître, mais non son bon sens : il s'égare de plus en plus dans son arrogance.", "Stanza 79"],
    ["C'est ce que l'on voit quand on interroge les runes, celles qui viennent des dieux, que les Puissances créèrent et que le Maître-Poète a peintes : le mieux est de se taire.", "Stanza 80"],
    ["À la fin du jour, loue le jour ; la femme, quand elle est brûlée ; l'épée, quand elle a été éprouvée ; la jeune fille, quand elle est mariée ; la glace, quand on l'a traversée ; la bière, quand elle est bue.", "Stanza 81"],
    ["Par le vent, fends le bois ; par beau temps, navigue sur mer ; dans l'obscurité, parle à la jeune fille (car nombreux sont les yeux du jour) ; d'un bateau, cherche la vitesse ; d'un bouclier, la protection ; d'une épée, la frappe ; d'une jeune fille, les baisers.", "Stanza 82"],
    ["Près du feu, bois la bière ; sur la glace, glisse ; achète un cheval maigre et une épée rouillée ; engraisse ton cheval à la maison, mais ton chien chez ton voisin.", "Stanza 83"],
    ["Aux paroles d'une jeune fille, nul ne doit se fier, ni à ce qu'une femme raconte ; car sur une roue tournante leurs cœurs ont été façonnés, l'inconstance a été mise dans leur poitrine.", "Stanza 84"],
    ["À l'arc qui casse, à la flamme qui brûle, au loup qui hurle, au corbeau qui croasse, au sanglier qui grogne, à l'arbre sans racines, à la vague qui monte, au chaudron qui bout,", "Stanza 85"],
    ["à la flèche qui vole, à la lame qui tombe, à la glace d'une nuit, au serpent enroulé, aux paroles de l'épouse au lit ou à l'épée brisée, au jeu de l'ours ou au fils d'un roi,", "Stanza 86"],
    ["au veau malade, à l'esclave volontaire, aux flatteries de la prophétesse, au guerrier fraîchement tombé au combat —", "Stanza 87"],
    ["à un champ tôt semé, nul ne doit se fier, ni trop tôt à son fils ; le temps gouverne le champ et l'esprit gouverne le fils, et tous deux sont incertains.", "Stanza 88"],
    ["Au meurtrier de son frère, s'il se trouve sur ton chemin, à la maison qui brûle, au cheval trop rapide (car alors une arme est fort utile) : ne sois jamais assez confiant pour te fier à tout cela.", "Stanza 89"],
    ["Telle est l'amitié des femmes aux pensées fourbes : comme si l'on menait un cheval non ferré sur la glace glissante, un poulain de deux ans indompté, ou comme si l'on menait un navire sans rames par vent contraire, ou comme si un boiteux chassait un renne sur une pente gelée.", "Stanza 90"],
    ["Je parle ouvertement car je connais les deux : changeant est l'esprit des hommes envers les femmes ; quand nous parlons le plus joliment, c'est là que nous pensons le plus faussement : cela trompe même l'esprit sage.", "Stanza 91"],
    ["Il doit parler doucement et offrir des biens, celui qui veut gagner l'amour d'une femme ; louer la beauté de la jeune fille : celui-là gagne, qui flatte.", "Stanza 92"],
    ["Pour l'amour, personne ne doit jamais en blâmer un autre ; souvent ce qui n'émeut pas le sot capture le sage : la grande beauté.", "Stanza 93"],
    ["On ne doit jamais reprocher à autrui la folie qui frappe beaucoup d'hommes ; la puissante passion fait souvent des sots à partir des sages.", "Stanza 94"],
    ["L'esprit seul sait ce qui vit près du cœur, lui seul connaît son caractère ; il n'y a pas de pire maladie pour l'homme avisé que de ne plus s'aimer soi-même.", "Stanza 95"],
    ["J'en fis l'épreuve quand je m'assis dans les roseaux et que j'attendais mon désir ; cette sage jeune fille était ma chair et mon cœur, et pourtant je ne l'eus point.", "Stanza 96"],
    ["Je trouvai la fille de Billing sur son lit, blanche comme le soleil, endormie ; la joie d'un prince me semblait n'être rien si je ne vivais pas auprès de ce corps.", "Stanza 97"],
    ["« Près du soir, Odin, tu devras revenir, si tu veux parler à la jeune fille ; tout serait perdu si nous n'étions seuls à connaître un tel affront. »", "Stanza 98"],
    ["Je repartis, pensant que l'amour était acquis, trompé par mon désir ; je croyais que j'aurais tout son cœur et toute sa faveur.", "Stanza 99"],
    ["Quand je revins ensuite, toute la garde était éveillée ; avec des lumières brûlantes et des torches portées, ainsi mon chemin était barré.", "Stanza 100"],
    ["Et vers le matin, quand je revins, la garde de la salle dormait ; je trouvai une chienne sur le lit de la bonne femme, attachée avec des liens.", "Stanza 101"],
    ["Mainte bonne fille, si on l'examine de près, est changeante envers les hommes ; je l'ai éprouvé quand j'ai tenté de séduire cette femme avisée : elle m'a accablé de toutes sortes d'affronts, et je n'ai point possédé la dame.", "Stanza 102"],
    ["Chez soi, il faut être joyeux et de bonne humeur avec ses hôtes, être avisé sur soi-même ; être doué de mémoire et de parole si l'on veut être savant, et parler souvent de bonnes choses.", "Stanza 103"],
    ["Je suis allé chez le vieux géant, maintenant je suis revenu ; j'ai peu obtenu là-bas par le silence. Par beaucoup de paroles, j'ai parlé à mon avantage dans les salles de Suttungr.", "Stanza 104"],
    ["Gunnlöd me donna, sur son siège d'or, une gorgée du précieux hydromel ; je lui ai rendu une bien mauvaise récompense pour son cœur sincère, pour son âme profonde.", "Stanza 105"],
    ["J'ai fait en sorte que le bec de Rati se fraye un chemin et ronge la pierre ; au-dessus et au-dessous se trouvaient les chemins des géants : ainsi j'ai risqué ma tête.", "Stanza 106"],
    ["De la beauté achetée j'ai bien profité, peu de choses manquent au sage ; car Óðrerir (l'hydromel) est maintenant monté jusqu'à la demeure des dieux.", "Stanza 107"],
    ["Il m'eût été difficile de revenir des demeures des géants si je ne m'étais pas servi de Gunnlöd, la bonne femme que j'ai tenue dans mes bras.", "Stanza 108"],
    ["Le lendemain, les géants du givre allèrent demander conseil dans la salle du Très-Haut ; ils s'enquirent de Bölverkr (Odin), s'il était revenu parmi les dieux ou si Suttungr l'avait tué.", "Stanza 109"],
    ["Un serment sur l'anneau, je crois qu'Odin l'a prêté ; comment se fier à sa parole ? Il a trompé Suttungr pour obtenir l'hydromel et a laissé Gunnlöd en larmes.", "Stanza 110"],
    ["Il est temps de parler du haut du siège du sage, près de la source d'Urd ; j'ai vu et je me suis tu, j'ai vu et j'ai réfléchi, j'ai écouté les paroles des hommes.", "Stanza 111"],
    ["J'ai entendu parler des runes et des conseils, dans la halle du Très-Haut, j'ai entendu dire ceci :", "Stanza 112"],
    ["Je te conseille, Loddfáfnir, d'accepter ce conseil — tu en profiteras si tu l'acceptes : ne te lève pas la nuit, sauf si tu dois faire le guet ou chercher un lieu à l'écart.", "Stanza 113"],
    ["Je te conseille, Loddfáfnir : ne dors pas dans les bras d'une magicienne, de peur qu'elle ne t'enchaîne de ses membres.", "Stanza 114"],
    ["Elle fera en sorte que tu ne te soucies plus de l'assemblée ni des paroles du roi ; tu ne voudras plus de nourriture ni de plaisir humain, et tu iras te coucher avec tristesse.", "Stanza 115"],
    ["Je te conseille, Loddfáfnir : ne tente jamais la femme d'autrui pour en faire ton amante.", "Stanza 116"],
    ["Je te conseille, Loddfáfnir : si tu dois voyager par la montagne ou le fjord, munis-toi bien de nourriture.", "Stanza 117"],
    ["Je te conseille, Loddfáfnir : ne confie jamais tes malheurs à un homme méchant ; car d'un homme mauvais, tu n'obtiendras jamais de récompense pour ta confiance.", "Stanza 118"],
    ["J'ai vu un homme mortellement blessé par les paroles d'une femme perfide ; une langue menteuse lui a causé la mort, sans qu'il y ait de crime véritable.", "Stanza 119"],
    ["Je te conseille, Loddfáfnir : si tu as un ami en qui tu as confiance, va le voir souvent ; car la brousse et les hautes herbes envahissent le chemin que l'on ne foule pas.", "Stanza 120"],
    ["Je te conseille, Loddfáfnir : attire à toi un homme de bien pour en faire ton confident, et apprends les chants qui guérissent.", "Stanza 121"],
    ["Je te conseille, Loddfáfnir : ne sois jamais le premier à rompre le lien avec ton ami ; le chagrin ronge le cœur quand on ne peut confier à personne tout son esprit.", "Stanza 122"],
    ["Je te conseille, Loddfáfnir : ne dispute jamais avec un sot insensé.", "Stanza 123"],
    ["Car d'un homme mauvais, tu n'obtiendras jamais de prix pour ton bien ; mais un homme de bien te rendra estimable par sa louange.", "Stanza 124"],
    ["C'est une parenté d'esprit quand on peut dire à un autre tout son cœur ; tout vaut mieux que la fausseté ; n'est pas un ami celui qui ne dit que des paroles plaisantes.", "Stanza 125"],
    ["Je te conseille, Loddfáfnir : ne dis pas même trois mots de dispute avec un homme pire que toi ; souvent le meilleur succombe quand le pire frappe avec sa langue.", "Stanza 126"],
    ["Je te conseille, Loddfáfnir : ne sois ni cordonnier ni fabricant de hampes, sauf pour toi-même ; si la chaussure est mal faite ou la hampe tordue, on appellera le malheur sur toi.", "Stanza 127"],
    ["Je te conseille, Loddfáfnir : là où tu vois le mal, dénonce-le comme tel, et ne donne aucun repos à tes ennemis.", "Stanza 128"],
    ["Je te conseille, Loddfáfnir : ne te réjouis jamais du mal, mais prends plaisir au bien.", "Stanza 129"],
    ["Je te conseille, Loddfáfnir : ne lève pas les yeux au combat (l'effroi saisit souvent les fils des hommes), de peur que les guerriers ne t'ensorcellent.", "Stanza 130"],
    ["Je te conseille, Loddfáfnir : si tu veux gagner l'amour d'une femme, fais de belles promesses et tiens-les fermement ; nul ne se lasse du bien s'il peut l'obtenir.", "Stanza 131"],
    ["Je te conseille, Loddfáfnir : je te demande d'être prudent, mais sans peur excessive ; sois surtout sur tes gardes avec la boisson et la femme d'un autre.", "Stanza 132"],
    ["Je te conseille, Loddfáfnir : ne traite jamais avec mépris ou dérision un invité ou un voyageur.", "Stanza 133"],
    ["Ceux qui restent assis chez eux savent rarement de quelle lignée sont ceux qui arrivent ; il n'est pas d'homme si bon qu'un défaut ne l'accompagne, ni si mauvais qu'il ne soit bon à rien.", "Stanza 134"],
    ["Je te conseille, Loddfáfnir : ne ris jamais d'un vieux sage ; ce que disent les anciens est souvent bon. Des paroles sensées sortent souvent d'une vieille peau ridée.", "Stanza 135"],
    ["Je te conseille, Loddfáfnir : n'aboie pas contre l'hôte et ne le chasse pas à ta porte ; sois bienveillant envers l'indigent.", "Stanza 136"],
    ["Puissante est la barre de la porte qui doit s'ouvrir à tous ; offre un anneau, ou l'on appellera sur tes membres toutes sortes de maux.", "Stanza 137"],
    ["Je sais que je pendis à l'arbre battu par les vents neuf nuits entières, blessé par la lance et offert à Odin, moi-même à moi-même sacrifié,", "Stanza 138"],
    ["sur cet arbre dont nul ne sait d'où proviennent les racines.", "Stanza 139"],
    ["On ne me donna ni pain ni corne à boire ; je regardai en bas, je ramassai les runes, en hurlant je les ramassai, et je tombai de là.", "Stanza 140"],
    ["Alors je commençai à germer et à savoir, à croître et à me porter bien ; d'une parole à une autre parole, la parole me menait, d'un acte à un autre acte, l'acte me menait.", "Stanza 141"],
    ["Tu trouveras les runes et les caractères gravés, des caractères très grands, des caractères très puissants, que le Maître-Poète a peints et que les Puissances ont créés, et que le Prince des dieux a gravés.", "Stanza 142"],
    ["Odin chez les Ases, Dáinn chez les Alfes, Dvalinn chez les nains, Ásviðr chez les géants, j'en ai moi-même gravé quelques-unes.", "Stanza 143"],
    ["Sais-tu comment il faut graver ? Sais-tu comment il faut interpréter ? Sais-tu comment il faut peindre ? Sais-tu comment il faut éprouver ? Sais-tu comment il faut prier ? Sais-tu comment il faut sacrifier ? Sais-tu comment il faut envoyer ? Sais-tu comment il faut détruire ?", "Stanza 144"],
    ["Mieux vaut ne pas prier que de trop sacrifier : un don attend toujours un retour ; mieux vaut ne pas envoyer que de trop détruire. Ainsi Odin grava avant l'origine des temps, là où il s'éleva quand il revint.", "Stanza 145"],
    ["Je connais des chants que les épouses des rois ne connaissent pas, ni les fils des hommes. Le premier s'appelle 'Secours' : il t'aidera dans les querelles, les soucis et les chagrins.", "Stanza 146"],
    ["J'en connais un deuxième, dont ont besoin ceux qui veulent être médecins.", "Stanza 147"],
    ["J'en connais un troisième : si j'ai grand besoin d'entraver mes ennemis, je peux émousser les lames de mes adversaires, ni leurs armes ni leurs ruses ne les aideront.", "Stanza 148"],
    ["J'en connais un quatrième : si des hommes mettent des liens sur mes membres, je chante de telle sorte que je peux m'en aller, les entraves sautent de mes pieds et les liens de mes mains.", "Stanza 149"],
    ["J'en connais un cinquième : si je vois une flèche voler dans la mêlée, elle ne volera pas si vite que je ne puisse l'arrêter, si seulement je l'aperçois du regard.", "Stanza 150"],
    ["J'en connais un sixième : si un homme veut me blesser par les racines d'un arbre mouillé, ce guerrier qui me menace sera dévoré par le malheur à ma place.", "Stanza 151"],
    ["J'en connais un septième : si je vois une haute salle brûler autour de mes compagnons de banc, le feu ne sera pas si vif que je ne puisse le calmer.", "Stanza 152"],
    ["J'en connais un huitième, qui est utile à tous : là où la haine s'élève entre les fils des rois, je peux l'apaiser rapidement.", "Stanza 153"],
    ["J'en connais un neuvième : si j'ai besoin de protéger mon bateau sur les flots, je calme le vent sur les vagues et j'endors la mer entière.", "Stanza 154"],
    ["J'en connais un dixième : si je vois des magiciennes chevaucher dans les airs, je fais en sorte qu'elles s'égarent et ne retrouvent plus leurs propres formes ni leurs propres esprits.", "Stanza 155"],
    ["J'en connais un onzième : si je dois mener de vieux amis au combat, je chante sous les boucliers, et ils s'avancent avec force, sains et saufs à la bataille, sains et saufs après la bataille, ils reviennent indemnes de partout.", "Stanza 156"],
    ["J'en connais un douzième : si je vois un pendu haut dans un arbre, je grave et je peins des runes de telle sorte que l'homme marche et me parle.", "Stanza 157"],
    ["J'en connais un treizième : si je verse de l'eau sur un jeune guerrier, il ne tombera pas, même s'il va au combat, il ne succombera pas sous les épées.", "Stanza 158"],
    ["J'en connais un quatorzième : si je dois énumérer les dieux devant les hommes, les Ases et les Alfes, je connais les distinctions de tous ; peu d'ignorants le peuvent.", "Stanza 159"],
    ["J'en connais un quinzième, celui que le nain Thjódreyrir chanta devant les portes de Dellingr : il chanta la force aux Ases, la gloire aux Alfes, et la sagesse à Odin.", "Stanza 160"],
    ["J'en connais un seizième : si je veux avoir tout l'esprit et le plaisir d'une femme avisée, je change les pensées de la belle et je tourne tout son cœur vers moi.", "Stanza 161"],
    ["J'en connais un dix-septième : de telle sorte que la jeune fille ne me quittera jamais volontiers.", "Stanza 162"],
    ["J'en connais un dix-huitième, que je n'enseignerai jamais à une jeune fille ni à la femme d'un homme — tout vaut mieux quand un seul le sait, c'est ainsi que se terminent les chants — sauf à celle qui m'entoure de ses bras ou qui est ma sœur.", "Stanza 163"],
    ["Maintenant les paroles du Très-Haut sont dites dans la salle du Très-Haut, très utiles aux fils des hommes, inutiles aux fils des géants. Salut à celui qui les a dites ! Salut à celui qui les connaît ! Que profite celui qui les a apprises ! Salut à ceux qui ont écouté !", "Stanza 164"]
];