export const nynorsk = [

    ["Alle dørganger, før ein går inn, skal ein skode og speide; for uvist er det kvar uvenner sit på benkene der inne.", "Stanza 1"],
    ["Heil deim som gjev! Ein gjest er komen; kvar skal han sitja? Bråhuga er den som på krakken skal freiste lukka.", "Stanza 2"],
    ["Eld treng den som inn er komen og er frosen på knea; mat og klede treng den mann som har reist over fjellet.", "Stanza 3"],
    ["Vatn treng den som til måltid kjem, handkle og venleg noding; godt ord skal han ha, om han kan få det, og tagnad medan andre talar.", "Stanza 4"],
    ["Vet treng den som vidt reiser; heime er alt lett. Til spott vert den som ingenting veit og sit hjå kloke folk.", "Stanza 5"],
    ["Med vetet sitt skal ein ikkje skryte, heller vera varsam i sinn; når ein klok og tagal gjest kjem til garden, skjer det sjeldan ulykke.", "Stanza 6"],
    ["Den varsame gjest som til måltid kjem, tier og lyder; med øyro høyrer han, med augo speidar han: slik røynar kvar vis mann.", "Stanza 7"],
    ["Sæl er den som får lovord og godvilje hjå seg sjølv; for det er tungt å eige det ein må finne i ein annan sitt bryst.", "Stanza 8"],
    ["Sæl er den som sjølv har lovord og vet så lenge han lever; for ille råd har ofte kome ut or ein annan sitt bryst.", "Stanza 9"],
    ["Betre bør ber ingen på vegen enn mykje mannevett; betre enn gull er det i framand land, det er den fattige si tilflukt.", "Stanza 10"],
    ["Betre bør ber ingen på vegen enn mykje mannevett; verre niste finst ikkje for reisa enn ofseleg drikk.", "Stanza 11"],
    ["Ikkje så godt som folk seier, er ølet for menneskeborna; for di meir han drikk, di mindre veit mannen kva som rår over sinnet.", "Stanza 12"],
    ["Gløymsle-hegren heiter han som over drikkelaget svever; han stel vetet frå mannen. Med fjørene til den fuglen vart eg bunden i Gunnlods gard.", "Stanza 13"],
    ["Drukken vart eg, eg vart ovdrukken hjå den kloke Fjalar; det er det beste med drikken, at kvar mann får vetet sitt atter.", "Stanza 14"],
    ["Tagal og tenksam skal ein kongsson vera og modig i kamp; glad og munter skal kvar mann vera, alt til døden han hentar.", "Stanza 15"],
    ["Den uvitige mann trur han skal leva evig om han skyr kampen; men alderdomen gjev han inga fred, om så spyta sparer han.", "Stanza 16"],
    ["Tåpen gapar når han kjem på vitjing, han mumlar eller stira; men med ein gong han får ein dram, vert det straks synt kva som bur i han.", "Stanza 17"],
    ["Berre den veit som vidt har reist og vandra mykje, kva for sinn som bur i kvar mann; han har sjølv vit.", "Stanza 18"],
    ["Hald ikkje på skåla, men drikk mjød med måte; tala det tarvelege eller teia. Ingen vil kalle deg ufolkeleg om du går tidleg til sengs.", "Stanza 19"],
    ["Den grådige mann, med mindre han styrer sin hug, et seg til døden; ofte fører magen den uvitige til spott når han er hjå kloke folk.", "Stanza 20"],
    ["Buskapen veit når han skal heim gå, og då går han ut or hagen; men den uvitige mann kjenner aldri målet for sin eigen mage.", "Stanza 21"],
    ["Ein ussel mann med dårlig sinnelag ler av alt han ser; han veit ikkje det han burde vite: at han ikkje er feilfri sjølv.", "Stanza 22"],
    ["Ein uvitig mann vakar alle netter og grunnar på alt moglege; då er han trøytt når morgonen kjem, og alt hans jammmer er som før.", "Stanza 23"],
    ["Ein uvitig mann trur at alle som lær mot han er vennene hans; han merkar ikkje, når han sit hjå kloke folk, at dei talar ille om han.", "Stanza 24"],
    ["Ein uvitig mann trur at alle som lær mot han er vennene hans; når han så kjem på tinget, finn han få som talar hans sak.", "Stanza 25"],
    ["Ein uvitig mann trur han veit alt når han sit i ein trygg krok; men han veit ikkje kva han skal svare når menn set han på prøve.", "Stanza 26"],
    ["Ein uvitig mann, når han kjem blant folk, gjer best i å teia; ingen veit at han ingenting kan, med mindre han talar for mykje. Den som inkje veit, merkar ikkje sjølv når han snakkar over seg.", "Stanza 27"],
    ["Klok tykkest den som spyrja kan og som svara veit; menneskeborna kan ikkje dylja det som gjeng føre seg blant folk.", "Stanza 28"],
    ["Mykje unyttig snakkar den som aldri teier, med ord utan meining; den snøgge tunga som ingen tøyle kjenner, skravlar ofte ulykke over seg sjølv.", "Stanza 29"],
    ["Ein skal ikkje gjera narr av andre, sjølv om dei kjem på vitjing; mang ein mann tykkest klok om han ikkje vert spurd og får sitja med turr hud på benken.", "Stanza 30"],
    ["Klok tykkest gjesten som spottar ein annan gjest og så stikk av; men den som ler ved måltidet, veit ikkje sikkert om han ler blant uvenner.", "Stanza 31"],
    ["Menn er ofte venlege mot kvarandre, men trettast likevel ved måltidet; denne spliden vil alltid finnast: at gjest kjempar mot gjest.", "Stanza 32"],
    ["Dugurd (frukost) skal ein ofte ta før ein går på vitjing, med mindre ein skal til ein venn; elles sit ein og glanar svolten, og kan lite ta del i praten.", "Stanza 33"],
    ["Ein stor omveg er det til ein dårlig venn, sjølv om huset hans ligg ved vegen; men til ein god venn fører strake stiar, sjølv om han bur langt borte.", "Stanza 34"],
    ["Gå skal ein, ein gjest skal ikkje vera alltid på same stad; det kjære vert kjipt om ein sit for lenge på ein annan sin benk.", "Stanza 35"],
    ["Eige heim er best, om han er liten; kvar mann er herre i sitt hus. To geiter og eit fletta tak er betre enn å tigge.", "Stanza 36"],
    ["Eige heim er best, om han er liten; kvar mann er herre i sitt hus. Hjartet blør på den som må be om mat til kvar mål.", "Stanza 37"],
    ["Frå våpna sine på marka skal ein ikkje vike ein fotbreidd; for ein veit aldri når ein på vegen kan trenge spydet sitt.", "Stanza 38"],
    ["Eg fann ingen mann så gåvmild eller gjestfri at han ikkje tok imot ei gåve, eller så raus med sitt gods at takk var han uvelkomen.", "Stanza 39"],
    ["Sitt gods, som ein har vunne, skal ein ikkje spare for mykje; ofte sparer ein til uvennen det som var tenkt for vennen: Mykje gjeng verre enn ein trur.", "Stanza 40"],
    ["Med våpen og klede skal venner gleda kvarandre, det er mest synleg på ein sjølv; gåve og gjengåve gjer venskapen varig, om det elles gjeng vel.", "Stanza 41"],
    ["Sin venn skal ein vera venn, og gjelda gåve med gåve; latter skal ein møte med latter, men svik med løgn.", "Stanza 42"],
    ["Sin venn skal ein vera venn, han sjølv og hans venn; men ingen manns uvenns venn skal ein noensinne vera.", "Stanza 43"],
    ["Veit du, om du har ein venn som du stolar godt på og du vil ha godt av han, skal du deila tankane dine med han og byte gåver, gå ofte og vitja han.", "Stanza 44"],
    ["Har du derimot ein annan som du stolar dårlig på, og du vil likevel ha godt av han, skal du tala fagre ord til han, men tenke svikaktig og gjelda løgn med løgn.", "Stanza 45"],
    ["Det er og slik med den du mistrur og som du aner svik hjå: Du skal le med han og tala mot din vilje; gåva skal gjelda likt.", "Stanza 46"],
    ["Ung var eg ein gong, eg vandra åleine og villfór på vegen; rik kjenst eg då eg møtte ein annan: Mann er manns gammen.", "Stanza 47"],
    ["Gåvmilde, tøffe menn lever best, dei kjenner sjeldan sorg; men den feige mannen fryktar alt, og den gnieraktige gruar seg alltid for gåver.", "Stanza 48"],
    ["Kleda mine gav eg på marka til to tremenn; kjemper tyktest dei vera då dei fekk kleda: Skamfull er den nakne mann.", "Stanza 49"],
    ["Furu døyr som står på ein naken stad, korkje bark eller nåler vernar henne; slik er mennesket som ingen elskar: Korleis skal han leva lenge?", "Stanza 50"],
    ["Heitare enn eld brenn blant falske venner kjærleiken i fem dagar; men han sloknar når den sjette kjem, og heile venskapen fell frå kvarandre.", "Stanza 51"],
    ["Ikkje berre store ting skal ein gje; ofte kjøper ein seg lovord med lite. Med eit halvt brød og ei skråstilt krukke vann eg meg ein kamerat.", "Stanza 52"],
    ["Små sandkorn, små sjøar, smått er menneske-vetet; ikkje alle menneske er like kloke, kvart mål er halvvegs.", "Stanza 53"],
    ["Middels klok bør kvar mann vera, aldri altfor vis; det livet er fagrast å leva for dei som veit vel kva dei veit.", "Stanza 54"],
    ["Middels klok bør kvar mann vera, aldri altfor vis; for ein vis manns hjarte er sjeldan glad om han er vorte altfor klok.", "Stanza 55"],
    ["Middels klok bør kvar mann vera, aldri altfor vis; sin lagnad bør ingen vite på førehand, då er sinnet mest fritt for sorg.", "Stanza 56"],
    ["Brann tennest av brann til han er utbrunnen, eld vert av eld vakt; mann vert av mann kjend gjennom tale, men av einsemd vert ein dum.", "Stanza 57"],
    ["Tidleg skal han stå opp som vil ha ein annan sitt eige eller liv; sjeldan fangar sovande ulv eit bytte, eller sovende mann sigeren.", "Stanza 58"],
    ["Tidleg skal han stå opp som har få arbeidsfolk, og sjølv gå til arbeidet; mykje vert forsømt av den som søv bort morgonen: Den flittige er halvvegs rik.", "Stanza 59"],
    ["Om tørt tre og om bjørkebark veit mannen å ta mål, og om veden som skal ligge på lager for veker og månader.", "Stanza 60"],
    ["Vaska og mett skal ein ri til tings, om ein enn ikkje er så godt kledd; sine sko og brøker skal ingen skjemmast over, og heller ikkje hesten, om ein ikkje har ein god ein.", "Stanza 61"],
    ["Snappar og snappar når han kjem til havet, gjer ørna ved den gamle flod; slik er mannen som kjem blant mange og har få som talar hans sak.", "Stanza 62"],
    ["Spørja og svara skal kvar klok mann som vil kallast vis; éin får vite det, men ikkje ein annan: Veit tre det, så veit heile verda det.", "Stanza 63"],
    ["Si makt skal kvar vis mann bruke med måte; for ein finn det ut når ein kjem blant dei tøffe, at ingen er den aller fremste.", "Stanza 64"],
    ["Ord som ein talar til ein annan, må ein ofte betale dyrt for.", "Stanza 65"],
    ["Altfor tidleg kom eg til mange stader, og for seint til sume; ølet var drukke eller ikkje brygga: Sjeldan kjem den uvelkomne til rette tid.", "Stanza 66"],
    ["Her og der hadde ein bede meg heim om eg ikkje hadde tregt mat ved måltidet, eller om to skinker hadde hengt hjå den trugne vennen der eg hadde ete éi.", "Stanza 67"],
    ["Eld er det beste for menneskeborna, og solas skin; si helse, om ein kan halde henne, og eit ulasteleg liv.", "Stanza 68"],
    ["Ein mann er ikkje heilt ulykkeleg om han er sjuk; sume er rike på søner, sume på frendar, sume på mykje godt, sume på velgjorde verk.", "Stanza 69"],
    ["Betre er det å leva enn ikkje å leva; den levande får alltid kua. Eg såg den rike sin eld brenne, men utanfor døra låg han død.", "Stanza 70"],
    ["Den halte kan ri, den handlause kan gjete, den døve kan kjempe og duge; å vera blind er betre enn å brennast: Ein død mann er til inga nytte.", "Stanza 71"],
    ["Ein son er betre, om han er seint fødd etter at faren er borte; sjeldan står bautasteinar ved vegen om dei ikkje er reiste av frende for frende.", "Stanza 72"],
    ["To er tunga sin morder; hovudet er hjartas fiende. I kvar neve ventar eg den skulte armen under kappen.", "Stanza 73"],
    ["På natta stoler den som stoler på sitt forråd; korte er skipsplankane, ustadig er haustnatta. Vêret skiftar ofte på fem dagar, og enda meir på ein månad.", "Stanza 74"],
    ["Den veit ingenting som ingenting veit: Mange vert tåper av rikdom. Ein mann er rik, ein annan fattig; klaga han ikkje for dårskap av den grunn.", "Stanza 75"],
    ["Døyr fe, døyr frendar, døyr sjølv det same; men ordet om deg døyr aldri om du deg eit godt eitt vann.", "Stanza 76"],
    ["Døyr fe, døyr frendar, døyr sjølv det same; eg veit eitt som aldri døyr: dom over kvar ein daud.", "Stanza 77"],
    ["Fulle kvear såg eg hjå Fitjungs søner, no ber dei tiggarkjeppen; slik er rikdom som eit augneblink: Han er den mest ustadige av venner.", "Stanza 78"],
    ["Den uvitige mann, om han får rikdom eller ei kvinnes kjærleik, då veks stoltheten, men ikkje vetet: Han gjeng stadig vidare i sitt hovmod.", "Stanza 79"],
    ["Det er no prøvd, det du spør runene om, dei som stammar frå gudar, som dei høge makter skapte og stortaleren måla: Han gjer best i å teia.", "Stanza 80"],
    ["Om kvelden skal ein dagen prise, kona når ho er brend, sverd når det er prøvd, møy når ho er gift, isen når ein er over, ølet når det er drukke.", "Stanza 81"],
    ["I vind skal ein ved felle, i godvêr ro på havet, i mørket tale med møy (mange er dagsins augo); skip er til å fare med, skjold til å verne, sverd til å hogge og møy til å kysse.", "Stanza 82"],
    ["Ved eld skal ein øl drikke, på isen gli, kjøpe mager hest og rustent sverd; hesten skal fôrast heime, men hunden hjå ein annan.", "Stanza 83"],
    ["Ei møy sine ord skal ingen tru, heller ikkje det ei kvinne talar; for på eit dreiande hjul vart hjarta deira skapt, og ustadigheit vart lagt i deira bryst.", "Stanza 84"],
    ["Bristande boge, brennande lue, gapande ulv, gispande kråke, gryntande svin, rotlaust tre, voksande bølgje, kokande kjele,", "Stanza 85"],
    ["flygande pil, fallande flod, isen av ei natt, ringlagt slange, brure-tale i senga eller knust sverd, leikande bjørn eller kongebarn,", "Stanza 86"],
    ["sjukt kalv, sjølvrådig træl, volva sitt smiger, den nyslagne på valen,", "Stanza 87"],
    ["halvbrend hus, snøgg hest (for éin fot gjer hesten unyttig): ingen vere så tillitsfull at han trur på alt dette.", "Stanza 88"],
    ["Sin brormordar, om ein møter han på vegen, brennande hus, rask hest (då er eit øk mest nyttig): kven er så tillitsfull at han trur på alt dette!", "Stanza 89"],
    ["Å tru på kjærleiken til kvinner som har svik i sinne, er som å ri med uskodde hestar på glatt is, med kåte toåringar, eller i hard storm med eit styrelaust skip, eller som ein halt som i tøvêr skal fange reinsdyr på fjellet.", "Stanza 90"],
    ["Ope vil eg no tale, for eg kjenner begge: ustadig er menns sinn mot kvinner; når me talar fagrast, tenker me falskast: det dårar sjølv den kloke.", "Stanza 91"],
    ["Fagert skal ein tale og gods by, om ein vil vinne ei kvinne sin kjærleik; prise den fagre møy sin kropp: den som smigrar, han vinner.", "Stanza 92"],
    ["For kjærleiken skal aldri ein mann laste ein annan; ofte fengar den kloke det som ikkje rører tåpen: den fagre skapnaden.", "Stanza 93"],
    ["Aldri skal ein mann laste ein annan for dårskap som råkar mange; verdas gang gjer ofte kloke menn til tåper gjennom begjæret si makt.", "Stanza 94"],
    ["Hugen åleine veit kva som bur nær hjarta, han åleine kjenner sitt sinn; inga plage er verre for ein klok mann enn å ikkje vera til freds med seg sjølv.", "Stanza 95"],
    ["Det røyna eg sjølv då eg sat i sivet og venta på mi kjære; liv og sjel var den kloke møy for meg, og likevel fekk eg henne ikkje.", "Stanza 96"],
    ["Billings møy fann eg på senga, solkvit, sovande; ein jarl si glede tyktest meg ingenting verd om eg ikkje fekk leve ved den kroppen.", "Stanza 97"],
    ["'Mot kvelden, Odin, skal du kome om du vil vinne møya; det er høgst usømeleg om ikkje me åleine deler ei slik lønn.'", "Stanza 98"],
    ["Eg vende tilbake og trudde meg elska, sikker i min villfaring; eg trudde eg hadde vunne all hennar gunst og glede.", "Stanza 99"],
    ["Då eg neste gong kom, var heile krigarflokken vaken; med brennande faklar og båre ved: slik var vegen sperra for meg.", "Stanza 100"],
    ["Og om morgonen, då eg kom atter, var sal-vakta sovna; ei bikkje fann eg på den gode senga til kvinna, bunden der i hennar stad.", "Stanza 101"],
    ["Mang ei fager møy, om ein kjenner henne nøyere, er falsk i sinn mot menn; det fekk eg røyne då eg den kloke møy lokka til elskhug: All slags skam la den listige på meg, og eg vann ikkje kvinna.", "Stanza 102"],
    ["Heime skal ein vera glad og mot gjester munter, sindig med seg sjølv; den som vil vera vis, må ha mykje kunnskap og ofte minnast det gode.", "Stanza 103"],
    ["Den gamle jotunen (Suttung) søkte eg opp, no er eg atter; lite vann eg der ved å teia. Med mange ord tala eg til min fordel i Suttung sine salar.", "Stanza 104"],
    ["Gunnlød gav meg på den gylne stol ein drikk av det dyre mjødet; dårlig lønn lét eg henne få etterpå for hennar ærlege sinn, for hennar tunge elskhug.", "Stanza 105"],
    ["Rati lét eg gnage veg og bore gjennom steinen; over og under meg var jotun-vegane: Slik sette eg hovudet mitt i pant.", "Stanza 106"],
    ["Den kjøpte skapnaden har eg nytta vel, den vise skortar sjeldan på råd; for Odrøre er no komen opp til gudane sin bustad.", "Stanza 107"],
    ["Tvilrådig er eg om eg hadde kome attende frå jotun-gardane, om eg ikkje hadde nytta Gunnlød, den gode kvinna, som la armen sin om meg.", "Stanza 108"],
    ["Dagen etter gjekk rimtussane for å spørja i Den Høge sin hall etter Den Høge; dei spurde om Bølverk var hjå gudane, eller om Suttung hadde drepe han.", "Stanza 109"],
    ["Ring-eid, seier dei, har Odin svore; kven skal ein no tru på? Suttung har han svike ved drikken og late Gunnlød sitja att i gråt.", "Stanza 110"],
    ["Tid er det å tala frå talarstolen ved Urds brunn; eg såg og tagde, eg såg og tenkte, eg lytta til mennene sin tale.", "Stanza 111"],
    ["Om runer høyrde eg dei råde, heller ikkje skorta det på råd; i Den Høge sin hall, i Den Høge sine salar, høyrde eg dei tale slik:", "Stanza 112"],
    ["Eg rådar deg, Loddfåvne, ta imot rådet; du har nytte om du tek det, heil om du følgjer det: Stå ikkje opp om natta, med mindre du skal speide eller gå ut i ærend.", "Stanza 113"],
    ["Eg rådar deg, Loddfåvne, ta imot rådet: Sov ikkje i armane til ei trollkunnig kvinne, så ho ikkje fangar deg med sine lemer.", "Stanza 114"],
    ["Ho gjer det slik at du ikkje bryr deg om tinget eller kongen sin tale; mat nektar du og menneska si glede, full av sorg gjeng du til svevns.", "Stanza 115"],
    ["Eg rådar deg, Loddfåvne, ta imot rådet: Lokk aldri ein annan mann si kone til løynleg elskhug.", "Stanza 116"],
    ["Eg rådar deg, Loddfåvne, ta imot rådet: Skal du reise over fjell eller fjord, utstyr deg vel med niste.", "Stanza 117"],
    ["Eg rådar deg, Loddfåvne, ta imot rådet: Lat aldri ein vond mann få vite di ulykke; for av ein vond mann får du aldri lønn for din gode tillit.", "Stanza 118"],
    ["Eg såg ein mann bli dødeleg såra av orda til ei vond kvinne; ei falsk tunge vart hans bane, og det utan sann klage.", "Stanza 119"],
    ["Eg rådar deg, Loddfåvne, ta imot rådet: Har du ein venn du stolar på, dra ofte og vitja han; for kratt veks og høgt gras på vegen som ingen gjeng.", "Stanza 120"],
    ["Eg rådar deg, Loddfåvne, ta imot rådet: Ein god mann skal du vinne deg til glede, og lær deg lækjemiddel å kjenne.", "Stanza 121"],
    ["Eg rådar deg, Loddfåvne, ta imot rådet: Ver aldri den fyrste til å bryte bandet med vennen din; sorg et hjartet om du ikkje kan seie din heile hug til nokon.", "Stanza 122"],
    ["Eg rådar deg, Loddfåvne, ta imot rådet: Ord skal du aldri skifte med ein uvettug tåpe.", "Stanza 123"],
    ["For av ein vond mann vil du aldri få godt som lønn; men ein god mann vil gjere deg verdifull ved sin ros.", "Stanza 124"],
    ["Delt sinnelag er det når ein seier alt sitt sinn til ein annan; alt er betre enn å vera falsk: Ingen venn er den som berre talar etter munnen.", "Stanza 125"],
    ["Eg rådar deg, Loddfåvne, ta imot rådet: Sjølv med tre ord skal du ikkje krangle med ein ringare mann; ofte fell den betre for den ringare når denne dreg sverdet.", "Stanza 126"],
    ["Eg rådar deg, Loddfåvne, ta imot rådet: Ver ikkje skomakar eller skaftmakar utan for deg sjølv; for om skoen sit dårlig eller skaftet er skeivt, vil dei ynskje deg alt vondt.", "Stanza 127"],
    ["Eg rådar deg, Loddfåvne, ta imot rådet: Der du ser urett, nemn det som urett, og gjev uvennene dine ingen fred.", "Stanza 128"],
    ["Eg rådar deg, Loddfåvne, ta imot rådet: Gled deg aldri over det vonde, men lat deg hugtake av det gode.", "Stanza 129"],
    ["Eg rådar deg, Loddfåvne, ta imot rådet: Sjå ikkje opp i kamp (for menneskeborna vert som vanvitige), så menn ikkje forheksar deg.", "Stanza 130"],
    ["Eg rådar deg, Loddfåvne, ta imot rådet: Vil du vinne ei kvinne sin elskhug, hald fast på lofte dine; ingen vert trøytt av det gode om han får det.", "Stanza 131"],
    ["Eg rådar deg, Loddfåvne, ta imot rådet: Ver varsam, men ikkje for redd; ver mest varsam med drikken og med ein annan mann si kone.", "Stanza 132"],
    ["Eg rådar deg, Loddfåvne, ta imot rådet: Spott aldri ein gjest eller ein vandrar, og le ikkje av han.", "Stanza 133"],
    ["Eg rådar deg, Loddfåvne, ta imot rådet: Le aldri av ein gråhåra talar; ofte er det godt, det dei gamle seier. Or rynka hud kjem ofte kloke ord.", "Stanza 134"],
    ["Ofte hengjer dei mellom hudene, dinglar under skinnene og slengjer mellom dei visne.", "Stanza 135"],
    ["Eg rådar deg, Loddfåvne, ta imot rådet: Skjell ikkje ut gjesten og jag han ikkje på porten; ver god mot dei arme.", "Stanza 136"],
    ["Stark er den dørstolpen som skal opne seg for alle; gjev ein ring, eller dei vil ynskje deg kvar ulykke.", "Stanza 137"],
    ["Eg veit at eg hekk på det vindkalde treet i ni heile netter, sårka med spjut og gjeven til Odin, eg sjølv til meg sjølv.", "Stanza 138"],
    ["På det treet som ingen veit kvar røtene rinn av.", "Stanza 139"],
    ["Dei rette meg korkje brød eller drikkehorn; eg spidda ned, eg tok opp runene, skrikande tok eg deim, og falt så ned derifrå.", "Stanza 140"],
    ["Då tok eg til å gro og vera vis, å vekse og trivast vel; ord fylgde ord til nytt ord, verk fylgde verk til nytt verk.", "Stanza 141"],
    ["Runer skal du finne og lesbare stavar, storstavar mange, maktstavar mange, som stortalaren måla og dei høge makter skapte og gudane sin Hroptr rista.", "Stanza 142"],
    ["Odin hjå aser, for alvar Daínn, Dvalin for dvergar, Allsvinn for jotnar; eg sjølv rista nokre for menneskeborna.", "Stanza 143"],
    ["Veit du korleis ein skal riste? Veit du korleis ein skal råde? Veit du korleis ein skal måle? Veit du korleis ein skal prøve? Veit du korleis ein skal bede? Veit du korleis ein skal ofre? Veit du korleis ein skal sende? Veit du korleis ein skal slette?", "Stanza 144"],
    ["Betre er inkje bede enn for mykje ofra, ei gåve ser alltid etter gjengåve; betre er inkje sendt enn for mykje sletta. Slik rista Thundr før folka si soge, der han steig opp då han kom atter.", "Stanza 145"],
    ["Dei songane kjenner eg som inga dronning kan og ingen manns son. 'Hjelp' heiter den fyrste, for den hjelper deg i strid og sorg og i alle kvalar.", "Stanza 146"],
    ["Ein annan kjenner eg som menneskeborna treng, dei som vil leva som lækjarar: å lækje sår og lindre sjukdom.", "Stanza 147"],
    ["Ein tredje kjenner eg: om eg har stor naud for å binde mine uvenner, så sløvar eg eggen på motstandarane sine våpen; korkje våpen eller svik hjelper deim då.", "Stanza 148"],
    ["Ein fjerde kjenner eg: om menn legg band på mine lemer, så syng eg slik at eg kan gå; lenka spring frå føtene og bandet frå hendene.", "Stanza 149"],
    ["Ein femte kjenner eg: om eg ser ei pil fljuge som vil skade i hæren, så flyg ho ikkje så snøgt at eg ikkje stansar henne om eg får sjå henne med augo.", "Stanza 150"],
    ["Ein sjette kjenner eg: om ein mann vil skade meg med røtene til eit framand tre, så råkar ulykka han sjølv og ikkje meg.", "Stanza 151"],
    ["Ein sjuande kjenner eg: om eg ser salen brenne kring mine benkefelagar, så brenn han ikkje så heitt at eg ikkje bergar han; den galdren kan eg syngje.", "Stanza 152"],
    ["Ein åttande kjenner eg, som er nyttig for alle å lære: der hat veks mellom fyrstesøner, der kan eg snøgt døyve det.", "Stanza 153"],
    ["Ein niande kjenner eg: om naud tvingar meg til å berge mitt skip på havet, så stiller eg vinden på bølgjene og lullar heile havet i svevn.", "Stanza 154"],
    ["Ein tiande kjenner eg: om eg ser gandreid-kvinner leike i lufta, så gjer eg slik at dei forvillar seg frå sine eigne huder og sin eigen hug.", "Stanza 155"],
    ["Ein ellevte kjenner eg: om eg skal leie gamle venner til strid, så syng eg under skjolda, og dei dreg med makt; heile til strid, heile frå strid, dei kjem heile overalt.", "Stanza 156"],
    ["Eit tolvte kjenner eg: om eg ser ein hengd mann i eit tre, så ristar og målar eg runer slik at mannen går og talar med meg.", "Stanza 157"],
    ["Eit trettande kjenner eg: om eg ausar vatn over ein ung krigar, så vil han ikkje falle sjølv om han dreg i kamp; ingen sverd hovlar han.", "Stanza 158"],
    ["Eit fjortande kjenner eg: om eg skal telje opp gudar for folk, aser og alvar, så kjenner eg alle vel; sjeldan kjenner ein uvittug deim slik.", "Stanza 159"],
    ["Eit femtende kjenner eg, som dvergen Tjodreir sang framfor Dellings dører: han song kraft til aser, ære til alvar og vet til Hroptr.", "Stanza 160"],
    ["Et sekstande kjenner eg: om eg vil ha ei klok møy sin elskhug og lyst, så vender eg sinnet til den kvitarma kvinna og snur heile hjarta hennar.", "Stanza 161"],
    ["Et syttande kjenner eg, slik at den unge møy aldri vil skilje seg frå meg; desse songane, Loddfåvne, vil du lengre sakne.", "Stanza 162"],
    ["Et attande kjenner eg, som eg aldri lærer til møy eller manns kone, utan til den eine som min arm famnar eller som er mi syster; alt er betre når berre éin veit det.", "Stanza 163"],
    ["No er Den Høge sin tale talt i Den Høge sin hall, nyttig for menneskeborna, unyttig for jotunsønene. Heil den som tala! Heil den som kjenner! Nytte har den som lærte! Heil deim som lytta!", "Stanza 164"]
];