export const spanish = [
    ["Todas las puertas, antes de avanzar, deben ser observadas, deben ser vigiladas; pues es difícil saber dónde los enemigos se sientan en la sala.", "Stanza 1"],
    ["¡Salud a los anfitriones! Un invitado ha llegado, ¿dónde se sentará? Muy apurado está quien, junto al fuego, debe probar su suerte.", "Stanza 2"],
    ["Fuego necesita quien acaba de llegar y tiene frías las rodillas; comida y ropa necesita el hombre que ha viajado por las montañas.", "Stanza 3"],
    ["Agua necesita quien viene a la comida, toallas y una acogida amable; si quiere obtener una buena recepción, debe hablar y ser respondido.", "Stanza 4"],
    ["Juicio necesita quien viaja lejos, en casa todo es fácil; pero es el hazmerreír quien nada sabe y se sienta junto a los sabios.", "Stanza 5"],
    ["De su sabiduría nadie debe jactarse, sino ser cauteloso de mente; cuando un invitado llega a su casa, que calle y esté atento; pues un amigo más fiel ningún hombre encontrará que el buen juicio.", "Stanza 6"],
    ["El invitado cauteloso que viene a la comida calla y escucha; con sus oídos oye, con sus ojos mira, y así el hombre sabio vigila.", "Stanza 7"],
    ["Feliz es aquel que por sí mismo gana el favor y la estima de los hombres; pues difícil es encontrar en el pecho de otro el pensamiento propio.", "Stanza 8"],
    ["Feliz es aquel que en vida posee estima y sabiduría también; pues a menudo el hombre ha recibido malos consejos del pecho de otro.", "Stanza 9"],
    ["Mejor carga no puede llevar un hombre en el camino que mucho juicio; es mejor que la riqueza en tierra extraña, y un refugio en la necesidad.", "Stanza 10"],
    ["Mejor carga no puede llevar un hombre en el camino que mucho juicio; pero peor provisión no hay para el camino que el exceso de bebida.", "Stanza 11"],
    ["La cerveza no es tan buena como dicen para los hijos de los hombres; pues cuanto más bebe el hombre, menos sabe cómo guardar su mente.", "Stanza 12"],
    ["El garza del olvido vuela sobre los banquetes y roba la mente de los hombres; con las plumas de esa ave fui encadenado una vez en la corte de Gunnlöd.", "Stanza 13"],
    ["Ebrio estuve, estuve muy ebrio, en casa del sabio Fjalar; pues lo mejor de la bebida es que cada hombre recupere su mente de nuevo.", "Stanza 14"],
    ["Silencioso y reflexivo debe ser el hijo de un príncipe, y valiente en la batalla; alegre y feliz sea cada hombre hasta que encuentre la muerte.", "Stanza 15"],
    ["El cobarde cree que vivirá para siempre si se mantiene a salvo de la lucha; pero la vejez no le dará paz al final, aunque las lanzas lo hayan perdonado.", "Stanza 16"],
    ["El necio abre la boca cuando viene a un banquete, balbucea o se queda mirando; pero si toma un trago, al momento se muestra su mente ante todos.", "Stanza 17"],
    ["Solo sabe aquel que viaja lejos y ha recorrido muchas tierras, qué mente hay en cada hombre que encuentra, si él mismo tiene juicio.", "Stanza 18"],
    ["No rehuyas la hidromiel, pero bebe con medida; di lo que sea necesario o calla; ningún hombre te reprochará falta de modales si te vas temprano a dormir.", "Stanza 19"],
    ["El hombre glotón, si su mente no conoce, come para su propia desgracia; y el vientre de un necio a menudo le trae desprecio cuando está entre sabios.", "Stanza 20"],
    ["Los rebaños saben bien cuándo deben irse a casa y dejar los pastos; pero el hombre necio nunca conoce la medida de su propio vientre.", "Stanza 21"],
    ["El hombre miserable y de mente malvada se burla de todo; una cosa no sabe, que debería saber: que él mismo no está libre de faltas.", "Stanza 22"],
    ["El hombre sin juicio permanece despierto toda la noche y se preocupa por todo; está agotado cuando llega la mañana, y todo sigue tan mal como antes.", "Stanza 23"],
    ["El hombre sin juicio cree que todos los que le sonríen son sus amigos; no percibe, cuando se sienta con los sabios, que hablan mal de él.", "Stanza 24"],
    ["El hombre sin juicio cree que todos los que le sonríen son sus amigos; pero cuando llega a la Asamblea (el Thing), descubre que tiene pocos que hablen por él.", "Stanza 25"],
    ["El hombre sin juicio cree que lo sabe todo si está sentado seguro en un rincón; pero no sabe qué responder cuando los hombres ponen a prueba su ingenio.", "Stanza 26"],
    ["El hombre sin juicio, cuando está entre hombres, es mejor que calle; nadie sabrá que nada sabe a menos que hable demasiado; y quien nada sabe, no sabe cuándo habla de más.", "Stanza 27"],
    ["Sabio parece quien sabe preguntar y también cómo responder; los hijos de los hombres nunca pueden ocultar lo que la gente dice de los hombres.", "Stanza 28"],
    ["Dice muchas palabras inútiles quien nunca calla; una lengua veloz, a menos que sea embridada, a menudo se trae problemas a sí misma.", "Stanza 29"],
    ["Un hombre no debe burlarse de otro que viene a su casa; muchos parecen sabios si no se les pregunta, y se sientan con la piel seca en su rincón.", "Stanza 30"],
    ["Sabio parece el invitado que huye del invitado que se mofa de él; pero quien se ríe de otro durante la comida no sabe si se ríe con sus enemigos.", "Stanza 31"],
    ["Muchos son los hombres de mente amistosa que se burlan unos de otros en la mesa; siempre habrá discordia entre los hombres, y el invitado reñirá con el invitado.", "Stanza 32"],
    ["Un hombre debe comer su comida temprano, a menos que vaya a casa de un amigo; de lo contrario, se sienta y dormita como si tuviera hambre, y tiene poca fuerza para preguntar.", "Stanza 33"],
    ["Largo es el camino hacia un falso amigo, aunque su casa esté en la ruta; pero hacia un amigo fiel el camino es corto, aunque haya viajado lejos.", "Stanza 34"],
    ["Uno debe partir, no ser un invitado para siempre en un solo lugar; lo amado se vuelve tedioso si uno se queda mucho tiempo en casa ajena.", "Stanza 35"],
    ["Tu propia casa es mejor, aunque sea pequeña; cada uno es amo en su hogar; aunque solo tengas dos cabras y una choza techada con corteza, es mejor que mendigar.", "Stanza 36"],
    ["Tu propia casa es mejor, aunque sea pequeña; cada uno es amo en su hogar; el corazón le sangra a quien debe mendigar su comida en cada comida.", "Stanza 37"],
    ["Un hombre nunca debe alejarse un paso de sus armas en el campo; pues no sabe cuándo, en el camino, puede tener necesidad de su lanza.", "Stanza 38"],
    ["Nunca he encontrado a un hombre tan generoso ni tan espléndido con su comida que no aceptara lo que se le ofreciera, ni a nadie tan desprendido con su dinero que le disgustara un regalo si lo recibía.", "Stanza 39"],
    ["De la riqueza que un hombre ha ganado, no debe padecer necesidad; a menudo se guarda para un enemigo lo que se destinaba a un amigo; muchas cosas salen peor de lo esperado.", "Stanza 40"],
    ["Con armas y vestidos deben los amigos alegrarse, pues eso se nota en uno mismo; los que dan y los que corresponden son amigos por más tiempo, si las cosas van bien.", "Stanza 41"],
    ["Para su amigo un hombre debe ser amigo, y devolver regalo por regalo; a la risa se debe responder con risa, y a la falsedad con mentira.", "Stanza 42"],
    ["Para su amigo un hombre debe ser amigo, para él y para el amigo de su amigo; pero ningún hombre debe ser amigo del amigo de su enemigo.", "Stanza 43"],
    ["Si tienes un amigo en quien confías plenamente y del que quieres obtener bien, debes mezclar tu mente con la suya, intercambiar regalos y visitarlo a menudo.", "Stanza 44"],
    ["Si tienes a otro en quien confías poco, pero del que quieres obtener bien, debes hablarle con dulzura pero pensar con falsedad, y devolver engaño por mentira.", "Stanza 45"],
    ["Aún más sobre aquel en quien poco confías y de cuya mente sospechas: debes reír con él y hablar contra tu pensamiento; los regalos deben ser como el dador.", "Stanza 46"],
    ["Joven fui una vez, caminaba solo, y entonces perdí mi camino; me sentí rico cuando encontré a otro, pues el hombre es la alegría del hombre.", "Stanza 47"],
    ["Los nobles y valientes viven mejor y rara vez sienten tristeza; pero el cobarde teme a todo, y el avaro siempre se lamenta por los regalos.", "Stanza 48"],
    ["Mis ropas di en el campo a dos hombres de madera; se sintieron nobles cuando tuvieron vestidos, pues el hombre desnudo se avergüenza.", "Stanza 49"],
    ["Se seca el pino que está en la aldea, no lo protege la corteza ni las agujas; así es el hombre a quien nadie ama, ¿por qué habría de vivir mucho tiempo?", "Stanza 50"],
    ["Más ardiente que el fuego por cinco días arde la amistad entre falsos amigos; pero se apaga cuando llega el sexto, y toda la amistad se arruina.", "Stanza 51"],
    ["No se debe dar solo cosas grandes, a menudo con poco se gana el elogio; con medio pan y una copa inclinada me gané un camarada.", "Stanza 52"],
    ["Pequeña la arena, pequeños los mares, pequeñas son las mentes de los hombres; pues no todos los hombres son igual de sabios, cada hombre es medio-en-todas-partes.", "Stanza 53"],
    ["Una medida de sabiduría debe tener cada hombre, pero nunca demasiada; pues la vida es más bella para aquellos que saben muchas cosas bien.", "Stanza 54"],
    ["Una medida de sabiduría debe tener cada hombre, pero nunca demasiada; pues el corazón del sabio rara vez es alegre, si es mucha la sabiduría que posee.", "Stanza 55"],
    ["Una medida de sabiduría debe tener cada hombre, pero nunca demasiada; que nadie conozca su destino de antemano, pues así su mente está más libre de preocupaciones.", "Stanza 56"],
    ["Una brasa arde de otra hasta que se consume, el fuego se aviva con el fuego; el hombre se conoce por su palabra, y el necio por su silencio.", "Stanza 57"],
    ["Temprano debe levantarse quien busca la vida o la riqueza de otro; rara vez el lobo que duerme consigue la carne, ni el hombre que duerme la victoria.", "Stanza 58"],
    ["Temprano debe levantarse quien tiene pocos trabajadores y atender él mismo su trabajo; mucho retrasa a quien duerme por la mañana, pues la mitad de la riqueza depende de la prisa.", "Stanza 59"],
    ["De los leños secos y de la corteza para el techo, un hombre conoce bien la medida, y de la madera que puede durar por un tiempo y por muchos meses.", "Stanza 60"],
    ["Limpio y saciado debe el hombre cabalgar a la Asamblea, aunque su ropa no sea la mejor; de sus zapatos y calzones que nadie se avergüence, ni de su caballo, aunque no sea bueno.", "Stanza 61"],
    ["El águila se estira y el águila se encorva cuando llega al mar; así es el hombre que llega entre muchos y tiene pocos que hablen por él.", "Stanza 62"],
    ["Preguntar y responder debe buscar todo hombre sabio que quiera ser llamado inteligente; que uno lo sepa, pero nunca un segundo; el mundo lo sabe si tres lo saben.", "Stanza 63"],
    ["Su poder debe todo hombre sabio usar de manera cautelosa; pues descubre, cuando está entre los valientes, que nadie es el más audaz de todos.", "Stanza 64"],
    ["Por las palabras que un hombre dice a otro, a menudo paga un precio.", "Stanza 65"],
    ["Mucho antes de tiempo llegué a muchos lugares, y demasiado tarde a otros; la cerveza estaba bebida, o aún no se había fermentado; el invitado odiado rara vez llega en el momento justo.", "Stanza 66"],
    ["Aquí y allá me habrían invitado a casa si no hubiera necesitado comida a la hora de comer, o si dos jamones hubieran colgado en casa de mi amigo fiel, donde solo me había comido uno.", "Stanza 67"],
    ["El fuego es lo mejor para los hijos de los hombres, y la vista del sol; su salud, si el hombre puede conservarla, y vivir una vida sin vicios.", "Stanza 68"],
    ["Ningún hombre es del todo miserable, aunque su salud sea mala; uno es bendecido con hijos, otro con parientes, otro con riqueza, otro con buenas obras.", "Stanza 69"],
    ["Es mejor estar vivo que estar muerto, pues el hombre vivo consigue la vaca; vi el fuego arder para el hombre rico, pero afuera yacía muerto ante la puerta.", "Stanza 70"],
    ["El cojo puede montar a caballo, el manco puede guiar un rebaño, el sordo puede luchar y ser útil; mejor es ser ciego que ser quemado; un cadáver no sirve para nada a nadie.", "Stanza 71"],
    ["Un hijo es mejor, aunque nazca tarde, después de que su padre haya partido; rara vez las piedras conmemorativas se alzan junto al camino a menos que las levante un pariente para su pariente.", "Stanza 72"],
    ["Dos son un ejército, la lengua es la perdición de la cabeza; bajo cada capa espero encontrar una mano.", "Stanza 73"],
    ["La noche es bienvenida por quien confía en sus provisiones, cortos son los remos del barco; inconstante es la noche de otoño; el clima cambia mucho en cinco días, y más en un mes.", "Stanza 74"],
    ["No sabe, quien nada sabe, que a muchos la riqueza los hace necios; un hombre es rico, otro es pobre, que nadie culpe a otro por su suerte.", "Stanza 75"],
    ["Muere el ganado, mueren los parientes, y uno mismo también muere; pero el buen nombre nunca muere para quien se lo ha ganado.", "Stanza 76"],
    ["Muere el ganado, mueren los parientes, y uno mismo también muere; pero yo sé una cosa que nunca muere: el juicio sobre cada muerto.", "Stanza 77"],
    ["Apriscos llenos vi para los hijos de Fitjung, ahora llevan el bastón de mendigo; la riqueza es como el parpadeo de un ojo, el más inconstante de los amigos.", "Stanza 78"],
    ["El hombre sin juicio, si gana para sí riqueza o el amor de una mujer, su orgullo aumenta, pero su sentido nunca; se hunde más y más en su necedad.", "Stanza 79"],
    ["Entonces se comprueba, cuando preguntas a las runas, aquellas nacidas de los dioses, las que los altos poderes hicieron y el Gran Orador pintó: que lo mejor es que él calle.", "Stanza 80"],
    ["Al atardecer debe alabarse el día, a la mujer cuando ha sido incinerada, a la espada cuando ha sido probada, a la doncella cuando se ha casado, al hielo cuando se ha cruzado, a la cerveza cuando se ha bebido.", "Stanza 81"],
    ["Con viento se debe talar madera, con brisa remar mar adentro, en la oscuridad hablar con una doncella (muchos son los ojos del día); para la velocidad se usa el barco, para la protección el escudo, para los golpes la espada y para los besos la doncella.", "Stanza 82"],
    ["Junto al fuego se debe beber la cerveza, sobre el hielo deslizarse; un caballo flaco se debe comprar, y una espada manchada; en casa se debe engordar al caballo, y al perro en la granja.", "Stanza 83"],
    ["En las palabras de una doncella ningún hombre debe confiar, ni en lo que diga una mujer; pues en una rueda giratoria fueron forjados sus corazones, y la inconstancia puesta en sus pechos.", "Stanza 84"],
    ["Arco que se quiebra, llama que arde, lobo que bosteza, cuervo que grazna, jabalí que gruñe, árbol sin raíces, ola que crece, caldero que hierve,", "Stanza 85"],
    ["Flecha que vuela, ola que cae, hielo de una sola noche, serpiente enroscada, charla de cama de una mujer o espada rota, juego de un oso o hijo de un rey,", "Stanza 86"],
    ["Ternero enfermo, esclavo voluntarioso, palabras lisonjeras de una bruja, enemigo recién abatido.", "Stanza 87"],
    ["En campo sembrado temprano nadie confíe, ni demasiado pronto en un hijo; el clima rige el campo y el juicio al hijo, y cada uno de ellos es inconstante.", "Stanza 88"],
    ["El asesino de un hermano, aunque se encuentre en el camino, una casa medio quemada, un caballo demasiado veloz (pues el caballo es inútil si una pata se rompe); que ningún hombre sea tan confiado como para confiar en todo esto.", "Stanza 89"],
    ["Así es el amor de las mujeres, que piensan con engaño: como guiar un caballo sin herraduras sobre hielo resbaladizo, un potro de dos años alegre y mal domado, o dirigir un barco sin timón en un vendaval, o que un cojo intente atrapar un reno en una ladera en deshielo.", "Stanza 90"],
    ["Claramente hablo, pues ambos conozco: inconstante es la mente del hombre hacia la mujer; cuando más dulce hablamos, más falso pensamos; eso atrapa hasta la mente más sabia.", "Stanza 91"],
    ["Dulce debe hablar y riqueza debe ofrecer quien desee ganar el amor de una mujer; debe alabar la belleza de la brillante doncella; gana quien corteja.", "Stanza 92"],
    ["Por su amor ningún hombre debe culpar nunca a otro; a menudo el sabio queda atrapado donde el necio no, por la belleza de un rostro.", "Stanza 93"],
    ["Por una falta propia ningún hombre culpe a otro, por aquello que a muchos sucede; la poderosa pasión vuelve a los hijos de los hombres de sabios a necios.", "Stanza 94"],
    ["Solo la mente sabe lo que habita cerca del corazón, cada hombre es su propio juez; no hay peor enfermedad para un sabio que no estar satisfecho con nada.", "Stanza 95"],
    ["Esto descubrí cuando me senté entre las cañas y esperaba a mi amor; cuerpo y alma era esa dulce doncella para mí, y sin embargo no la conseguí.", "Stanza 96"],
    ["A la hija de Billing encontré en su cama, brillante como el sol, durmiendo; ningún placer de un jarl me pareció igual a ese: vivir con esa forma encantadora.", "Stanza 97"],
    ["'Cerca del anochecer, Odín, vendrás si quieres cortejar a la doncella; sería del todo indecoroso que otros supieran de tal pecado.'", "Stanza 98"],
    ["Me alejé, y creí amar con la esperanza de un hombre sabio; pensé que tendría su corazón y toda su alegría.", "Stanza 99"],
    ["Así regresé después, cuando todos los guerreros estaban despiertos y vigilando; con luces encendidas y portando antorchas, un camino de desgracia estaba marcado para mí.", "Stanza 100"],
    ["Y cerca de la mañana, cuando regresé, todos los guerreros dormían; pero encontré un perro de aquella noble mujer atado sobre su cama.", "Stanza 101"],
    ["Muchas doncellas, si se las conoce bien, resultan inconstantes con los hombres; eso lo aprendí cuando intenté seducir a aquella astuta mujer; ella me cubrió de insultos y no obtuve nada de la doncella.", "Stanza 102"],
    ["En casa debe el hombre estar alegre y ser cordial con los huéspedes, pero prudente consigo mismo; con buena memoria y facilidad de palabra si quiere pasar por sabio, debe hablar a menudo de lo bueno; un 'fimbul-fambi' es llamado quien poco tiene que decir, pues tal es la marca del ignorante.", "Stanza 103"],
    ["Visité al antiguo gigante, y ya estoy de vuelta, poco conseguí allí callando; con muchas palabras hablé para mi provecho en las salas de Suttung.", "Stanza 104"],
    ["Gunnlöð me dio, en su silla de oro, un trago de la preciosa hidromiel; pero mal pago le di después a su noble corazón y a su profundo amor.", "Stanza 105"],
    ["Con el pico de Rati me abrí espacio y roí a través de la roca; por encima y por debajo estaban los caminos de los gigantes, así que puse en juego mi cabeza.", "Stanza 106"],
    ["Del premio bien ganado he disfrutado mucho, pues al sabio poco le falta; ahora la hidromiel Óðrerir ha subido a la tierra de los hombres.", "Stanza 107"],
    ["Dudo que hoy hubiera regresado de las moradas de los gigantes si no me hubiera valido de Gunnlöð, esa buena mujer, a quien estreché en mis brazos.", "Stanza 108"],
    ["Al día siguiente los gigantes de la escarcha fueron a la sala del Altísimo para pedir consejo; preguntaron por Bölverk, si estaba con los dioses o si Suttung lo había matado.", "Stanza 109"],
    ["Un juramento sobre el anillo, creo, hizo Odín; ¿quién puede confiar en su palabra? Engañó a Suttung para quitarle la hidromiel y dejó a Gunnlöð llorando.", "Stanza 110"],
    ["Es hora de hablar desde la silla del orador junto a la fuente de Urd; vi y callé, vi y medité, escuché las palabras de los hombres; oí hablar de runas y de secretos consejos en la sala del Altísimo, y esto es lo que dijeron:", "Stanza 111"],
    ["Te aconsejo, Loddfáfnir, que escuches mi consejo: te será útil si lo sigues, te traerá bien si lo aprendes: no te levantes por la noche, a menos que vayas a vigilar o busques un lugar afuera.", "Stanza 112"],
    ["Te aconsejo, Loddfáfnir, que escuches mi consejo: te será útil si lo sigues, te traerá bien si lo aprendes: no caigas en los lazos de una mujer experta en magia, de modo que te estreche en sus brazos.", "Stanza 113"],
    ["Ella hará que no te importe la Asamblea ni lo que diga el rey; aborrecerás la comida y los placeres humanos, y te irás a dormir lleno de penas.", "Stanza 114"],
    ["Te aconsejo, Loddfáfnir, que escuches mi consejo: te será útil si lo sigues, te traerá bien si lo aprendes: nunca seduzcas a la mujer de otro para que sea tu amante secreta.", "Stanza 115"],
    ["Te aconsejo, Loddfáfnir, que escuches mi consejo: te será útil si lo sigues, te traerá bien si lo aprendes: si por la montaña o por el fiordo tienes que viajar, asegúrate de llevar buena comida.", "Stanza 116"],
    ["Te aconsejo, Loddfáfnir, que escuches mi consejo: te será útil si lo sigues, te traerá bien si lo aprendes: nunca dejes que un hombre malvado conozca tu desgracia; pues de un mal hombre nunca recibirás recompensa por tu buena voluntad.", "Stanza 117"],
    ["Vi a un hombre herido por las palabras de un hombre malvado; una lengua falsa le causó la muerte, y ni siquiera por una causa verdadera.", "Stanza 118"],
    ["Te aconsejo, Loddfáfnir, que escuches mi consejo: te será útil si lo sigues, te traerá bien si lo aprendes: si tienes un amigo en quien confías mucho, ve a verlo a menudo; pues la maleza y la hierba alta crecen en el camino que nadie pisa.", "Stanza 119"],
    ["Te aconsejo, Loddfáfnir, que escuches mi consejo: te será útil si lo sigues, te traerá bien si lo aprendes: atrae hacia ti a un hombre bueno por su amor, y aprende los conjuros de vida mientras vivas.", "Stanza 120"],
    ["Te aconsejo, Loddfáfnir, que escuches mi consejo: te será útil si lo sigues, te traerá bien si lo aprendes: nunca seas el primero en romper el vínculo con tu amigo; el dolor devora el corazón si no puedes contarle a alguien toda tu mente.", "Stanza 121"],
    ["Te aconsejo, Loddfáfnir, que escuches mi consejo: te será útil si lo sigues, te traerá bien si lo aprendes: nunca intercambies palabras con un necio ignorante.", "Stanza 122"],
    ["Pues de un hombre malvado nunca recibirás recompensa por tu buena voluntad; pero un hombre bueno te hará amar por el elogio de los demás.", "Stanza 123"],
    ["Hay verdadera amistad cuando uno puede decir todo su corazón al otro; cualquier cosa es mejor que ser inconstante; no es amigo quien solo habla para complacer.", "Stanza 124"],
    ["Te aconsejo, Loddfáfnir, que escuches mi consejo: te será útil si lo sigues, te traerá bien si lo aprendes: ni tres palabras cruces con un hombre peor que tú; a menudo el mejor falla cuando el peor golpea.", "Stanza 125"],
    ["Te aconsejo, Loddfáfnir, que escuches mi consejo: te será útil si lo sigues, te traerá bien si lo aprendes: no seas fabricante de zapatos ni de flechas, a menos que sea para ti mismo; si el zapato está mal formado o la flecha torcida, se te deseará el mal.", "Stanza 126"],
    ["Te aconsejo, Loddfáfnir, que escuches mi consejo: te será útil si lo sigues, te traerá bien si lo aprendes: donde encuentres maldad, denúnciala, y no des paz a tus enemigos.", "Stanza 127"],
    ["Te aconsejo, Loddfáfnir, que escuches mi consejo: te será útil si lo sigues, te traerá bien si lo aprendes: nunca te alegres del mal, sino goza con el bien.", "Stanza 128"],
    ["Te aconsejo, Loddfáfnir, que escuches mi consejo: te será útil si lo sigues, te traerá bien si lo aprendes: no mires hacia arriba en la batalla —como hombres locos se vuelven los hijos de los hombres— no sea que quedes hechizado.", "Stanza 129"],
    ["Te aconsejo, Loddfáfnir, que escuches mi consejo: te será útil si lo sigues, te traerá bien si lo aprendes: si quieres ganar el amor de una buena mujer y gozar de ella, debes prometer bellamente y cumplir tu palabra; nadie rechaza lo bueno si lo obtiene.", "Stanza 130"],
    ["Te aconsejo, Loddfáfnir, que escuches mi consejo: te será útil si lo sigues, te traerá bien si lo aprendes: te pido que seas cauteloso, pero no en exceso; sé cauteloso ante todo con la bebida, con la mujer de otro y, tercero, con que los ladrones no te engañen.", "Stanza 131"],
    ["Te aconsejo, Loddfáfnir, que escuches mi consejo: te será útil si lo sigues, te traerá bien si lo aprendes: nunca te burles ni desprecies a un invitado o a un caminante.", "Stanza 132"],
    ["A menudo no saben bien los que están dentro qué clase de hombre es el que llega; nadie es tan bueno que no tenga defectos, ni tan malvado que no sirva para nada.", "Stanza 133"],
    ["Te aconsejo, Loddfáfnir, que escuches mi consejo: te será útil si lo sigues, te traerá bien si lo aprendes: nunca te rías del orador anciano, a menudo es bueno lo que dicen los viejos; de una piel arrugada suelen salir palabras sabias.", "Stanza 134"],
    ["Te aconsejo, Loddfáfnir, que escuches mi consejo: te será útil si lo sigues, te traerá bien si lo aprendes: no le ladres a un invitado ni lo eches de la puerta, sé amable con el desvalido.", "Stanza 135"],
    ["Fuerte es el travesaño que debe moverse para abrir la puerta a todos; da un anillo o te deseará todo mal en tus miembros.", "Stanza 136"],
    ["Te aconsejo, Loddfáfnir, que escuches mi consejo: donde bebas cerveza, busca el poder de la tierra, pues la tierra cura la ebriedad, el fuego las enfermedades, el roble el estreñimiento, la espiga la magia, el salón las disputas, la luna los celos, el bocado la rabia y las runas el mal; el campo absorberá la inundación.", "Stanza 137"],
    ["Sé que colgué de un árbol mecido por el viento nueve largas noches, herido por una lanza y entregado a Odín, yo mismo a mí mismo, en aquel árbol del que nadie sabe de dónde nacen sus raíces.", "Stanza 138"],
    ["No me dieron pan ni de beber con un cuerno, miré hacia abajo, recogí las runas, gritando las recogí, y de allí caí de nuevo.", "Stanza 139"],
    ["Nueve cantos poderosos aprendí del famoso hijo de Bölthorn, padre de Bestla, y un trago obtuve de la preciosa hidromiel, servida desde Óðrerir.", "Stanza 140"],
    ["Entonces empecé a prosperar y a ser sabio, a crecer y a sentirme bien; de una palabra me llevaba a otra palabra, de una obra me llevaba a otra obra.", "Stanza 141"],
    ["Runas hallarás y signos interpretados, signos muy grandes, signos muy fuertes, que el Gran Orador pintó y los altos poderes hicieron y el Consejero de los Dioses grabó.", "Stanza 142"],
    ["Odín entre los dioses, y Dáinn para los elfos, Dvalinn para los enanos, Ásviðr para los gigantes, y yo mismo grabé algunas.", "Stanza 143"],
    ["¿Sabes cómo se debe grabar? ¿Sabes cómo se debe interpretar? ¿Sabes cómo se debe pintar? ¿Sabes cómo se debe probar? ¿Sabes cómo se debe pedir? ¿Sabes cómo se debe ofrendar? ¿Sabes cómo se debe enviar? ¿Sabes cómo se debe sacrificar?", "Stanza 144"],
    ["Es mejor no pedir que ofrendar en exceso, pues el regalo siempre busca una recompensa; es mejor no enviar que sacrificar demasiado. Así grabó Thundr antes de la historia de los hombres, allí donde se levantó cuando regresó.", "Stanza 145"],
    ["Los conjuros que conozco no los sabe la mujer de ningún rey ni ningún hijo de hombre. 'Ayuda' se llama el primero, y ese te ayudará en pleitos, penas y en todas tus angustias.", "Stanza 146"],
    ["Un segundo conozco, que necesitan los hijos de los hombres que quieren vivir como sanadores.", "Stanza 147"],
    ["Un tercero conozco: si tengo gran necesidad de encadenar a mis enemigos, emboto los filos de mis adversarios; ni sus armas ni sus garrotes pueden herir.", "Stanza 148"],
    ["Un cuarto conozco: si los hombres atan mis miembros con grillos, canto un conjuro que me permite caminar; los grilletes saltan de mis pies y las ataduras de mis manos.", "Stanza 149"],
    ["Un quinto conozco: si veo una lanza volar en medio de la hueste; por muy rápido que vuele, puedo detenerla si la alcanzo con la mirada.", "Stanza 150"],
    ["Un sexto conozco: si un hombre quiere herirme con las raíces de un árbol mágico; el hombre que piensa hacerme daño verá que el mal cae sobre él mismo.", "Stanza 151"],
    ["Un séptimo conozco: si veo el salón arder en torno a mis compañeros; por mucho que arda, puedo salvarlos; ese conjuro sé cantar.", "Stanza 152"],
    ["Un octavo conozco, que es útil para que todos lo aprendan; donde el odio crece entre los hijos de un rey, puedo curarlo pronto.", "Stanza 153"],
    ["Un noveno conozco: si tengo necesidad de salvar mi barco en el mar; calmo el viento sobre las olas y pongo a dormir a todo el mar.", "Stanza 154"],
    ["Un décimo conozco: si veo brujas del aire jugando en el cielo; hago que se pierdan, lejos de sus propias mentes y lejos de sus propios hogares.", "Stanza 155"],
    ["Un undécimo conozco: si debo guiar a viejos amigos a la batalla; canto bajo sus escudos y van con poder, sanos a la lucha y sanos de la lucha, y sanos dondequiera que vayan.", "Stanza 156"],
    ["Un duodécimo conozco: si veo a un muerto colgado en lo alto de un árbol; grabo y pinto las runas de tal modo que el hombre camina y habla conmigo.", "Stanza 157"],
    ["Un decimotercero conozco: si debo verter agua sobre un joven guerrero; no caerá aunque vaya al combate, y no sucumbirá ante la espada.", "Stanza 158"],
    ["Un decimocuarto conozco: si debo enumerar a los dioses ante los hombres; de los dioses y los elfos conozco la verdad, como pocos que no sean sabios pueden saber.", "Stanza 159"],
    ["Un decimoquinto conozco, el que cantó el enano Thjóðreyrir ante las puertas de Delling; cantó poder para los dioses, gloria para los elfos y sabiduría para Odín.", "Stanza 160"],
    ["Un decimosexto conozco: si deseo tener todo el amor y el placer de una doncella sabia; mudo los pensamientos de la mujer de blancos brazos y cambio toda su mente.", "Stanza 161"],
    ["Un decimoséptimo conozco, para que la joven doncella rara vez me deje. Estos conjuros, Loddfáfnir, te faltarán por mucho tiempo; pero son buenos si los aprendes y útiles si los posees.", "Stanza 162"],
    ["Un decimoctavo conozco, que nunca cuento a una doncella ni a la mujer de un hombre —todo es mejor cuando solo uno lo sabe, ese es el fin de los conjuros— excepto a aquella que me estrecha en sus brazos o que sea mi hermana.", "Stanza 163"],
    ["Ahora las palabras del Altísimo han sido dichas en la sala del Altísimo, muy útiles para los hijos de los hombres, muy inútiles para los hijos de los gigantes. ¡Salud a quien las dijo! ¡Salud a quien las conoce! ¡Que aproveche quien las aprendió! ¡Salud a quienes las escucharon!", "Stanza 164"]
];