export const svenska = [

    ["Alla dörrar, innan man går in, bör man betrakta och speja kring; ty ovisst är att veta var ovänner sitter på bänkarna där inne.", "Stanza 1"],
    ["Hell givarna! En gäst har kommit; var skall han sitta? Brådis är den som på tröskeln skall pröva sin lycka.", "Stanza 2"],
    ["Eld behöver den som kommit in och är frusen om knäna; mat och kläder behöver den man som har rest över fjället.", "Stanza 3"],
    ["Vatten behöver den som till måltid kommer, handduk och vänlig hälsning; ett gott ord bör han få, om han kan få det, och tystnad medan andra talar.", "Stanza 4"],
    ["Vett behöver den som vida reser; hemma är allt lätt. Till åtlöje blir den som ingenting vet och sitter bland kloka folk.", "Stanza 5"],
    ["Med sitt vett skall man inte skryta, hellre vara varsam i sinn; när en klok och tystlåten gäst kommer till gården, sker sällan olycka.", "Stanza 6"],
    ["Den varsamme gäst som till måltid kommer, tiger och lyssnar; med öronen hör han, med ögonen spejar han: så prövar varje vis man.", "Stanza 7"],
    ["Säll är den som får lovord och godvilja hos sig själv; ty det är tungt att äga det man måste finna i en annans bröst.", "Stanza 8"],
    ["Säll är den som själv har lovord och vett så länge han lever; ty illasinnade råd har ofta kommit ur en annans bröst.", "Stanza 9"],
    ["Bättre börda bär ingen på vägen än mycket mannavett; bättre än guld är det i främmande land, det är den fattiges tillflykt.", "Stanza 10"],
    ["Bättre börda bär ingen på vägen än mycket mannavett; sämre niste finns inte för resan än för mycket dryck.", "Stanza 11"],
    ["Inte så gott som folk säger är ölet för människornas barn; ty ju mer han dricker, desto mindre vet mannen vad som råder över hans sinn.", "Stanza 12"],
    ["Glömskans häger heter han som över dryckeslaget svävar; han stjäl vettet från mannen. Med de fjädrarna blev jag bunden i Gunnlöds gård.", "Stanza 13"],
    ["Drucken blev jag, jag blev överdryckig hos den kloke Fjalar; det är det bästa med drycken, att var man får sitt vett åter.", "Stanza 14"],
    ["Tyst och tänksam skall en kungason vara och modig i kamp; glad och munter skall varje man vara, ända till döden honom hämtar.", "Stanza 15"],
    ["Den ovise mannen tror han skall leva evigt om han skyr kampen; men ålderdomen ger honom ingen frid, även om spjuten sparar honom.", "Stanza 16"],
    ["Dåren gapar när han kommer på besök, han mumlar eller stirrar; men så snart han får en sup, märks det genast vad som bor i honom.", "Stanza 17"],
    ["Blott den vet som vida har rest och vandrat mycket, vad för ett sinn som bor i varje man; han har själv vett.", "Stanza 18"],
    ["Håll inte på bägaren, men drick mjöd med måtta; tala det nödvändiga eller tig. Ingen vill kalla dig ohyfsad om du går tidigt till sängs.", "Stanza 19"],
    ["Den lystne mannen, om han inte styr sin håg, äter sig till döds; ofta för magen den ovise till åtlöje när han är bland kloka folk.", "Stanza 20"],
    ["Boskapen vet när den skall gå hem och lämnar då betet; men den ovise mannen känner aldrig måttet för sin egen mage.", "Stanza 21"],
    ["En usel man med dåligt sinnelag ler åt allt han ser; han vet inte det han borde veta: att han inte är felfri själv.", "Stanza 22"],
    ["En ovis man vakar alla nätter och grubblar på allt möjligt; han är trött när morgonen kommer, och allt hans elände är som förr.", "Stanza 23"],
    ["En ovis man tror att alla som ler mot honom är hans vänner; han märker inte, när han sitter bland kloka, att de talar illa om honom.", "Stanza 24"],
    ["En ovis man tror att alla som ler mot honom är hans vänner; men när han kommer till tinget, finner han få som för hans talan.", "Stanza 25"],
    ["En ovis man tror sig veta allt när han sitter i en trygg vrå; men han vet inte vad han skall svara när män sätter honom på prov.", "Stanza 26"],
    ["En ovis man, när han kommer bland folk, gör bäst i att tiga; ingen vet att han ingenting kan, såvida han inte talar för mycket. Den som inget vet, märker inte själv när han pratar i nattmössan.", "Stanza 27"],
    ["Klok tycks den som förstår att fråga och vet att svara; människornas barn kan inte dölja det som sker bland folk.", "Stanza 28"],
    ["Mycket onyttigt pratar den som aldrig tiger, med ord utan mening; den snabba tungan som ingen tystnad känner, talar ofta olycka över sig själv.", "Stanza 29"],
    ["Man skall inte göra narr av andra, även om de kommer på besök; mången man verkar klok om han inte blir frågad och får sitta med torr hud på bänken.", "Stanza 30"],
    ["Klok tycks gästen som hånar en annan gäst och sedan smiter; men den som skrattar vid måltiden vet inte säkert om han ler bland ovänner.", "Stanza 31"],
    ["Män är ofta vänliga mot varandra men grälar ändå vid måltiden; denna osämja kommer alltid att finnas: att gäst kämpar mot gäst.", "Stanza 32"],
    ["Frukost skall man ofta äta innan man går på besök, om man inte skall till en vän; annars sitter man och glor hungrig och kan föga ta del i samtalet.", "Stanza 33"],
    ["En stor omväg är det till en dålig vän, även om hans hus ligger vid vägen; men till en god vän leder raka stigar, även om han bor långt borta.", "Stanza 34"],
    ["Gå skall man, en gäst skall inte alltid stanna på samma ställe; det kära blir tråkigt om man sitter för länge på en annans bänk.", "Stanza 35"],
    ["Eget hem är bäst, även om det är litet; var man är herre i sitt hus. Två getter och ett flätat tak är bättre än att tigga.", "Stanza 36"],
    ["Eget hem är bäst, även om det är litet; var man är herre i sitt hus. Hjärtat blöder på den som måste be om mat till varje mål.", "Stanza 37"],
    ["Från sina vapen på marken skall man inte vika en fotbredd; ty man vet aldrig när man på vägen kan behöva sitt spjut.", "Stanza 38"],
    ["Jag fann ingen man så givmild eller gästfri att han inte tog emot en gåva, eller så slösaktig med sitt gods att tack var honom ovälkommet.", "Stanza 39"],
    ["Sitt gods, som man har vunnit, skall man inte spara för mycket; ofta sparas åt ovännen det som var tänkt åt vännen: Mycket går sämre än man tror.", "Stanza 40"],
    ["Med vapen och kläder skall vänner glädja varandra, det syns mest på en själv; givmildhet och gengåva gör vänskapen varaktig, om det i övrigt går väl.", "Stanza 41"],
    ["Sin vän skall man vara vän och gälda gåva med gåva; skratt skall man möta med skratt, men svek med lögn.", "Stanza 42"],
    ["Sin vän skall man vara vän, mot honom och hans vän; men ingen mans oväns vän skall man någonsin vara.", "Stanza 43"],
    ["Vet du att du har en vän som du litar väl på, och du vill ha gott av honom, skall du dela dina tankar med honom och byta gåvor, sök upp honom ofta.", "Stanza 44"],
    ["Har du däremot en annan som du litar illa på, men du vill ändå ha gott av honom, skall du tala fagra ord till honom men tänka svikfullt och gälda lögn med lögn.", "Stanza 45"],
    ["Det är också så med den du misstror och som du anar svek hos: du skall le med honom och tala mot din vilja; gåvan skall likna hans egen.", "Stanza 46"],
    ["Ung var jag förr, jag vandrade ensam och for vill på vägen; rik kände jag mig när jag mötte en annan: människa är människans gamman.", "Stanza 47"],
    ["Givmilda, tappra män lever bäst, de känner sällan sorg; men den fega mannen fruktar allt, och den girige gruvar sig alltid för gåvor.", "Stanza 48"],
    ["Mina kläder gav jag på marken åt två trägubbar; kämpar tycktes de vara när de fick kläder: skamlig är den nakne mannen.", "Stanza 49"],
    ["Tallen förtvinar som står på en ödslig plats, varken bark eller barr skyddar den; så är människan som ingen älskar: hur skall hon kunna leva länge?", "Stanza 50"],
    ["Hetare än eld brinner bland falska vänner kärleken i fem dagar; men den slocknar när den sjätte kommer och hela vänskapen vissnar.", "Stanza 51"],
    ["Inte bara stora ting skall man ge; ofta köper man sig pris för litet. Med en halv kaka och en lutad bägare vann jag mig en kamrat.", "Stanza 52"],
    ["Små sandkorn, små sjöar, litet är människans vett; inte alla människor är lika kloka, varje sinne är halvt.", "Stanza 53"],
    ["Lagom klok bör varje människa vara, aldrig allt för vis; det livet är vackrast att leva för dem som vet väl vad de vet.", "Stanza 54"],
    ["Lagom klok bör varje människa vara, aldrig allt för vis; ty en vis mans hjärta är sällan glatt, om han blivit allt för klok.", "Stanza 55"],
    ["Lagom klok bör varje människa vara, aldrig allt för vis; sitt öde bör ingen veta i förväg, då är sinnet mest fritt från sorg.", "Stanza 56"],
    ["Brand tänds av brand tills den är utbrunnen, eld blir av eld väckt; man blir av man känd genom tal, men av ensamhet blir man dum.", "Stanza 57"],
    ["Tidigt skall han stiga upp som vill ha en annans egendom eller liv; sällan fångar sovande varg ett byte, eller sovande man segern.", "Stanza 58"],
    ["Tidigt skall han stiga upp som har få folk och själv gå till sitt arbete; mycket försummas av den som sover bort morgonen: den flitige är halvvägs rik.", "Stanza 59"],
    ["Om torrt trä och om björkbark vet mannen att ta mått, och om veden som skall ligga i lager för veckor och månader.", "Stanza 60"],
    ["Tvättad och mätt skall man rida till tings, även om man inte är så välklädd; sina skor och byxor skall ingen skämmas över, och inte heller hästen, även om man inte har en bra.", "Stanza 61"],
    ["Snappar och snavar när han kommer till havet, gör örnen vid den gamla floden; så är mannen som kommer bland många och har få som för hans talan.", "Stanza 62"],
    ["Fråga och svara skall varje klok man som vill kallas vis; en får veta det, men inte en till: vet tre det, så vet hela världen det.", "Stanza 63"],
    ["Sin makt skall varje vis man bruka med måtta; ty man finner det när man kommer bland de tappra, att ingen är den allra främste.", "Stanza 64"],
    ["Ord som man talar till en annan, får man ofta betala dyrt för.", "Stanza 65"],
    ["Alltför tidigt kom jag till många ställen, och för sent till vissa; ölet var drucket eller inte bryggt: sällan kommer den ovälkomne i rätt tid.", "Stanza 66"],
    ["Här och där hade man bjudit mig hem om jag inte hade behövt mat vid måltiden, eller om två skinkor hade hängt hos den trofne vännen där jag hade ätit en.", "Stanza 67"],
    ["Eld är det bästa för människors barn, och solens sken; sin hälsa, om man får behålla den, och ett klanderfritt liv.", "Stanza 68"],
    ["En man är inte helt olycklig även om han är sjuk; vissa är rika på söner, vissa på fränder, vissa på mycket gott, vissa på välgjorda verk.", "Stanza 69"],
    ["Bättre är att leva än att inte leva; den levande får alltid kon. Jag såg den rikes eld brinna, men utanför dörren låg han död.", "Stanza 70"],
    ["Den halte kan rida, den handlöse valla, den döve kan kämpa och duga; att vara blind är bättre än att brännas: en död man är till ingen nytta.", "Stanza 71"],
    ["En son är bättre, även om han är sent född efter att fadern gått bort; sällan står bautastenar vid vägen om de inte rests av frände för frände.", "Stanza 72"],
    ["Två är tungans mördare; huvudet är hjärtats fiende. I varje näve väntar jag den dolda armen under kappen.", "Stanza 73"],
    ["På natten litar den som litar på sitt förråd; korta är skeppsplankorna, ostadig är höstnatten. Vädret skiftar ofta på fem dagar, och ännu mer på en månad.", "Stanza 74"],
    ["Den vet ingenting som ingenting vet: många blir dårar av rikedom. En man är rik, en annan fattig; anklaga honom inte för dårskap därför.", "Stanza 75"],
    ["Fä dör, fränder dö, man dör själv på samma vis; men ett gott rykte dör aldrig för den som har vunnit det.", "Stanza 76"],
    ["Fä dör, fränder dö, man dör själv på samma vis; jag vet ett som aldrig dör: domen över varje död man.", "Stanza 77"],
    ["Fulla fållor såg jag hos Fitjungs söner, nu bär de tiggarkäppen; sådan är rikedom, likt en blinkning: den är den mest ostadiga av vänner.", "Stanza 78"],
    ["Den ovise mannen, om han får rikedom eller en kvinnas kärlek, då växer stoltheten men inte vettet: han går allt längre i sitt högmod.", "Stanza 79"],
    ["Det är nu prövat, det du frågar runorna om, de som stammar från gudar, som de höga makterna skapade och stortalaren målade: han gör bäst i att tiga.", "Stanza 80"],
    ["Vid kvällen skall man dagen prisa, konan när hon är bränd, svärdet när det är prövat, mön när hon är gift, isen när man kommit över, ölet när det är drucket.", "Stanza 81"],
    ["I vind skall man ved fälla, i gott väder ro på havet, i mörket tala med mör (många är dagens ögon); skepp är till för färd, sköld till skydd, svärd till hugg och mön till kyssar.", "Stanza 82"],
    ["Vid eld skall man öl dricka, på isen glida, köpa mager häst och rostigt svärd; hästen skall födas hemma, men hunden hos en annan.", "Stanza 83"],
    ["En mös ord skall ingen tro, inte heller vad en kvinna talar; ty på ett rullande hjul blev deras hjärtan skapade och ostadighet lagd i deras bröst.", "Stanza 84"],
    ["Bristande båge, brinnande låga, gapande varg, gispande kråka, grymtande svin, rotlöst träd, växande våg, kokande kittel,", "Stanza 85"],
    ["flygande pil, fallande flod, isen av en natt, ringlad orm, brudtal i sängen eller brustet svärd, lekande björn eller konungabarn,", "Stanza 86"],
    ["sjukt kalv, självrådig träl, völvans smicker, den nyslagne på valplatsen,", "Stanza 87"],
    ["halvbränt hus, snabb häst (för en fot gör hästen onyttig): ingen vare så tillitsfull att han tror på allt detta.", "Stanza 88"],
    ["Sin broders mördare om man möter på vägen, brinnande hus, rask häst (då är en yxa mest nyttig): vem är så tillitsfull att han tror på allt detta!", "Stanza 89"],
    ["Att tro på kärleken hos kvinnor med svek i sinne är som att rida med oskodda hästar på glatt is, med kåta tvååringar, eller i hård storm med styrlöst skepp, eller som en halt som i töväder skall fånga renar på fjället.", "Stanza 90"],
    ["Öppet vill jag nu tala, ty jag känner båda: ostadigt är mäns sinne mot kvinnor; när vi talar fagrast tänker vi falskast: det dårar även den kloke.", "Stanza 91"],
    ["Fagert skall man tala och gåvor bjuda om man vill vinna en kvinnas kärlek; prisa den fagra möns kropp: den som smickrar, han vinner.", "Stanza 92"],
    ["För kärleken skall aldrig en man klandra en annan; ofta fångar den kloke det som inte rör dåren: den fagra skepnaden.", "Stanza 93"],
    ["Aldrig skall en man klandra en annan för dårskap som drabbar många; världens gång gör ofta kloka män till dårar genom begärets makt.", "Stanza 94"],
    ["Sinnet ensamt vet vad som bor nära hjärtat, det ensamt känner sin håg; ingen plåga är värre för en klok man än att inte vara tillfreds med sig själv.", "Stanza 95"],
    ["Det rönte jag själv när jag satt i säven och väntade på min kära; liv och själ var den kloka mön för mig, men ändå fick jag henne inte.", "Stanza 96"],
    ["Billings mö fann jag på sängen, solvithvit, sovande; en jarls glädje tycktes mig intet värd om jag inte fick leva vid den kroppen.", "Stanza 97"],
    ["'Mot kvällen, Oden, skall du komma om du vill vinna mön; det är högst osömligt om inte vi ensamma delar en sådan lön.'", "Stanza 98"],
    ["Jag vände tillbaka och trodde mig älskad, säker i min villfarelse; jag trodde jag vunnit all hennes gunst och glädje.", "Stanza 99"],
    ["Då jag nästa gång kom var hela krigarskaran vaken; med brinnande facklor och burna ljus: så var vägen spärrad för mig.", "Stanza 100"],
    ["Och på morgonen, när jag kom åter, var salens vakt vaken; en hynda fann jag på den goda sängen hos kvinnan, bunden där i hennes ställe.", "Stanza 101"],
    ["Mången fager mö, om man känner henne närmare, är falsk i sinne mot män; det rönte jag när jag den kloka mön lockade till älskog: all slags skam lade den listiga på mig, och jag vann aldrig kvinnan.", "Stanza 102"],
    ["Hemma skall man vara glad och mot gäster munter, sansad med sig själv; den som vill vara vis måste ha mycket kunskap och ofta minnas det goda.", "Stanza 103"],
    ["Den gamle jätten (Suttung) sökte jag upp, nu är jag åter; föga vann jag där genom att tiga. Med många ord talade jag till min fördel i Suttungs salar.", "Stanza 104"],
    ["Gunnlöd gav mig på den gyllene stolen en dryck av det dyra mjödet; dålig lön lät jag henne få efteråt för hennes ärliga sinne, för hennes tunga älskog.", "Stanza 105"],
    ["Rati lät jag gnaga väg och borra genom stenen; över och under mig var jättens vägar: så satte jag mitt huvud i pant.", "Stanza 106"],
    ["Den köpta skepnaden har jag nyttjat väl, den vise brister sällan i råd; ty Odrörer är nu kommen upp till gudarnas boning.", "Stanza 107"],
    ["Tveksamt är om jag hade kommit åter från jättens gårdar, om jag inte nyttjat Gunnlöd, den goda kvinnan, som lade armen om mig.", "Stanza 108"],
    ["Dagen efter gick rimtursarna för att fråga i Den Höges hall efter Den Höge; de frågade om Bölverk var hos gudarna, eller om Suttung hade dräpt honom.", "Stanza 109"],
    ["Ring-ed, säger de, har Oden svurit; vem skall man nu lita på? Suttung har han svikit vid drycken och låtit Gunnlöd sitta kvar i gråt.", "Stanza 110"],
    ["Tid är det att tala från talarstolen vid Urds brunn; jag såg och teg, jag såg och tänkte, jag lyssnade till männens tal.", "Stanza 111"],
    ["Om runor hörde jag dem råda, inte heller brast det i råd; i Den Höges hall, i Den Höges salar, hörde jag dem tala så:", "Stanza 112"],
    ["Jag råder dig, Loddfåvne, ta emot rådet; du har nytta om du tar det, lycka om du följer det: stig inte upp om natten, om du inte skall speja eller gå ut i ärende.", "Stanza 113"],
    ["Jag råder dig, Loddfåvne, ta emot rådet: sov inte i armarna på en trollkunnig kvinna, så att hon inte fångar dig med sina lemmar.", "Stanza 114"],
    ["Hon gör så att du inte bryr dig om tinget eller konungens tal; mat vägrar du och människors glädje, full av sorg går du till sömns.", "Stanza 115"],
    ["Jag råder dig, Loddfåvne, ta emot rådet: locka aldrig en annan mans hustru till lönnlig älskog.", "Stanza 116"],
    ["Jag råder dig, Loddfåvne, ta emot rådet: skall du resa över fjäll eller fjord, utrusta dig väl med niste.", "Stanza 117"],
    ["Jag råder dig, Loddfåvne, ta emot rådet: låt aldrig en ond man få veta din olycka; ty av en ond man får du aldrig lön för din goda tillit.", "Stanza 118"],
    ["Jag såg en man bli dödligt sårad av orden från en ond kvinna; en falsk tunga blev hans bane, och det utan sann anklagelse.", "Stanza 119"],
    ["Jag råder dig, Loddfåvne, ta emot rådet: har du en vän du litar på, dra ofta och besök honom; ty snår växer och högt gräs på vägen som ingen går.", "Stanza 120"],
    ["Jag råder dig, Loddfåvne, ta emot rådet: En god man skall du vinna dig till glädje, och lär dig läkemedel att känna.", "Stanza 121"],
    ["Jag råder dig, Loddfåvne, ta emot rådet: Var aldrig den förste att bryta bandet med din vän; sorg äter hjärtat om du inte kan säga din hela håg till någon.", "Stanza 122"],
    ["Jag råder dig, Loddfåvne, ta emot rådet: Ord skall du aldrig skifta med en ovettig tölp.", "Stanza 123"],
    ["Ty av en ond man kommer du aldrig få gott som lön; men en god man skall göra dig värdefull genom sitt lov.", "Stanza 124"],
    ["Delat sinnelag är det när man säger allt sitt inre till en annan; allt är bättre än att vara falsk: ingen vän är den som bara pratar efter munnen.", "Stanza 125"],
    ["Jag råder dig, Loddfåvne, ta emot rådet: Inte ens med tre ord skall du träta med en sämre man; ofta fäller den sämre den bättre när denne drar svärdet.", "Stanza 126"],
    ["Jag råder dig, Loddfåvne, ta emot rådet: Var inte skomakare eller skaftmakare för andra än dig själv; ty om skon sitter illa eller skaftet är snett, önskar de dig allt ont.", "Stanza 127"],
    ["Jag råder dig, Loddfåvne, ta emot rådet: Där du ser oförrätt, nämn den som oförrätt, och ge dina ovänner ingen frid.", "Stanza 128"],
    ["Jag råder dig, Loddfåvne, ta emot rådet: Gläd dig aldrig åt det onda, men låt dig tjusas av det goda.", "Stanza 129"],
    ["Jag råder dig, Loddfåvne, ta emot rådet: Se inte upp i strid (ty människornas barn blir som vanvettiga), så att män inte förhäxar dig.", "Stanza 130"],
    ["Jag råder dig, Loddfåvne, ta emot rådet: Vill du vinna en kvinnas älskog, håll fast vid dina löften; ingen tröttnar på det goda om han får det.", "Stanza 131"],
    ["Jag råder dig, Loddfåvne, ta emot rådet: Var varsam, men inte rädd; var mest varsam med drycken och med en annan mans hustru.", "Stanza 132"],
    ["Jag råder dig, Loddfåvne, ta emot rådet: Spotta aldrig på en gäst eller en vandrare, och le inte åt honom.", "Stanza 133"],
    ["Jag råder dig, Loddfåvne, ta emot rådet: Le aldrig åt en gråhårig talare; ofta är det gott det de gamla säger. Ur skrynklig hud kommer ofta kloka ord.", "Stanza 134"],
    ["Ofta hänger de bland hudarna, dinglar under skinnen och slänger bland de vissna.", "Stanza 135"],
    ["Jag råder dig, Loddfåvne, ta emot rådet: Skäll inte på gästen och jaga honom inte på porten; var god mot de arma.", "Stanza 136"],
    ["Stark är den dörrstolpe som skall öppna sig för alla; ge en ring, eller så kommer de önska dig varje olycka.", "Stanza 137"],
    ["Jag vet att jag hängde i det vindkalla trädet i nio hela nätter, sårad med spjut och given åt Oden, jag själv åt mig själv.", "Stanza 138"],
    ["I det trädet som ingen vet varifrån dess rötter rinner.", "Stanza 139"],
    ["De räckte mig varken bröd eller dryckeshorn; jag spejade neråt, jag tog upp runorna, skrikande tog jag dem, och föll sedan ner därifrån.", "Stanza 140"],
    ["Då började jag gro och bli vis, att växa och trivas väl; ord följde ord till nytt ord, verk följde verk till nytt verk.", "Stanza 141"],
    ["Runor skall du finna och läsbara stavar, mycket stora stavar, mycket mäktiga stavar, som stortalaren målade och de höga makterna skapade och gudarnas Hroptr ristade.", "Stanza 142"],
    ["Oden bland asar, för alfer Daínn, Dvalin för dvärgar, Allsvinn för jättar; jag själv ristade några för människornas barn.", "Stanza 143"],
    ["Vet du hur man skall rista? Vet du hur man skall råda? Vet du hur man skall måla? Vet du hur man skall pröva? Vet du hur man skall be? Vet du hur man skall offra? Vet du hur man skall sända? Vet du hur man skall sletta (utplåna)?", "Stanza 144"],
    ["Bättre är inget bett än för mycket offrat, en gåva ser alltid efter gengåva; bättre är inget sänt än för mycket slettat. Så ristade Thundr före folkens historia, där han steg upp, när han kom tillbaka.", "Stanza 145"],
    ["De sånger känner jag som ingen drottning kan och ingen mans son. 'Hjälp' heter den första, ty den hjälper dig i strid och sorg och i alla kval.", "Stanza 146"],
    ["En andra känner jag som människornas barn behöver, de som vill leva som läkare: att bota sår och lindra sjukdom.", "Stanza 147"],
    ["En tredje känner jag: om jag har stor nöd att binda mina ovänner, så slövar jag eggen på motståndarnas vapen; varken svärd eller svek hjälper dem då.", "Stanza 148"],
    ["En fjärde känner jag: om män lägger bojor på mina lemmar, så sjunger jag så att jag kan gå; länken spricker från fötterna och bandet från händerna.", "Stanza 149"],
    ["En femte känner jag: om jag ser en pil flyga som vill skada i hären, så flyger den inte så snabbt att jag inte hejdar den, om jag får syn på den.", "Stanza 150"],
    ["En sjätte känner jag: om en man vill skada mig med rötterna av ett främmande träd, så drabbar olyckan honom själv och inte mig.", "Stanza 151"],
    ["En sjunde känner jag: om jag ser salen brinna kring mina bänkkamrater, så brinner den inte så hett att jag inte räddar den; den galdern kan jag sjunga.", "Stanza 152"],
    ["En åttonde känner jag som är nyttig för alla att lära: där hat växer mellan furstesöner, där kan jag snabbt dämpa det.", "Stanza 153"],
    ["En nionde känner jag: om nöd tvingar mig att rädda mitt skepp på havet, så stillar jag vinden på vågorna och lullar hela havet i sömn.", "Stanza 154"],
    ["En tionde känner jag: om jag ser gandreid-kvinnor leka i luften, så gör jag så att de förvillar sig från sina egna hudar och sitt eget sinne.", "Stanza 155"],
    ["En elfte känner jag: om jag skall leda gamla vänner till strid, så sjunger jag under sköldarna och de drar med makt; hela till strid, hela från strid, de kommer hela överallt.", "Stanza 156"],
    ["En tolfte känner jag: om jag ser en hängd man i ett träd, så ristar och målar jag runor så att mannen går och talar med mig.", "Stanza 157"],
    ["En trettonde känner jag: om jag öser vatten över en ung krigare, så kommer han inte att falla även om han drar i kamp; inget svärd biter på honom.", "Stanza 158"],
    ["En fjortonde känner jag: om jag skall räkna upp gudar för folk, asar och alfer, så känner jag alla väl; sällan känner en ovettig dem så.", "Stanza 159"],
    ["En femtonde känner jag som dvärgen Tjodreir sjöng inför Dellings dörrar: han sjöng kraft åt asar, ära åt alfer och visdom åt Hroptr.", "Stanza 160"],
    ["En sextonde känner jag: om jag vill ha en klok mös älskog och lust, så vänder jag sinnet hos den vitarmade kvinnan och vänder hela hennes hjärta.", "Stanza 161"],
    ["En sjuttonde känner jag, så att den unga mön aldrig vill skiljas från mig; dessa sånger, Loddfåvne, kommer du länge att sakna.", "Stanza 162"],
    ["En artonde känner jag som jag aldrig lär ut till mö eller mans hustru, utom till den enda som min arm famnar eller som är min syster; allt är bättre när bara en vet det.", "Stanza 163"],
    ["Nu är Den Höges tal talat i Den Höges hall, nyttigt för människornas barn, onyttigt för jättarnas söner. Hell den som talade! Hell den som känner! Nytta har den som lärde! Hell dem som lyssnade!", "Stanza 164"]
];
