export const english = [

    ["At every door-way, before one enters, one should spy round, one should look round; for it is hard to know where enemies sit in the hall before thee.", "Stanza 1"],
    ["Hail to the givers! a guest has come; where shall the stranger sit? Swift shall he be who, with knots to untie, shall test his fortune forth.", "Stanza 2"],
    ["Fire he needs who with frozen knees has come from the wild without; food and clothing the wanderer craves who has fared o'er the iron fells.", "Stanza 3"],
    ["Water he needs who comes to the feast, towels and lowly greeting; if a good reception he wishes to win, he must talk and be answered again.", "Stanza 4"],
    ["Wits are needed by him who wanders wide, at home is all easy; but a laughing-stock is he who nothing knows and sits with the wise together.", "Stanza 5"],
    ["Of his knowledge proud shall no man be, but rather be careful in mind; when to his house a weary guest comes, let him be silent and heedful; for a more faithful friend shall a man ne'er find than a right good share of wit.", "Stanza 6"],
    ["The wary guest who comes to the feast is silent and listens long; with his ears he hears, with his eyes he looks, and the wise man spies about.", "Stanza 7"],
    ["Happy is he who for himself wins favor and praise of men; for difficult is it to find in the breast of another a man's own mind.", "Stanza 8"],
    ["Happy is he who in life possesses praise and wit as well; for often has man from another's breast received but evil rede.", "Stanza 9"],
    ["A better burden can no man bear on the way than a store of wit; it is better than wealth in a strange abode, and a refuge is it in need.", "Stanza 10"],
    ["A better burden can no man bear on the way than a store of wit; worse victuals for the way can no man take than a surfeit of ale.", "Stanza 11"],
    ["Ale is not so good as it is said for the sons of men; for the more a man drinks, the less he knows how to keep his mind.", "Stanza 12"],
    ["The heron of forgetfulness hovers o'er feasts, and steals the minds of men; with the feathers of that fowl I was fettered once in the court of Gunnlöd.", "Stanza 13"],
    ["Drunk I was, I was dead-drunk, at the house of Fjalar the wise; for the best of drinking is when every man gets back his mind again.", "Stanza 14"],
    ["Silent and thoughtful a prince's son should be, and bold in battle; glad and happy let every man be until he meets his death.", "Stanza 15"],
    ["The coward believes he will live forever if he keeps him safe from strife; but old age leaves him no peace in the end, though the spears have spared him.", "Stanza 16"],
    ["The fool gapes wide when he comes to a feast, he mumbles or else he stares; but if he gets a drink, in a moment his mind is shown to all.", "Stanza 17"],
    ["He alone knows who wanders wide and has fared through many a land, what mind is in every man he meets, if himself has wit.", "Stanza 18"],
    ["Shun not the mead, but drink in measure; speak that which is needful or be silent; for no man will chide thee for lack of manners if thou goest early to sleep.", "Stanza 19"],
    ["The gluttonous man, if his mind he knows not, eats to his own undoing; and a fool's belly often brings him to scorn when he comes among the wise.", "Stanza 20"],
    ["The herds know well when home they shall go, and leave the grazing land; but the foolish man never knows the measure of his own belly.", "Stanza 21"],
    ["A wretched man with an evil mind sneers at everything; one thing he knows not, which he ought to know, that he is not free from faults.", "Stanza 22"],
    ["A witless man stays awake all night, and worries about everything; he is weary indeed when the morning comes, and all is as bad as before.", "Stanza 23"],
    ["A witless man thinks that all who smile on him are his friends; he does not perceive, when he sits with the wise, that they speak ill of him.", "Stanza 24"],
    ["A witless man thinks that all who smile on him are his friends; but when he comes to the Thing, he finds that he has few to speak for him.", "Stanza 25"],
    ["A witless man thinks he knows everything if he sits in a corner safe; but he knows not what answer to make when men test his wits.", "Stanza 26"],
    ["A witless man, when he comes among men, had best be silent; for no one will know that he nothing knows unless he talks too much; and the man who knows nothing, knows not when he talks too much.", "Stanza 27"],
    ["Wise he seems who knows how to ask, and also how to answer; the sons of men can never hide what people say of men.", "Stanza 28"],
    ["He utters many a useless word who is never silent; a ready tongue, unless it be bridled, often brings trouble on itself.", "Stanza 29"],
    ["A man should not make a laughing-stock of another who comes to his house; many a one seems wise if he be not asked, and sits with dry skin in his corner.", "Stanza 30"],
    ["Wise a guest seems who flees from a guest who makes a mock of him; but he who laughs at another at meat knows not if he laughs with his enemies.", "Stanza 31"],
    ["Many are men who are friendly-minded, yet mock each other at meat; ever will there be strife among men, and guest will wrangle with guest.", "Stanza 32"],
    ["A man should take his meal early, unless he goes to a friend's; he sits and mopes, like one who is hungry, and has little power to ask.", "Stanza 33"],
    ["A long way it is to a false friend, though his house be on the road; but to a true friend the way is short, though he has fared far away.", "Stanza 34"],
    ["Forth shall one go, and not be a guest forever in one place; the welcome becomes wearisome if one sits too long in another's house.", "Stanza 35"],
    ["A house of one's own is better, though small; everyone is master at home; though he has but two goats and a bark-thatched hut, it is better than begging for a meal.", "Stanza 36"],
    ["A house of one's own is better, though small; everyone is master at home; his heart bleeds who must beg for his food for every meal.", "Stanza 37"],
    ["A man should never go a foot's length from his weapons on the field; for he knows not when on the way without he may have need of his spear.", "Stanza 38"],
    ["I have never found a man so generous and so free with his food that he would not take what was offered, or so bold with his money that he would loathe a gift if he received it.", "Stanza 39"],
    ["Of the wealth he has won, a man should not suffer need; often that is saved for a foe which was meant for a friend; many things go worse than expected.", "Stanza 40"],
    ["With weapons and weeds should friends be won, for such is most seen on oneself; givers and requiters are longest friends, if things go well as they should.", "Stanza 41"],
    ["To his friend a man should be a friend, and gifts with gifts requite; laughter with laughter let men receive, but falsehood with a lie.", "Stanza 42"],
    ["To his friend a man should be a friend, to him and the friend of his friend; but no man should ever be a friend to the friend of his enemy.", "Stanza 43"],
    ["If thou hast a friend whom thou trustest well from whom thou wilt good receive, thy mind shalt thou blend with his, and gifts shalt thou exchange, and fare to find him oft.", "Stanza 44"],
    ["If thou hast another whom thou trustest ill, from whom thou wilt good receive, fair shalt thou speak but false shalt thou think, and falsehood with lies requite.", "Stanza 45"],
    ["Yet further of him whom thou trustest ill, and whose mind thou dost mistrust; thou shalt laugh with him and speak against thy thought, for gifts should be like the giver's.", "Stanza 46"],
    ["Young was I once, I walked alone, and then I lost my way; rich I felt when I found another, for man is the joy of man.", "Stanza 47"],
    ["The noble and brave live best and are happiest, and seldom feel sorrow; but the coward is ever in fear, and the miser is ever mourning for gifts.", "Stanza 48"],
    ["My garments I gave to two wooden men who stood on the field; noble they seemed when clothes they had, for the naked man is shamed.", "Stanza 49"],
    ["The pine tree wastes that stands in the village, and has neither bark nor needles; so is the man whom no one loves, why should he live for long?", "Stanza 50"],
    ["Hotter than fire for five days' time burns friendship between false friends; but it is quenched when the sixth day comes, and all the friendship is spoiled.", "Stanza 51"],
    ["A great thing a man should not give, for often is praise won with little; with half a loaf and a tilted bowl I have found myself a comrade.", "Stanza 52"],
    ["Little the sand, little the seas, little the minds of men; for all men are not equally wise, a man is half-everywhere.", "Stanza 53"],
    ["A measure of wisdom should each man have, but never too much of it; for the life of those is fairest to see who know many things right well.", "Stanza 54"],
    ["A measure of wisdom should each man have, but never too much of it; for the heart of the wise is seldom glad, if too much wisdom he has.", "Stanza 55"],
    ["A measure of wisdom should each man have, but never too much of it; let no man know his fate beforehand, for his mind is freest from care.", "Stanza 56"],
    ["Brand burns from brand until it is burnt, fire is kindled from fire; man is known by his speech to man, and the dull by his silence.", "Stanza 57"],
    ["Early shall he rise who seeks the life or the wealth of another; seldom the lounging wolf gets the meat, or the sleeping man the victory.", "Stanza 58"],
    ["Early shall he rise who has few to work, and go to his work himself; much hinders the man who sleeps in the morning, for half of wealth is in haste.", "Stanza 59"],
    ["Of dry logs and bark for the roof, a man knows well the measure, and of the wood that can last for a time and for many months to come.", "Stanza 60"],
    ["Washed and fed should a man ride to the Thing, though his clothes be not the best; of his shoes and breeches let no man be ashamed, nor of his horse, though it be not good.", "Stanza 61"],
    ["The eagle snatches and the eagle snaps when he comes to the sea; so it is with a man who comes among many and has few to speak for him.", "Stanza 62"],
    ["To ask and to answer should every wise man seek, who wishes to be called clever; let one know, but a second never, for the world knows if three know.", "Stanza 63"],
    ["His power should every wise man use in a cautious way; for he finds, when he comes among the brave, that no one is the boldest of all.", "Stanza 64"],
    ["For the words that a man says to another, he often pays a price.", "Stanza 65"],
    ["Much too early I came to many a place, and too late to some; the ale was drunk, or it was not yet brewed; the loathed guest seldom finds the right time.", "Stanza 66"],
    ["Here and there I would have been invited home, if I had not needed meat at meal-time, or if two hams had hung at my true friend's, where I had eaten one.", "Stanza 67"],
    ["Fire is best for the sons of men, and the sight of the sun; his health, if a man may have it, and a life without vice.", "Stanza 68"],
    ["No man is entirely wretched, though his health be bad; one is blessed with sons, another with kinsmen, another with wealth, another with goodly works.", "Stanza 69"],
    ["Better to be alive than to be dead, for the living man gets the cow; I saw the fire burn for the rich man, but outside he lay dead at the door.", "Stanza 70"],
    ["The halt can ride a horse, the handless can drive a herd, the deaf can fight and be useful; better to be blind than to be burnt; a corpse is of no use to anyone.", "Stanza 71"],
    ["A son is better, though born late after his father has passed; seldom do memorial stones stand by the way unless raised by a kinsman to kinsman.", "Stanza 72"],
    ["Two are an army, the tongue is the head's bane; under every cloak I expect a hand.", "Stanza 73"],
    ["The night is welcomed by him who trusts his provisions, short are the ship's oars; fickle is the autumn night; the weather changes much in five days, and more in a month.", "Stanza 74"],
    ["He knows not, who knows nothing, that many are made fools by wealth; one man is rich, another is poor, let no man blame another for his lot.", "Stanza 75"],
    ["Cattle die, kinsmen die, and so one dies oneself; but a good name never dies for him who has earned it.", "Stanza 76"],
    ["Cattle die, kinsmen die, and so one dies oneself; but I know one thing that never dies: the judgment on each one dead.", "Stanza 77"],
    ["Full folds I saw for the sons of Fitjung, now they carry a beggar's staff; wealth is like the twinkle of an eye, the most fickle of friends.", "Stanza 78"],
    ["A witless man, if he wins for himself wealth or a woman's love, his pride increases, but his wit never; he goes further and further in his folly.", "Stanza 79"],
    ["Then it is proven, when thou askest the runes, the gods-sprung ones, which the high powers made and the Great Speaker painted: that he had best be silent.", "Stanza 80"],
    ["At evening shall the day be praised, a woman after she is burnt, a sword after it is tried, a maid after she is married, ice after it is crossed, ale after it is drunk.", "Stanza 81"],
    ["In the wind shall one hew wood, in a breeze row out to sea, in the dark dally with a maiden (many are the eyes of day); for speed a ship is used, for protection a shield, for blows a sword, and for kisses a maid.", "Stanza 82"],
    ["By the fire shall ale be drunk, on the ice shall one skate; a lean horse shall one buy, and a stained sword; at home shall the horse be fattened, and the dog at the farm.", "Stanza 83"],
    ["In a maiden's words shall no man trust, nor in what a woman says; for on a whirling wheel their hearts were fashioned, and fickleness laid in their breasts.", "Stanza 84"],
    ["A breaking bow, a burning flame, a yawning wolf, a croaking crow, a grunting swine, a rootless tree, a waxing wave, a boiling kettle,", "Stanza 85"],
    ["A flying arrow, a falling wave, ice of a single night, a coiled adder, a woman's bed-talk, or a broken sword, the play of a bear, or a king's child,", "Stanza 86"],
    ["A sick calf, a self-willed thrall, a witch's flattering words, a new-slain foe.", "Stanza 87"],
    ["An early-sown field let no man trust, nor too soon in a son; the weather rules the field, and wit the son, and each of these is fickle.", "Stanza 88"],
    ["The slayer of a brother, though met on the road, a half-burnt house, a horse too swift (for the horse is useless if one leg breaks); let no man be so trustful as to trust in all of these.", "Stanza 89"],
    ["Such is the love of women, who think with deceit, as to drive a horse without calks on slippery ice, a gay two-year-old, and ill-tamed, or to steer a rudderless ship in a gale, or for a halt man to catch a reindeer on a thawing hillside.", "Stanza 90"],
    ["Plainly I speak, for both I know: fickle is the mind of man to women; when we speak most fair, we think most false; that traps the wisest mind.", "Stanza 91"],
    ["Fair shall he speak and wealth shall he offer who wishes to win a woman's love; he should praise the beauty of the bright maid; he wins who woos.", "Stanza 92"],
    ["For his love shall no man ever blame another; often the wise are trapped, where the fools are not, by the beauty of a face.", "Stanza 93"],
    ["For a fault of his own shall no man blame another, for that which happens to many; the mighty passion turns the sons of men from wise to fools.", "Stanza 94"],
    ["The mind alone knows what is near the heart, each man is his own judge; there is no sickness worse for any wise man than to be satisfied with nothing.", "Stanza 95"],
    ["This I found when I sat in the reeds and waited for my love; body and soul was that sweet maid to me, yet I won her not.", "Stanza 96"],
    ["Billing's daughter I found on her bed, sun-bright, sleeping; no joy of a jarl seemed equal to that, to live with that lovely form.", "Stanza 97"],
    ["'Near evening, Odin, shalt thou come if thou wouldst woo the maid; it were all unmeet unless we alone should know of such a sin.'", "Stanza 98"],
    ["Away I went, and I thought I loved with a wise man's hope; I thought that I should have her heart and all her joy.", "Stanza 99"],
    ["So I came next when the warriors all were awake and watching; with burning lights and bearing torches, a path of woe was marked for me.", "Stanza 100"],
    ["And near morning, when I came again, the warriors all were sleeping; a dog I found of the noble dame tied fast upon her bed.", "Stanza 101"],
    ["Many a maid, if one knows her well, is fickle of mind to men; that I found when the clever maid I sought to lead astray; every insult the crafty woman heaped upon my head, and I won the maid not at all.", "Stanza 102"],
    ["At home let a man be glad, and cheerful with guests, and cautious about himself; mindful and ready of speech if he wishes to be wise, he should often speak of the good; a 'fimbul-fambi' is he called who has little to say, for such is the way of the ignorant.", "Stanza 103"],
    ["The ancient giant I sought, now I am come back, little I got there by silence; with many words I spoke to my profit in Suttung's halls.", "Stanza 104"],
    ["Gunnlöd gave me on the golden chair a draught of the precious mead; a poor reward I let her have for her weary spirit and her heartfelt love.", "Stanza 105"],
    ["With Rati's mouth I made me room and gnawed through the rock; over and under were the giants' ways, so I risked my head.", "Stanza 106"],
    ["The well-earned prize I have used right well, for the wise lacks little; for Odrerir now has come up to the earth of the men of the world.", "Stanza 107"],
    ["Doubt have I if I should have come out from the giants' courts, had I not used Gunnlöd, the noble dame, whom I held in my arms.", "Stanza 108"],
    ["The next day the frost-giants came to ask for the High One's counsel in the High One's hall; they asked for Bölverk, if he were with the gods or if Suttung had slain him.", "Stanza 109"],
    ["A ring-oath, I think, Odin has sworn; who can trust his troth? Suttung he cheated of his mead and left Gunnlöd to weep.", "Stanza 110"],
    ["It is time to speak from the speaker's chair by the well of Urd; I saw and was silent, I saw and I thought, I listened to the speech of men; of runes I heard them speak, and of secret counsel in the High One's hall, and this is what they said:", "Stanza 111"],
    ["I counsel thee, Loddfáfnir, to take my advice, — thou wilt profit if thou takest it, it will be well for thee if thou learnest it —: rise not at night unless thou art spying or seeking a place without.", "Stanza 112"],
    ["I counsel thee, Loddfáfnir, to take my advice, — thou wilt profit if thou takest it, it will be well for thee if thou learnest it —: bewitch not a woman's love, so that she holds thee in her arms.", "Stanza 113"],
    ["She will bring it to pass that thou carest not for the Thing or the speech of the king; food thou wilt loathe and the joy of men, and sorrowful go to thy sleep.", "Stanza 114"],
    ["I counsel thee, Loddfáfnir, to take my advice, — thou wilt profit if thou takest it, it will be well for thee if thou learnest it —: never entice to thy side another's wife as a secret friend.", "Stanza 115"],
    ["I counsel thee, Loddfáfnir, to take my advice, — thou wilt profit if thou takest it, it will be well for thee if thou learnest it —: if on the mountain or fjord thou farest, see that thou hast good food.", "Stanza 116"],
    ["I counsel thee, Loddfáfnir, to take my advice, — thou wilt profit if thou takest it, it will be well for thee if thou learnest it —: never let an evil man know thy misfortune; for from an evil man thou wilt never get a reward for thy good will.", "Stanza 117"],
    ["I saw a man wounded by the words of an evil man; a false tongue was the death of him, and not even for a true cause.", "Stanza 118"],
    ["I counsel thee, Loddfáfnir, to take my advice, — thou wilt profit if thou takest it, it will be well for thee if thou learnest it —: if thou hast a friend whom thou trustest well, go to find him oft; for the path grows over with brush and high grass which no one treads.", "Stanza 119"],
    ["I counsel thee, Loddfáfnir, to take my advice, — thou wilt profit if thou takest it, it will be well for thee if thou learnest it —: draw a good man to thee for the sake of his love, and learn the spells of life while thou livest.", "Stanza 120"],
    ["I counsel thee, Loddfáfnir, to take my advice, — thou wilt profit if thou takest it, it will be well for thee if thou learnest it —: be never the first to break the bond of friendship with thy friend; sorrow eats the heart if thou canst not tell all thy mind to someone.", "Stanza 121"],
    ["I counsel thee, Loddfáfnir, to take my advice, — thou wilt profit if thou takest it, it will be well for thee if thou learnest it —: never exchange words with a witless ape.", "Stanza 122"],
    ["For from an evil man thou wilt never get a reward for thy good will; but a good man will make thee loved by the praise of others.", "Stanza 123"],
    ["A shared mind is when one can tell all his heart to another; anything is better than being fickle; he is no friend who speaks only to please.", "Stanza 124"],
    ["I counsel thee, Loddfáfnir, to take my advice, — thou wilt profit if thou takest it, it will be well for thee if thou learnest it —: not three words shalt thou bandy with a worse man; often the better man fails when the worse man strikes.", "Stanza 125"],
    ["I counsel thee, Loddfáfnir, to take my advice, — thou wilt profit if thou takest it, it will be well for thee if thou learnest it —: be not a maker of shoes or of shafts, unless it be for thyself; if the shoe is ill-shaped or the shaft be crooked, then evil is wished to thee.", "Stanza 126"],
    ["I counsel thee, Loddfáfnir, to take my advice, — thou wilt profit if thou takest it, it will be well for thee if thou learnest it —: wherever thou findest evil, speak out against it, and give no peace to thy foes.", "Stanza 127"],
    ["I counsel thee, Loddfáfnir, to take my advice, — thou wilt profit if thou takest it, it will be well for thee if thou learnest it —: in evil be never glad, but let the good be thy joy.", "Stanza 128"],
    ["I counsel thee, Loddfáfnir, to take my advice, — thou wilt profit if thou takest it, it will be well for thee if thou learnest it —: look not up in battle, — like men gone mad are the sons of men — lest the men should bewitch thee.", "Stanza 129"],
    ["I counsel thee, Loddfáfnir, to take my advice, — thou wilt profit if thou takest it, it will be well for thee if thou learnest it —: if thou wilt win for thyself a good woman's love and have joy of her, fair must thou promise and keep thy word; no one loathes the good if he gets it.", "Stanza 130"],
    ["I counsel thee, Loddfáfnir, to take my advice, — thou wilt profit if thou takest it, it will be well for thee if thou learnest it —: I bid thee be wary, yet not over-wary; be wariest with ale and with another's wife, and thirdly, that thieves do not outwit thee.", "Stanza 131"],
    ["I counsel thee, Loddfáfnir, to take my advice, — thou wilt profit if thou takest it, it will be well for thee if thou learnest it —: never hold in mock or scorn a guest or a wanderer.", "Stanza 132"],
    ["Often they know not well, who sit within, what kind of man he is who comes; no man is so good that no fault follows him, nor so wicked that he is of no use.", "Stanza 133"],
    ["I counsel thee, Loddfáfnir, to take my advice, — thou wilt profit if thou takest it, it will be well for thee if thou learnest it —: at a hoary speaker laugh thou never, often is good what the old men say; often from a shriveled skin come wise words.", "Stanza 134"],
    ["I counsel thee, Loddfáfnir, to take my advice, — thou wilt profit if thou takest it, it will be well for thee if thou learnest it —: bark not at a guest nor drive him from the gate, be kind to the poor.", "Stanza 135"],
    ["Strong is the beam that must be moved to open the door to all; give thou a ring, or it will wish thee every ill in thy limbs.", "Stanza 136"],
    ["I counsel thee, Loddfáfnir, to take my advice, — thou wilt profit if thou takest it, it will be well for thee if thou learnest it —: where thou drinkest ale, choose the power of the earth, for earth takes the ale, and fire the sickness, the oak the swelling, the ear against magic, the hall against strife — for hate one must fight — the moon against jealousy, the bit against biting-sickness, and runes against evil; the field shall take the flood.", "Stanza 137"],
    ["I know that I hung on a windy tree nine long nights, wounded with a spear, dedicated to Odin, myself to myself, on that tree of which no man knows from where its roots run.", "Stanza 138"],
    ["With no bread did they mock me nor a drinking horn, I looked down, I took up the runes, screaming I took them, and fell back from there.", "Stanza 139"],
    ["Nine mighty songs I learned from the famous son of Bölthorn, Bestla's father, and a draught I got of the precious mead, poured from Odrerir.", "Stanza 140"],
    ["Then I began to thrive, and wisdom to get, I grew and well I was; each word led me on to another word, each deed to another deed.", "Stanza 141"],
    ["Runes shalt thou find, and read the signs, very strong signs, very stout signs, which the Great Speaker painted and the high powers made and the Counselor of the Gods wrote.", "Stanza 142"],
    ["Odin among the gods, and Dain for the elves, Dvalin for the dwarfs, Alsvid for the giants, and I myself wrote some.", "Stanza 143"],
    ["Knowest thou how one shall write? Knowest thou how one shall read? Knowest thou how one shall paint? Knowest thou how one shall test? Knowest thou how one shall ask? Knowest thou how one shall sacrifice? Knowest thou how one shall send? Knowest thou how one shall shed?", "Stanza 144"],
    ["Better no prayer than too big an offering, by a gift a gift is sought; better no sending than too much shedding. So Thund wrote before the history of men, where he rose up, when he came back.", "Stanza 145"],
    ["The spells I know, which no king's wife knows, nor any son of man; 'Help' one is called, and that will help thee in sickness and sorrow and all thy grief.", "Stanza 146"],
    ["A second I know, which the sons of men need who would live as healers.", "Stanza 147"],
    ["A third I know, if great is my need of fetters for my foes; the edges of my enemies I dull, and neither weapons nor clubs can bite.", "Stanza 148"],
    ["A fourth I know, if men shall bind my limbs with fetters; I chant a spell that I may go free, the fetters spring from my feet, and the bonds from my hands.", "Stanza 149"],
    ["A fifth I know, if I see a spear flying in the host; however fast it flies, I can stop it if I catch it with my eyes.", "Stanza 150"],
    ["A sixth I know, if a man would wound me with the roots of a magic tree; the man who thinks to do me harm shall find that the harm falls on himself.", "Stanza 151"],
    ["A seventh I know, if I see the hall high-burning around my bench-mates; however wide it burns, I can save them; that spell I know how to chant.", "Stanza 152"],
    ["An eighth I know, which for everyone is useful to learn; where hate grows among the sons of a king, I can quickly heal it.", "Stanza 153"],
    ["A ninth I know, if I have need to save my ship on the sea; I calm the wind on the waves and put all the sea to sleep.", "Stanza 154"],
    ["A tenth I know, if I see hags of the air playing in the sky; I so work it that they wander lost, far from their own minds and far from their own homes.", "Stanza 155"],
    ["An eleventh I know, if I must lead my old friends into battle; under their shields I chant, and they go with power, whole to the fight, and whole from the fight, and whole wherever they go.", "Stanza 156"],
    ["A twelfth I know, if I see a dead man hanging high on a tree; I so write and paint the runes that the man shall walk and speak with me.", "Stanza 157"],
    ["A thirteenth I know, if I shall pour water on a young man; he shall not fall, though he goes to the fight, and he shall not sink before the sword.", "Stanza 158"],
    ["A fourteenth I know, if I shall tell the host of the gods before men; of gods and elves I know the truth, as few who are not wise can know.", "Stanza 159"],
    ["A fifteenth I know, which Thjodrerir the dwarf chanted before Delling's doors; he chanted power to the gods, and glory to the elves, and wisdom to Odin.", "Stanza 160"],
    ["A sixteenth I know, if I wish to have all the mind and joy of a wise maid; I turn the thoughts of the white-armed maid and change all her mind.", "Stanza 161"],
    ["A seventeenth I know, so that the young maid shall seldom leave me. These spells, Loddfáfnir, shalt thou long lack; yet they are good if thou learnest them, and useful if thou hast them.", "Stanza 162"],
    ["An eighteenth I know, which I never tell to a maid or a man's wife — everything is better when only one knows, that is the end of the spells — except to her who holds me in her arms or who is my sister.", "Stanza 163"],
    ["Now the words of the High One are spoken in the High One's hall, very useful to the sons of men, quite useless to the sons of giants. Hail to him who spoke! Hail to him who knows! May he profit who learned! Hail to those who listened!", "Stanza 164"]
];