export const islenska = [

    ["Gáttir allar, áður gangi fram, um skoðast skyli, um skyggnast skyli, því að óvíst er að vita, hvar óvinir sitja á fleti fyrir.", "Stanza 1"],
    ["Gefendur heilir! Gestur er inn kominn, hvar skal sitja á? Mjög er bráður, sá er á bröndum skal síns of freista frama.", "Stanza 2"],
    ["Elds er þörf, þeim er inn er kominn og á kné kalsinn; matar og fata er manni þörf, þeim er hefur um fjall farið.", "Stanza 3"],
    ["Vatns er þörf, þeim er til verðar kemur, þerru og þjóðlaðar; góðs um æðis, ef sér geta mætti, orðs og endurþagnar.", "Stanza 4"],
    ["Vits er þörf, þeim er víða ratar; dælt er heima hvað. Að augabragði verður, sá er ekki kann og með snotrum situr.", "Stanza 5"],
    ["Við snotran mann skal engi gorta, heldur sé hann í hyggju var; þá er horskur og þögull kemur heimsgarða til, verður sjaldan víti vörum.", "Stanza 6"],
    ["Hinn vargi gestur, er til verðar kemur, þunnu hljóði þegir; eyrum hlýðir, en augum skoðar: svo nýsist fróðra hver fyrir.", "Stanza 7"],
    ["Eftirvænting er sá, er sér um fær lof og líknstafi; erfitt er það, er maður eiga skal í annars brjósti.", "Stanza 8"],
    ["Sæll er sá, er sjálfur á lof og vit meðan lifir; því að ill ráð hefur maður oft þegið úr annars brjósti.", "Stanza 9"],
    ["Byrði betri ber-at maður brautu að en sé manvit mikið; auði betra þykir það í ókunnum stað, slíkt er víls vistar.", "Stanza 10"],
    ["Byrði betri ber-at maður brautu að en sé manvit mikið; vegnest verra veit-a hann velli að en sé ofdrykkja öls.", "Stanza 11"],
    ["Er-at svo gott sem góðir kveða öl alda sonum; því að færra veit, er fleira drekkur, síns til geðs gumi.", "Stanza 12"],
    ["Óminnishegri heitir sá er yfir öldrum þrumir, hann stelur geði guma; þess fugls fjöðrum eg fjötraður varð í garði Gunnlaðar.", "Stanza 13"],
    ["Ölvaður eg varð, varð ofölvi að hins fróða Fjalars; því er öl best, að aftur fær hver sína geðsmuni gumi.", "Stanza 14"],
    ["Þögull og hugalt skal þjóðans barn og vígdjarft vera; glaður og reifur skal gumna hver, uns sinn bíður bana.", "Stanza 15"],
    ["Ósnjallur maður hyggst munu ey lifa, ef hann við víg varast; en elli gefur honum engi frið, þótt honum spjót gefi.", "Stanza 16"],
    ["Kópir afglapi, er til kynnis kemur, þylst hann um eða þrumir; allt er sýnt, ef hann sylg um fær, hvílíkt er geð guma.", "Stanza 17"],
    ["Sá einn veit, er víða ratar og hefur fjöld farið, hverju geði stýrir gumna hver; hann er viti vaxinn.", "Stanza 18"],
    ["Haldi-t maður á keri, drekki þó af hófi mjöð, mæli þarft eða þegi; ókynnis þess váar þig engi maður, þótt þú gangir snemma að sofa.", "Stanza 19"],
    ["Gráðugur halur, nema geðs viti, etur sér aldurtregi; oft fær hlægi, er með horskum kemur, manni heimskum magi.", "Stanza 20"],
    ["Hjarðir það vitu, nær þær heim skulu, og ganga þá af grasi; en ósvinnur maður kann ævaagi síns of mál maga.", "Stanza 21"],
    ["Vesall maður og illa skapi hlær að hvívetna; hitt-at hann veit, er hann vita þyrfti, að hann er-at vamma var.", "Stanza 22"],
    ["Ósvinnur maður vakir um allar nætur og hyggur að hvívetna; þá er hann móður, er morgunn kemur, allt er böll svo sem var.", "Stanza 23"],
    ["Ósnotur maður hyggst öllum vera vinur, þeim er við hann hlæja; hitt-at hann finnur, er með snotrum situr, að hann á fár mælendur.", "Stanza 24"],
    ["Ósnotur maður hyggst öllum vera vinur, þeim er við hann hlæja; þá það finnur, er að þingi kemur, að hann á fár formælendur.", "Stanza 25"],
    ["Ósnotur maður þykist allt vita, ef hann á sér í vörum veru; en hitt-at hann veit, hvað hann skal við kveða, ef hann reyna skulu gumar.", "Stanza 26"],
    ["Ósnotur maður, er með aldir kemur, það er best að hann þegi; engi það veit, að hann ekki kann, nema hann mæli of margt. Veit-a maður, sá er ekki veit, nema hann mæli of margt.", "Stanza 27"],
    ["Fróður sá þykist, er fregna kann og segja jafnsaman; ey leyna megu foldinga synir, hvað um líður með lýðum.", "Stanza 28"],
    ["Of mæli mælir, sá er æva þegir, ótíð fárleg orð; hraðmælt tunga, nema haldið sé, oft sér ógott um gelur.", "Stanza 29"],
    ["Að augabragði skal-at mann hafa, þótt til kynnis komi; margur það hyggst, ef hann freginn er-at, að hann þurran hljóti dvelja.", "Stanza 30"],
    ["Fróður þykist, sá er flýr gestsnið, og hagar sér í hvívetna; en sá er hlær við verði, veit-at hann vissulega, hvort hann hlær með óvinum.", "Stanza 31"],
    ["Gumar margir eru glöggskilir, en þó við verði vaskir; það er sýnt, að þeir til snotra koma, ef þeir á fundi fást.", "Stanza 32"],
    ["Árliga verðar skyli maður oft fá, nema til kynnis komi; situr og lopir, lætur sem soltinn sé, og kann fregna að fáu.", "Stanza 33"],
    ["Afglapa er mikið til ills vinar, þótt á brautu búi; en til góðs vinar liggja gagnvegir, þótt hann sé firr farinn.", "Stanza 34"],
    ["Ganga skal, skal-at gestur vera ey í einum stað; ljúfur verður leiður, ef lengi situr annars fletjum á.", "Stanza 35"],
    ["Bú er betra, þótt lítið sé, halur er heima hver; þótt tvær geitur eigi og taugreftan sal, það er þó betra en bæn.", "Stanza 36"],
    ["Bú er betra, þótt lítið sé, halur er heima hver; blóðugt er hjarta, þeim er biðja skal sér í mál hvert matar.", "Stanza 37"],
    ["Vopnum sínum skal-at maður velli á feti ganga framar; því að óvíst er að vita, nær verður á vegum úti geirs of þörf guma.", "Stanza 38"],
    ["Fann eg-at mann svo örvan eða svo matar góðan, að ei væri þiggja þegið, eða síns fjár svo gjöfulan, að leið sé laun, ef þegi.", "Stanza 39"],
    ["Fjár síns, er fengið hefur, skyli-t maður þörf þola; oft sparir leiðum það er ætlaði ljúfum, margt gengur verr en varir.", "Stanza 40"],
    ["Vopnum og váðum skulu vinir gleðjast, það er á sjálfum sýnst; viðurgefendur og endurgefendur verast vinir lengst, ef það bíður að verða vel.", "Stanza 41"],
    ["Vin sínum skal maður vinur vera og gjalda gjöf við gjöf; hlátr við hlátri skyli gumur taka en lausung við lygi.", "Stanza 42"],
    ["Vin sínum skal maður vinur vera, þeim og þess vin; en óvinar síns skyli engi maður vinar vinur vera.", "Stanza 43"],
    ["Veistu, ef þú átt vin, þann er þú vel trúir, og vilt þú af honum gott geta, geði skaltu við hann blanda og gjöfum skipta, fara að finna oft.", "Stanza 44"],
    ["Ef þú átt annan, þann er þú illa trúir, viltu þó af honum gott geta, fagurt skaltu við hann mæla en flátt hyggja og gjalda lausung við lygi.", "Stanza 45"],
    ["Það er enn um þann, er þú illa trúir og þér er grunur að hans geði, hlæja skaltu við honum og um hug mæla; glík skulu gjöld gjöfum.", "Stanza 46"],
    ["Ungr var eg fordum, fór eg einn saman, þá varð eg villur vega; auðigur þóttumst, er eg annan fann, maður er manns gaman.", "Stanza 47"],
    ["Örvar og prúðir munu best lifa, sjaldan sút ala; en ósnjallur maður uggir hvívetna, sýtir æ glöggur við gjöfum.", "Stanza 48"],
    ["Váðir mínar gaf eg velli að tveim trémönnum; rekkar það þóttust, er þeir rift höfðu: skömm er skjaldlausum hal.", "Stanza 49"],
    ["Hrörnar þöll, sú er stendur þorpi á, hlýr-at henni börkur né barr; svo er maður, sá er manngi ann, hvað skal hann lengi lifa?", "Stanza 50"],
    ["Eldi heitari brennur með illum vinum friður fimm daga; en þá slokknar, er hinn sjötti kemur, og versnar allur vinskapur.", "Stanza 51"],
    ["Mikið eitt skal-at manni gefa; oft kaupir sér í litlu lof. Með hálfum hleif og með höllu keri fékk eg mér félaga.", "Stanza 52"],
    ["Lítilla sanda, lítilla sæva, lítil eru geð guma; því að allir menn urðu-t jafnspakir, hálf er öld hvar.", "Stanza 53"],
    ["Meðalsnotur hver skyli maður vera, eyva til snotur; þeim er fyrstur fegurstur að lifa, er vel margt vitu.", "Stanza 54"],
    ["Meðalsnotur hver skyli maður vera, eyva til snotur; því að snoturs manns hjarta verður sjaldan glatt, ef sá er alsnotur, er á.", "Stanza 55"],
    ["Meðalsnotur hver skyli maður vera, eyva til snotur; örlög sín viti engi maður fyrir, þeim er sorgalausastur sefi.", "Stanza 56"],
    ["Brandur af brandi brennur, uns brunninn er, funi kveikist af funa; maður af manni verður að máli kunnur en til dælskur af dul.", "Stanza 57"],
    ["Ár skal rísa, sá er annars vill fé eða fjör hafa; sjaldan liggjandi úlfur lær um getur né sofandi maður sigur.", "Stanza 58"],
    ["Ár skal rísa, sá er á fáa vísa, og ganga síns verka á vit; margt dvelur þann er um morgun sefur, hálfur er auður und hvötum.", "Stanza 59"],
    ["Þurra skíða og þakinna næfra, þess kann maður mjög mál, og þess viðar, er vinnast má misseri og mánuði.", "Stanza 60"],
    ["Þveginn og mettari ríði maður þingi að, þótt sé-at til góðra gerva; skúa og bróka skammist engi maður, né hests in heldur, þótt hann hafi-t góðan.", "Stanza 61"],
    ["Snöktir og gnapir, er til sævar kemur, örn á öldinn má; svo er maður, er með mörgum kemur og á formælendur fáa.", "Stanza 62"],
    ["Fregna og segja skal fróðra hver, sá er vill heitinn horskur; einn vita skaltu, en annar eigi, vitu þrír, ef þjóð veit.", "Stanza 63"],
    ["Ríki sitt skyli ráðsnotra hver í hófi hafa; þá það finnur, er með fræknum kemur, að engi er einna hvatastur.", "Stanza 64"],
    ["Orða þeirra, er maður öðrum segir, oft hann gjöld um fær.", "Stanza 65"],
    ["Mjög til snemma kom eg í marga staði, en til síð í suma; öl var drukkið, sumt var óbruggað: sjaldan hittir leiður í lið.", "Stanza 66"],
    ["Hér og hvar mundi mér heim of boðið, ef eg þyrfti-t að málungi mat, eða tvö læri hengi að hins tryggva vinar, þars eg hafði eitt etið.", "Stanza 67"],
    ["Eldur er bestur með ýta sonum og sólar sýn, heilyndi sitt, ef maður hafa náir, án við löst að lifa.", "Stanza 68"],
    ["Ert-at-tu alls vesall, þótt þú sért illa heill; sumur er af sonum sæll, sumur af frændum, sumur af fé miklu, sumur af verkum vel.", "Stanza 69"],
    ["Betra er lifðum en sé ólifðum, ey getur kvikur kú; eld sá eg brenna auðgum manni fyrir, en úti var dauður fyr durum.", "Stanza 70"],
    ["Haltur ríður hrossi, hjörð rekur handlaus, daufur vegur og dugir; blindur er betri en brenndur sé, nýtur manngi nás.", "Stanza 71"],
    ["Sonur er betri, þótt sé síð of borinn eftir genginn guma; sjaldan bautasteinar standa brautu nær, nema reisi niður að nið.", "Stanza 72"],
    ["Tveir eru eins herjar, tungan er höfuðs bani; er mér í hverri bæn von handar undir hvirfli.", "Stanza 73"],
    ["Nótt verður feginn, sá er nesti trúir, skammar eru skips rár; hverf er haustnótt. Margt um breytist á fimm dögum, en meira á mánuði.", "Stanza 74"],
    ["Veit-a sá, er ekki veit, margur verður af aurum api; maður er auðigur, annar óauðigur, skylit þann vits vita.", "Stanza 75"],
    ["Deyr fé, deyja frændur, deyr sjálfur ið sama; en orðstír deyr aldregi, hveim er sér góðan getur.", "Stanza 76"],
    ["Deyr fé, deyja frændur, deyr sjálfur ið sama; eg veit einn, að aldrei deyr: dómur um dauðan hvern.", "Stanza 77"],
    ["Fullar fletjur sá eg Fitjungs sonum, nú bera þeir völustaf; svo er auður sem augabragð, hann er valtastur vina.", "Stanza 78"],
    ["Ósnotur maður, ef hann getur eignast fé eða fljóts ást, þroskast honum þroski, en vitið aldregi, og gengur hann í ofsa mikinn.", "Stanza 79"],
    ["Það er þá reynt, er þú að rúnum spyrst, þeim er gerðu ginnregin og rístu fimbulþulur; þá hefur hann best, ef hann þegir.", "Stanza 80"],
    ["At kveldi skal dag leyfa, konu er brennd er, mæki er reyndur er, mey er gefin er, ís er yfir kemst, öl er drukkið er.", "Stanza 81"],
    ["Í vindi skal við höggva, á veðri róa, í myrkri við mey tala, mörg eru dags augu; á skip skal skriðar leita, á skjöld til hlífar, mæki til höggva en mey til kossa.", "Stanza 82"],
    ["Við eld skal öl drekka, á ísi skríða, kaupa magran mar en mæki saurgan; heima skal hest feita en hund á búi.", "Stanza 83"],
    ["Meyjar orðum skyli manngi trúa né því er kveður kona, því að á hverfanda hveli voru þeim hjörtu sköpuð, brigð í brjóst um lögð.", "Stanza 84"],
    ["Brestanda boga, brennanda loga, gínanda vargi, gjallanda kráku, rýtanda svíni, rótlausum viði, vaxanda vági, vellanda katli,", "Stanza 85"],
    ["fljúganda fleini, fallanda báru, ísi einnættum, ormi hringlögðum, brúðar beðmálum eða brotnu sverði, bjarnar leiki eða konungs barni,", "Stanza 86"],
    ["sjúkum kálfi, sjálfráða þræli, völvu mæli, val nýfelldum,", "Stanza 87"],
    ["akri ársánum trúi engi maður né til snemma syni; veður ræður akri en vit syni, er-at þeirra hvárt tryggt,", "Stanza 88"],
    ["bróðurbana sínum, þótt á brautu mæti, brennanda húsi, hundi snörpum (þá er vápn til yxna mest): verði-t maður svo tryggur að þessu trúi öllu.", "Stanza 89"],
    ["Svo er friður kvenna, þeirra er flátt hyggja, sem aki jó óbryddum á ísi hálum, teitum tvævetrum og sé tamur illa, eða í bastsnotu í byrlausu skipi, eða skyli haltur henda hrein í þá fannir.", "Stanza 90"],
    ["Bert eg nú mæli, því að eg bæði veit, brigður er karla hugur konum; þá vér fegurst mælum, er vér flást hyggjum: það tælir hveðna hug.", "Stanza 91"],
    ["Fagurt skal mæla og fé bjóða, sá er vill fljóts ást fá, líki leyfa hins ljósa mær: sá fær, er fríar.", "Stanza 92"],
    ["Einstakis ást skyli engi maður annan lasta aldregi; oft fáa hveðna, er hina vísustu fá-at, fegurðar leitir.", "Stanza 93"],
    ["Eyvits lasta skyli eftir annan, það er mörgum manni ber; heimska úr hveðnum gerir hölða sonu sá inn máttki munur.", "Stanza 94"],
    ["Hugur einn það veit, er býr hjarta nær, einn er hann sér of sefa; engi er sótt verri hveim er snotrum manni en sér engu að una.", "Stanza 95"],
    ["Það eg reyndi, er eg í reyri sat og vænti eg míns munar; hold og hjarta var mér in horska mær, þó eg hana ekki hefði.", "Stanza 96"],
    ["Billings mey eg fann á beði í, sólhvíta, sofa; jarls yndi þótti mér ekki vera hjá því líki að lifa.", "Stanza 97"],
    ["'Auk nær aftni skaltu, Óðinn, koma, ef þú vilt þér mæla mey; allt eru ósköp, nema einir viti slíkan löst saman.'", "Stanza 98"],
    ["Aftur eg hvarf og unna þóttumst vísum vilja frá; hitt eg hugða, að eg hafa mundi geð hennar allt og gaman.", "Stanza 99"],
    ["Svo kom eg næst, að in nýta var víðisveit öll vakin; með brennanda ljósum og bornum viði, svo var mér villustígur of vitaður.", "Stanza 100"],
    ["Auk nær morgni, er eg enn kom, þá var saldrótt sofinn; hvepna fann eg þá á beði þeirrar hinnar góðu konu, barna hund bundinn.", "Stanza 101"],
    ["Mörg er góð mær, ef görva kannar, við fífli fláttreguð; það eg þá reyndi, er eg hið ráðsvinna teygða eg flagð á flærðir: háðungar hverrar leitaði hún mér in horska mær, og hafði eg þess vits vit.", "Stanza 102"],
    ["Heima glaður og við gesti reifur, snotur skaltu um þig sjá; minnugur og málugur, ef þú vilt margfróður vera, oft skaltu góðs geta.", "Stanza 103"],
    ["Inn gamla jötun eg sótti, nú em eg aftur kominn; lítið gat eg þar þegjandi. Mörgum orðum mælti eg í minn frama í Suttungs sölum.", "Stanza 104"],
    ["Gunnlöð mér gaf á gullnum stóli drykk hins dýra mjaðar; ill iðgjöld lét eg hana eftir hafa síns hins tryggva hugar, síns hins örðga muna.", "Stanza 105"],
    ["Rata munn lét eg rúms um leita og um grjót gnaga; yfir og undir stóðu mér jötna vegir, svo hætti eg höfði við.", "Stanza 106"],
    ["Vel keyptar litar hef eg vel notið, fás er fróðum vant; því að Óðrerir er nú upp kominn á alda vés jaðar.", "Stanza 107"],
    ["Tvíráð er mér, ef eg væri enn kominn úr jötna görðum, ef eg Gunnlaðar né nyti, þeirrar hinnar góðu konu, er eg lagði arm yfir.", "Stanza 108"],
    ["Hins næsta dags gengu hrímþursar ráðs að spyrja í hávars sal; að Bölverki spurðu þeir, ef hann væri með böndum kominn, eða hefði honum Suttungur of sóað.", "Stanza 109"],
    ["Baugeið Óðinn, hygg eg, að unnið hafi; hvað skal hans tryggðum trúa? Suttung svikinn hann lét sumbli frá og grætta Gunnlöðu.", "Stanza 110"],
    ["Mál er að þylja þular stóli á, Urðarbrunni að; sá eg og þagða eg, sá eg og hugða eg, hlýdda eg á hölða mál.", "Stanza 111"],
    ["Of rúnar heyrða eg dæma, né of ráðum þögðu, Hávahöllu í, Hávahöllu að, heyrða eg segja svo:", "Stanza 112"],
    ["Ráðumst þér, Loddfáfnir, en þú ráð nemir, njóta mundu, ef þú nemur, þér munu góð, ef þú getur: Nótt þú rís-at, nema þú nýsa hveðir, eða þú leitir þér innan út staðar.", "Stanza 113"],
    ["Ráðumst þér, Loddfáfnir, en þú ráð nemir, njóta mundu, ef þú nemur, þér munu góð, ef þú getur: Fjölkunnigri konu skaltu í faðmi sofa, svo að hún lyki þig liðum.", "Stanza 114"],
    ["Hún svo gerir, að þú gáir eigi þings né þjóðans máls; mat þú vilt-at né manna gaman, ferðu syfjaður að sofa.", "Stanza 115"],
    ["Ráðumst þér, Loddfáfnir, en þú ráð nemir, njóta mundu, ef þú nemur, þér munu góð, ef þú getur: Annars konu teygðu þér aldregi eyrarúnu að.", "Stanza 116"],
    ["Ráðumst þér, Loddfáfnir, en þú ráð nemir, njóta mundu, ef þú nemur, þér munu góð, ef þú getur: Á fjalli eða firði, ef þig fara lystir, búst þú að nesti vel.", "Stanza 117"],
    ["Ráðumst þér, Loddfáfnir, en þú ráð nemir, njóta mundu, ef þú nemur, þér munu góð, ef þú getur: Illan mann láttu aldregi óhöpp þín vita; því að af illum manni fær þú aldregi endurgjöld hins góða hugar.", "Stanza 118"],
    ["Ofviða eg sá manni orð til sköðu ills konu; fláráð tunga varð honum að fjörlagi, og þeygi um sanna sök.", "Stanza 119"],
    ["Ráðumst þér, Loddfáfnir, en þú ráð nemir, njóta mundu, ef þú nemur, þér munu góð, ef þú getur: Veistu, ef þú átt vin, þann er þú vel trúir, farðu að finna oft; því að hrísi vex og háu grasi vegur, er vættki treður.", "Stanza 120"],
    ["Ráðumst þér, Loddfáfnir, en þú ráð nemir, njóta mundu, ef þú nemur, þér munu góð, ef þú getur: Góðan mann teygðu þér að gamanrúnunum og lærðu líknargaldra.", "Stanza 121"],
    ["Ráðumst þér, Loddfáfnir, en þú ráð nemir, njóta mundu, ef þú nemur, þér munu góð, ef þú getur: Vertu aldregi fyrri að slíta vináttu við vin þinn; sorg etur hjarta, ef þú segja né náir einhverjum allan þinn hug.", "Stanza 122"],
    ["Ráðumst þér, Loddfáfnir, en þú ráð nemir, njóta mundu, ef þú nemur, þér munu góð, ef þú getur: Orðum skipta þú skalt aldregi við ósvinna apa.", "Stanza 123"],
    ["Því að af illum manni fær þú aldregi góðs endurgjöld; en góður maður mun þig gera dýrkan með lofstír.", "Stanza 124"],
    ["Sifjum er þá blandat, er maður segja ræður einhverjum allan sinn hug; allt er betra en sé brigðum að vera, er-at sá vinur, er vilt eitt mælir.", "Stanza 125"],
    ["Ráðumst þér, Loddfáfnir, en þú ráð nemir, njóta mundu, ef þú nemur, þér munu góð, ef þú getur: Þremur orðum senn skaltu-t við verra mann deila; oft hinn betri bilar, er hinn verri vegur.", "Stanza 126"],
    ["Ráðumst þér, Loddfáfnir, en þú ráð nemir, njóta mundu, ef þú nemur, þér munu góð, ef þú getur: Skósmiður þú veri né skaftsmiður, nema þú sjálfum þér sér; ef skór er skakkur eða skaft sé rangt, þá er þér böls beðið.", "Stanza 127"],
    ["Ráðumst þér, Loddfáfnir, en þú ráð nemir, njóta mundu, ef þú nemur, þér munu góð, ef þú getur: Hvar er þú böl kynnir, segðu þér bölvi að og gef-at þínum óvinum frið.", "Stanza 128"],
    ["Ráðumst þér, Loddfáfnir, en þú ráð nemir, njóta mundu, ef þú nemur, þér munu góð, ef þú getur: Illu fagna þú aldregi en lát þér að góðu getið.", "Stanza 129"],
    ["Ráðumst þér, Loddfáfnir, en þú ráð nemir, njóta mundu, ef þú nemur, þér munu góð, ef þú getur: Upp skaltu-t líta í orrustu (gjalti verða gumna synir), síður þig um heilli gumar.", "Stanza 130"],
    ["Ráðumst þér, Loddfáfnir, en þú ráð nemir, njóta mundu, ef þú nemur, þér munu góð, ef þú getur: Ef þú vilt þér góða konu að gamanrúnun mæla og fá fögnuð af, fögru skaltu heita og láta fast vera; leiðist engi gott, ef getur.", "Stanza 131"],
    ["Ráðumst þér, Loddfáfnir, en þú ráð nemir, njóta mundu, ef þú nemur, þér munu góð, ef þú getur: Var þig bið eg, en sé-at vandan var, varstu við öl mest og við annars konu.", "Stanza 132"],
    ["Ráðumst þér, Loddfáfnir, en þú ráð nemir, njóta mundu, ef þú nemur, þér munu góð, ef þú getur: Að háði né hlátri hafðu aldregi gest né ganganda.", "Stanza 133"],
    ["Oft vitu ógjörla, þeir er inni sitja, hvers þeir eru kyns, er koma; er-at maður svo góður, að galli né fylgi, né svo illur, að einugi dugi.", "Stanza 134"],
    ["At háði né hlátri hafðu aldregi háran þul; oft er gott, það er gamlir kveða. Oft úr skörpum belg skilin orð koma.", "Stanza 135"],
    ["Ráðumst þér, Loddfáfnir, en þú ráð nemir, njóta mundu, ef þú nemur, þér munu góð, ef þú getur: Gest þú né geyja né á grind hrindir, gættu vamma vörum.", "Stanza 136"],
    ["Rammt er það tré, er ríða skal öllum í opna gátt; baug þú gef, eða þér biðja mun hvers böls á liðu.", "Stanza 137"],
    ["Veit eg, að eg hékk vindga meiði á níu nýttur allar, geiri undaður og gefinn Óðni, sjálfur sjálfum mér.", "Stanza 138"],
    ["Á þeim meiði, er manngi veit, hvers hann af rótum rennur.", "Stanza 139"],
    ["Við hleifi mig sældu né við hornigi; nýsta eg niður, nam eg upp rúnar, æpandi nam, féll eg aftur þaðan.", "Stanza 140"],
    ["Þá nam eg frævast og fróður vera og vaxa og vel hafna; orð mér af orði orðs leitaði, verk mér af verki verks leitaði.", "Stanza 141"],
    ["Rúnar munt þú finna og ráðna stafi, mjög stóra stafi, mjög stinna stafi, er fáði fimbulþulur og gerðu ginnregin og reist Hroptur rögna.", "Stanza 142"],
    ["Óðinn með ásum, en fyrir alfum Dáinn, Dvalinn dvergum fyrir, Ásvinnur jötnum fyrir, eg reist sjálfur sumar.", "Stanza 143"],
    ["Veistu hve rísta skal? Veistu hve ráða skal? Veistu hve fá skal? Veistu hve freista skal? Veistu hve biðja skal? Veistu hve blóta skal? Veistu hve senda skal? Veistu hve sóa skal?", "Stanza 144"],
    ["Betra er óbeðið en sé ofblótið, ey sér til gildis gjöf; betra er ósent en sé ofsóað. Svo Þundur reist fyrir þjóða rök, þar hann upp um reis, er hann aftur kom.", "Stanza 145"],
    ["Ljóð eg þau kann, er kann-at þjóðans kona og mannskis mögur. 'Hjálp' heitir eitt, en það þér hjálpa mun við sökum og sútum og harðréttum hverjum.", "Stanza 146"],
    ["Það kann eg annað, er þurfa ýta synir, þeir er vilja læknar lifa.", "Stanza 147"],
    ["Það kann eg þriðja: ef mér verður þörf mikil hafta við mína heiftmögur, eggjar eg deyfi minna andskota, bíta-t þeim vápn né velir.", "Stanza 148"],
    ["Það kann eg fjórða: ef mér fyrðar leggja höft að hamslitum, svo eg gel, að eg ganga má, spyrna löstir af fótum en fjötur af höndum.", "Stanza 149"],
    ["Það kann eg fimmta: ef eg sé af fári skotinn flein í þjóðliði, flýgur-at hann svo stinnt, að eg stöðvig-a-k, ef eg hann sjónum of fæ.", "Stanza 150"],
    ["Það kann eg sjötta: ef mig særir þegn á rótum rásviðar, og þann hal, er mig heifta kveður, þann etur mein en mig ekki.", "Stanza 151"],
    ["Það kann eg sjöunda: ef eg sé háan halla brenna um bekkjunum, brennur-at svo breitt, að eg bjargig-a-k, þann kann eg galdur að gala.", "Stanza 152"],
    ["Það kann eg sjöunda: ef eg sé háan hita loga um bekkisveitum, brennur-at svo breitt, að eg honum bjargi-t, þann kann eg galdur að gala.", "Stanza 152"],
    ["Það kann eg áttunda, er öllum er nytsamlegt að nema: hvar er hatur vex með hildings sonum, það má eg bæta brátt.", "Stanza 153"],
    ["Það kann eg níunda: ef mig nauður um stendur að bjarga fari mínu á floti, vind eg kyrri á vogum og svæfi eg allan sæ.", "Stanza 154"],
    ["Það kann eg tíunda: ef eg sé túnriður leika lofti á, eg svo vinn, að þær villar fara sinna heim huga, sinna heim hama.", "Stanza 155"],
    ["Það kann eg ellefta: ef eg skal til orrustu leiða langvini, undir randir eg gala, en þeir með ríki fara heilir hildar til, heilir hildi frá, koma þeir heilir hvaðan.", "Stanza 156"],
    ["Það kann eg tólfta: ef eg sé á tré uppi vofa virgilná, svo eg ríst og í rúnum fá, að sá gengur gumi og mælir við mig.", "Stanza 157"],
    ["Það kann eg þrettánda: ef eg skal þegn ungan vatni ausa, mun-at hann falla, þótt hann í fólk komi, hnígur-at sá halur fyrir hjörum.", "Stanza 158"],
    ["Það kann eg fjórtánda: ef eg skal fyrða liði telja goð fyrir gumum, ása og alfa eg kann allra skil, fár kann ósnotur svo.", "Stanza 159"],
    ["Það kann eg fimmtánda, er gól Þjóðreyrir dvergur fyr Dellings durum: afl gól hann ásum, en alfum frama, hyggju Hroptatý.", "Stanza 160"],
    ["Það kann eg sextánda: ef eg vil hins svinna manns hafa geð allt og gaman, hugi eg hverfi hvítarmri konu og sný eg öllum hennar sefa.", "Stanza 161"],
    ["Það kann eg sjöunda tugta: að mig mun seint firrast hið unga fljóð; ljóða þessara mun þú, Loddfáfnir, lengi vanta.", "Stanza 162"],
    ["Það kann eg átjánda, er eg æva kenni mey né manns konu, - allt er betra, er einn um veit, það fylgir ljóða lokum, - nema þeirri einni, er mig armi ver, eða mín systir sé.", "Stanza 163"],
    ["Nú eru Hávamál kveðin Hávahöllu í, allþörf ýta sonum, óþörf jötna sonum. Heill, sá er kvað! Heill, sá er kann! Njóti, sá er nam! Heilir, þeir er hlýddu!", "Stanza 164"]
];