export const norse = [
    ["Gáttir allar, áðr gangi fram, um skoðast skyli, um skyggnast skyli, því at óvíst er at vita, hvar óvinir sitja á fleti fyrir.", "Stanza 1"],
    ["Gefendr heilir! Gestr er inn kominn, hvar skal sitja sjá? Mjök er bráðr, sá er á bröndum skal síns of freista frama.", "Stanza 2"],
    ["Elds er þörf, þeim er inn er kominn ok á kné kalsinn; matar ok váða er manni þörf, þeim er hefir um fjall farið.", "Stanza 3"],
    ["Vatns er þörf, þeim er til verðar kemr, þerru ok þjóðlaðar, góðs of æðis, ef sér geta mætti, orðs ok endurþögu.", "Stanza 4"],
    ["Vits er þörf, þeim er víða ratar; dælt er heima hvat; at augabragði verðr, sá er ekki kann ok með snotrum sitr.", "Stanza 5"],
    ["At hyggjandi sinni skylit maðr hræsinn vera, heldr gætinn at geði; þá er horskr ok þögull kemr heimisgarða til, sjaldan verðr víti vörum, því at óbrigðra vin fær maðr aldregi en mannvit mikit.", "Stanza 6"],
    ["Enn vari gestr, er til verðar kemr, þunnu hljóði þegir, eyrum hlýðir, en augum skoðar; svá nýsist fróðra hverr fyrir.", "Stanza 7"],
    ["Eftir nýtist, sá er sér fær lof ok líknstafi; óvissara er þat, er maðr eiga skal annars brjóstum í.", "Stanza 8"],
    ["Sá er sæll, er sjálfr of á lof ok vit, meðan lifir; því at ill ráð hefir maðr oft þegið úr annars brjóstum.", "Stanza 9"],
    ["Byrði betri berr-at maðr brautu at en mannvit mikit; auði betra þykir þat í ókunnum stað, slíkt er válaðs vera.", "Stanza 10"],
    ["Byrði betri berr-at maðr brautu at en mannvit mikit; vegnest verra vegr-at hann velli at en sé ofdrykkja öls.", "Stanza 11"],
    ["Er-at svá gott, sem gott kveða, öl alda sonum, því at færa veit, er fleira drekkr, síns til geðs gumi.", "Stanza 12"],
    ["Óminnishegri heitir sá er yfir ölðrum þrumir, hann stelr geði guma; þess fugls fjöðrum ek fjötraðr vark í garði Gunnlöðar.", "Stanza 13"],
    ["Ölr ek varð, varð ofrölvi at ins fróða Fjalars; því er ölðr bazt, at aftr of heimtir hverr sitt geð gumi.", "Stanza 14"],
    ["Þagalt ok hugalt skyli þjóðans barn ok vígstjarft vera; glaðr ok reifr skyli gumna hverr, unz sinn bíðr bana.", "Stanza 15"],
    ["Ósnjallr maðr hyggst munu ey lifa, ef hann við víg varast; en elli gefr honum engi frið, þótt honum geirar gefi.", "Stanza 16"],
    ["Kópir afglapi, er til kynnis kemr, þylst hann um eða þrumir; allt er senn, ef hann sylg um getr, uppi er þá geð guma.", "Stanza 17"],
    ["Sá einn veit, er víða ratar ok hefir fjölð of farið, hverju geði stýrir gumna hverr, sá er vitandi er vits.", "Stanza 18"],
    ["Haldi-t maðr á keri, drekki þó af hófi mjöð, mæli þarft eða þegi; ókynnis þess vár þig engi maðr, at þú gangir snemma at sofa.", "Stanza 19"],
    ["Gráðugr halr, nema geðs viti, etr sér aldrtregi; oft fær hlægi, er með horskum kemr, manni heimskum magi.", "Stanza 20"],
    ["Hjarðir þat vitu, nær þær heim skulu, ok ganga þá af grasi; en ósviðr maðr kann ævagi síns of mál maga.", "Stanza 21"],
    ["Vesall maðr ok illa skapi hlær at hvívetna; hitt-at hann veit, er hann vita þyrfti, at hann er-at vamma lauss.", "Stanza 22"],
    ["Ósviðr maðr vakir um allar nætr ok hyggr at hvívetna; þá er móðr, er morgunn kemr, allt er víl sem var.", "Stanza 23"],
    ["Ósnotr maðr hyggr sér alla vera vini, þá er við hann hlæja; hitt-at hann finnr, er með snotrum sitr, at hann á fáa formælendr.", "Stanza 24"],
    ["Ósnotr maðr hyggr sér alla vera vini, þá er við hann hlæja; þá þat finnr, er at þingi kemr, at hann á fáa formælendr.", "Stanza 25"],
    ["Ósnotr maðr þykist allt vita, ef hann á sér í vöri vrögl; en þat hann niðat veit, hvat hann skal við kveða, ef hans freista firar.", "Stanza 26"],
    ["Ósnotr maðr, er með aldir kemr, þat er bazt, at hann þegi; engi þat veit, at hann ekki kann, nema hann mæli til margt; veit-at maðr, hinn er vætki veit, þótt hann mæli til margt.", "Stanza 27"],
    ["Fróðr þykist, sá er fregna kann ok segja jafnsaman; eyvitu leyna megu ýta synir, því er gengr um guma.", "Stanza 28"],
    ["Ósnotr maðr mælir margt um þat, er til máls kemr; oft in hraðmælta tunga, nema haldræði eigi, sér ógagn mælir.", "Stanza 29"],
    ["At augabragði skal-at maðr annan hafa, þótt til kynnis komi; margr þat hyggr, ef hann freginn er-at, at hann þurrfjallr þrumi.", "Stanza 30"],
    ["Fróðr þykist, sá er flýr á braut gestr at gest hæðinn; veit-at görla, sá er of verði glissir, þótt hann með grönum geyji.", "Stanza 31"],
    ["Gumnar margir eru gisholdnir, en þó við sökumast; aldar róg þat mun æ vera, órir gestr við gest.", "Stanza 32"],
    ["Árliga verðar skyli maðr oft fáa, nema til kynnis komi; sitr ok nýpir, lætr sem soltinn sé, ok kann fregna at fáu.", "Stanza 33"],
    ["Afhvarf mikit er til ills vinar, þótt á brautu búi; en til góðs vinar liggja gagnvegir, þótt hann sé firr farinn.", "Stanza 34"],
    ["Ganga skal, skal-at gestr vera ey í einum stað; ljúfr verðr leiðr, ef lengi sitr annars fletjum á.", "Stanza 35"],
    ["Bú er betra, þótt lítið sé, halr er heima hver; þótt tvær geitr eigi ok taugreftan sal, þat er þó betra en bæn.", "Stanza 36"],
    ["Bú er betra, þótt lítið sé, halr er heima hver; blóðugt er hjarta, þeim er biðja skal sér í mál hvert matar.", "Stanza 37"],
    ["Vápnum sínum skal-at maðr velli á feti ganga framar; því at óvíst er at vita, nær verðr á vegum úti geirs of þörf guma.", "Stanza 38"],
    ["Fann-at ek mildan mann eða svá matar góðan, at-at væri þiggja þægt, eða síns fjár svá gjöflan guma, at leið sé laun, ef þegi.", "Stanza 39"],
    ["Fjár síns, er fengit hefir, skyli-t maðr þörf þola; oft sparir leiðum þat er lífum ætlaði, margt gengr verr en varir.", "Stanza 40"],
    ["Vápnum ok váðum skulu vinir gleðjast, þat er á sjálfum sýnst; viðrgefendr ok endurgefendr eru vinir lengst, ef þat bíðr at verða vel.", "Stanza 41"],
    ["Vin sínum skal maðr vinur vera ok gjalda gjöf við gjöf; hlátr við hlátri skyli hölðar taka en lausung við lygi.", "Stanza 42"],
    ["Vin sínum skal maðr vinur vera, þeim ok þess vin; en óvinar síns skyli engi maðr vinar vinur vera.", "Stanza 43"],
    ["Veiztu, ef þú átt vin, þann er þú vel trúir, ok vilt þú af honum gott geta, geði skaltu við hann blanda ok gjöfum skipta, fara at finna oft.", "Stanza 44"],
    ["Ef þú átt annan, þann er þú illa trúir, vildu þó af honum gott geta, fagurt skaltu við hann mæla en flátt hyggja ok gjalda lausung við lygi.", "Stanza 45"],
    ["Það er enn of þann, er þú illa trúir ok þér er grunur at hans geði, hlæja skaltu við honum ok um hug mæla; glík skulu gjöld gjöfum.", "Stanza 46"],
    ["Ungr var ek fordum, fór ek einn saman, þá varð ek villr vega; auðigr þóttumst, er ek annan fann, maðr er manns gaman.", "Stanza 47"],
    ["Hafendr ok hvatir gumar bazt lifa, sjaldan sút ala; en ósnjallr maðr uggir hotvetna, sýtir æ glöggur við gjöfum.", "Stanza 48"],
    ["Váðir mínar gaf ek velli að tveim trémönnum; rekkar þat þóttust, er þeir rifjuðust; skömm er nökviðr halr.", "Stanza 49"],
    ["Hrörnar þöll, sú er stendr þorpi á, hlýrat henni börkr né barr; svá er maðr, sá er manngi ann, hvat skal hann lengi lifa?", "Stanza 50"],
    ["Eldi heitari brennr með illum vinum friðr fimm daga; en þá sloknar, er inn sétti kemr, ok versnar allr vinskapr.", "Stanza 51"],
    ["Mikit eitt skal-at manni gefa, oft kaupir sér í litlu lof; með hálfum hleif ok með höllu keri fekk ek mér félaga.", "Stanza 52"],
    ["Lítilla sanda, lítilla sæva, lítil eru geð guma; því at allir menn urðu-t jafnspakir, hálf er öld hvar.", "Stanza 53"],
    ["Meðalsnotr skyli manna hverr, æva til snotr sé; þeim er fyrstur fegrst að lifa, er vel margt vitu.", "Stanza 54"],
    ["Meðalsnotr skyli manna hverr, æva til snotr sé; því at snoturs manns hjarta verðr sjaldan glatt, ef sá er alsnotr, er á.", "Stanza 55"],
    ["Meðalsnotr skyli manna hverr, æva til snotr sé; örlög sín viti engi fyrir, þeim er sorgalausastur sefi.", "Stanza 56"],
    ["Brandr af brandi brennr, unz brunninn er, funi kveikist af fana; maðr af manni verðr at máli kuðr, en til dælskur af dul.", "Stanza 57"],
    ["Ár skal rísa, sá er annars vill fé eða fjör hafa; sjaldan liggjandi úlfur lær um getr né sofandi maðr sigur.", "Stanza 58"],
    ["Ár skal rísa, sá er á fáa verki, ok ganga síns verka á vit; margt dvelr þann er um morgun sefr, hálfur er auðr und hvötum.", "Stanza 59"],
    ["Þurra skíða ok þakinna næfra, þess kann maðr mjöglaust mál, ok þess viðar, er vinnast má til málungs ok misseris.", "Stanza 60"],
    ["Þveginn ok mettr ríði maðr þingi at, þótt sé-t væddr til vel; skúa ok bróka skammist engi maðr, né hests in heldr, þótt hann hafi-t góðan.", "Stanza 61"],
    ["Snapir ok gnapir, er til sævar kemr, örn á öldinn sjá; svá er maðr, er með mörgum kemr ok á formælendr fáa.", "Stanza 62"],
    ["Fregna ok segja skal hverr fróðr vera, sá er vill heitinn horskr; einn vita skal, en annarr eigi, þjóð veit, ef þrír eru.", "Stanza 63"],
    ["Ríki sitt skyli ráðsnotra hverr í hófi hafa; þá þat finnr, er með fræknum kemr, at engi er einna hvatastr.", "Stanza 64"],
    ["Orða þeirra, er maðr öðrum segir, oft hann gjöld of getr.", "Stanza 65"],
    ["Mjök til snemma kom ek í marga staði, en til síð í suma; öl var drukkit, sumt var ólagat, sjaldan hittir leiðr í lið.", "Stanza 66"],
    ["Hér ok hvar mundi mér heim of boðit, ef þyrftig-at at málungi mat, eða tvær læri hengi at ins tryggva vinar, þars ek hafða eitt etit.", "Stanza 67"],
    ["Eldr er beztr með ýta sonum ok sólar sýn, heilyndi sitt, ef maðr hafa náir, án við löst at lifa.", "Stanza 68"],
    ["Er-at maðr alls vesall, þótt hann sé illa heill; sumr er af sonum sæll, sumr af frændum, sumr af fé örnu, sumr af verkum vel.", "Stanza 69"],
    ["Betra er lifðum en sé ólifðum, ey getr kvikr kú; eld sá ek upp brenna auðgum manni fyrir, en úti var dauðr fyr durum.", "Stanza 70"],
    ["Haltr ríðr hrossi, hjörð rekr handar vanr, daufr vegr ok dugir; blindr er betri en brenndur sé, nýtir engi mann dauðan.", "Stanza 71"],
    ["Sonr er betri, þótt sé síð of alin eftir genginn guma; sjaldan bautarsteinar standa brautu nær, nema reisi niðr at nið.", "Stanza 72"],
    ["Tveir eru eins herjar, tunga er höfuðs bani; er mér í héðin hvern handar væni.", "Stanza 73"],
    ["Nótt verðr feginn, sá er nesti trúir, skammt eru skips rár; hverf er haustgríma; mörg um skiptist á fimm dögum veðr, en meira á mánuði.", "Stanza 74"],
    ["Veit-at sá, er vætki veit, margr verðr af aurum api; maðr er auðigr, annarr óauðigr, skylit þann vamma vá.", "Stanza 75"],
    ["Deyr fé, deyja frændr, deyr sjálfur it sama; en orðstírr deyr aldregi, hveim er sér góðan getr.", "Stanza 76"],
    ["Deyr fé, deyja frændr, deyr sjálfur it sama; ek veit einn, at aldrei deyr: dómr of dauðan hvern.", "Stanza 77"],
    ["Fullar grindur sá ek fyr Fjörungs sonum, nú bera þeir völstaf; svá er auðr sem augabragð, hann er valtastur vina.", "Stanza 78"],
    ["Ósnotr maðr, ef hann eignast getr fé eða fljóðs munu, metnaðr honum þróast, en mannvit aldregi, fram gengr hann drjúgt í dul.", "Stanza 79"],
    ["Þat er þá reynt, er þú að rúnum spyrr, inum reginkunnum, þeim er gerðu ginnregin ok fáði fimbulþulr; þá hefir hann bazt, ef hann þegir.", "Stanza 80"],
    ["At kveldi skal dag leyfa, konu er brennd er, mæki er reyndur er, mey er gefin er, ís er yfir kemur, öl er drukkið er.", "Stanza 81"],
    ["Í vindi skal við höggva, í veðri á sjó róa, í myrkri við mær tala, mörg eru dags augu; á skip skal skriðar leita, á skjöld til hlífar, mæki höggs, en mey kossa.", "Stanza 82"],
    ["Við eld skal öl drekka, en á ísi skríða, magran hest kaupa, en mæki saurgan, heima hest feita, en hund á búi.", "Stanza 83"],
    ["Meyjar orðum skyli manngi trúa, né því er kveður kona, því að á hverfanda hveli voru þeim hjörtu sköpuð, brigð í brjóst um lagið.", "Stanza 84"],
    ["Brestanda boga, brennanda loga, gínanda úlfi, gjallanda kráku, rýtanda svíni, rótlausum viði, vaxanda vági, vellanda katli,", "Stanza 85"],
    ["Fljúganda fleini, fallandi báru, ísi einnættum, ormi hringlegnum, brúðar beðmálum eða brotnu sverði, bjarnar leiki eða barni konungs,", "Stanza 86"],
    ["Sjúkum kálfi, sjálfráða þræli, völu vilmæli, val nýfelldum.", "Stanza 87"],
    ["Akri ársánum trúi engi maðr, né til snemma syni, veðr ræður akri, en vit syni, þess er hvortveggja hvasst.", "Stanza 88"],
    ["Bróðurbana sínum, þótt á brautu mæti, húsi hálfbrunnu, hesti alskjótum, þá er jór ónýtur, ef einn fótur brotnar; verði-t maðr svo tryggur, að þessu öllu trúi.", "Stanza 89"],
    ["Svo er friðr kvenna, þeirra er flátt hyggja, sem aki jó óbryddum á ísi hálum, teitum, tvévetrum, og sé taminn illa, eða í hvössum byr beiti stýrilausu, eða skyli haltur hendast í skriðu brattri.", "Stanza 90"],
    ["Bergtala ek nú, því að ek bæði veit, bráð er karls hugur við konur; þá vér fegrst mælum, er vér flást hyggjum, þat tælir horska hugi.", "Stanza 91"],
    ["Fagurt skal mæla ok fé bjóða, sá er vill fljóðs ást fá, líki leyfa ins ljósa mær, sá fær, er fríar.", "Stanza 92"],
    ["Ástar sakir skyli engi maðr annan aldregi telja; oft fá snotran, er ósviðan fá-at, lostfagrir litir.", "Stanza 93"],
    ["Eyvitar losti skyli eftir annan telja, þess er mörgum manni mætir; heimska ór horskum gerir hölða sonu sá inn máttki munr.", "Stanza 94"],
    ["Hugr einn þat veit, er býr hjarta nær, einn er hann um sína sefa; engi er sjúkdómur verri hveim vísindamanni en við engu að una.", "Stanza 95"],
    ["Þat ek þá reynda, er ek í reyri sat ok beið ek míns munar; hold ok hjarta var mér in horska mær, þó eg hana alla-t gætag.", "Stanza 96"],
    ["Billings mey ek fann beðjum á, sólhvíta sofa; jarls yndi þótti mér ekki vera við þat líkama að lifa.", "Stanza 97"],
    ["Auk nær kveldi skaltu, Óðinn, koma, ef þú vilt mæla mey; allt eru ósköp, nema einir viti slíkan löst saman.", "Stanza 98"],
    ["Aftr ek hvarf ok unna þóttumst vísum vilja frá; hitt ek hugða, að ek hafa mundi geð hennar allt ok gaman.", "Stanza 99"],
    ["Svo kom ek næst, að in snjalla var úti öll herið vakin, með brennandum ljósum ok bornum viði, svo var mér vílshatar vegur ætlaður.", "Stanza 100"],
    ["Ok nær morgni, er ek var enn kominn, þá var saldrótt sofinn; hund fann ek þá þeirrar innar góðu konu bundinn beðjum á.", "Stanza 101"],
    ["Mörg er góð mær, ef görva kannar, við hölða hugbrigð; þat ek þá reynda, er ek it ráðspaka teygða ek á flærðir fljóð; háðungar hverrar leitaði in horska mær, ok hafða ek þess vettugi víls.", "Stanza 102"],
    ["Heima glaðr gumi ok við gesti reifr, sviðr skal um sig vera, minnigr ok málugr, ef hann vill margfróðr vera, oft skal góðs geta; fimbulfambi heitir sá er fátt kann segja, þat er ósnoturs aðal.", "Stanza 103"],
    ["Inn forna jötun ek sótta, nú em ek aftr kominn, lítt þar þagðig um; mörgum orðum mælta ek í minn frama í Suttungs sölum.", "Stanza 104"],
    ["Gunnlöð mér gaf gullnum stóli á drykk ins dýra mjaðar; ill iðgjöld lét ek hana eftir hafa síns ins heila hugar, síns ins svára sefa.", "Stanza 105"],
    ["Rata munn lét ek rúms um leita ok um grjót gnaga; yfir ok undir stóðu mér jötna vegir, svo hætta ek höfði til.", "Stanza 106"],
    ["Vel keyptar litar ek hafa vel notið, fás er fróðum vant; því at Óðrerir er nú upp kominn á alda vés jörð.", "Stanza 107"],
    ["Ifi er mér á, at ek væra enn kominn út úr jötna görðum, ef ek Gunnlaðar né nyti, innar góðu konu, þeirrar er lögðu ek arm yfir.", "Stanza 108"],
    ["Ins hindra dags gengu hrímþursar ráðs at fregna í hávars sal; at Bölverki þeir spurðu, ef hann væri með böndum kominn eða hefði honum Suttungr of sóað.", "Stanza 109"],
    ["Baugseið Óðinn, hygg ek, at unnið hafi; hvat skal hans tryggðum trúa? Suttung svikinn hann lét sumbli frá ok grætta Gunnlöðu.", "Stanza 110"],
    ["Mál er at þylja þular stóli á, Urðarbrunni at; sá ek ok þagðak, sá ek ok hugðak, hlýdda ek á hölða mál; of rúnar heyrða ek dæma, né of ráðum þögðu Háva höllu í, Háva höllu at, heyrða ek segja svo:", "Stanza 111"],
    ["Ráðumk þér, Loddfáfnir, at þú ráð nemir, - njóta mundu, ef þú nemr, þér munu góð, ef þú getr -: nótt þú rísat, nema þú nýsnir sér eða þú leitir þér innan út staðar.", "Stanza 112"],
    ["Ráðumk þér, Loddfáfnir, at þú ráð nemir, - njóta mundu, ef þú nemr, þér munu góð, ef þú getr -: fjölkunnigri konu skaltu í faðmi sofa, svo at hon lyki þig liðum.", "Stanza 113"],
    ["Hon svá gerir, at þú gáir eigi þings né þjóðans máls; mat þú villat né manna gaman, ferr þú sorgafullr at sofa.", "Stanza 114"],
    ["Ráðumk þér, Loddfáfnir, at þú ráð nemir, - njóta mundu, ef þú nemr, þér munu góð, ef þú getr -: annars konu teygðu þér aldregi eyrarúnu at.", "Stanza 115"],
    ["Ráðumk þér, Loddfáfnir, at þú ráð nemir, - njóta mundu, ef þú nemr, þér munu góð, ef þú getr -: á fjalli eða firði, ef þig fýsir at fara, fástu at virði vel.", "Stanza 116"],
    ["Ráðumk þér, Loddfáfnir, at þú ráð nemir, - njóta mundu, ef þú nemr, þér munu góð, ef þú getr -: illan mann láttu aldregi óhöpp þín vita, því at af illum manni fær þú aldregi gjöld fyrir góðan hug.", "Stanza 117"],
    ["Ofarla ek sá orðum bitinn hölðs ins illa manns; tunga ins fjölvísa varð honum at bana, ok þeygi of sanna sök.", "Stanza 118"],
    ["Ráðumk þér, Loddfáfnir, at þú ráð nemir, - njóta mundu, ef þú nemr, þér munu góð, ef þú getr -: veiztu, ef þú átt vin, þann er þú vel trúir, farðu at finna oft; því at hrísi vex ok hávu grasi vegur, er vætki treðr.", "Stanza 119"],
    ["Ráðumk þér, Loddfáfnir, at þú ráð nemir, - njóta mundu, ef þú nemr, þér munu góð, ef þú getr -: góðan mann teygðu þér at gamanrúnum ok nem líknargaldra, meðan þú lifir.", "Stanza 120"],
    ["Ráðumk þér, Loddfáfnir, at þú ráð nemir, - njóta mundu, ef þú nemr, þér munu góð, ef þú getr -: vin þínum ver þú aldregi fyrri at slíta flokksbragði; sorg etr hjarta, ef þú segja ne náir einhverjum allan hug.", "Stanza 121"],
    ["Ráðumk þér, Loddfáfnir, at þú ráð nemir, - njóta mundu, ef þú nemr, þér munu góð, ef þú getr -: orðum skipta þú skalt aldregi við ósvinna apa.", "Stanza 122"],
    ["Því at af illum manni fær þú aldregi góðs laun fyrir; en góðr maðr mun þig gera líknfastan lofi eftir.", "Stanza 123"],
    ["Sifjum er þá blandat, er segja ræðr einhverjum allan hug; allt er betra en sé brigðum at vera; er-at sá vinr, er vilt eitt segir.", "Stanza 124"],
    ["Ráðumk þér, Loddfáfnir, at þú ráð nemir, - njóta mundu, ef þú nemr, þér munu góð, ef þú getr -: þrjú orð eigi skaltu við verra mann deila; oft inn betri bilar, þá er inn verri vegr.", "Stanza 125"],
    ["Ráðumk þér, Loddfáfnir, at þú ráð nemir, - njóta mundu, ef þú nemr, þér munu góð, ef þú getr -: skósmiðr þú ver þér né skaftsmiðr, nema þú sjálfum þér sér; skór sé illa skapaðr eða skaft sé rangt, þá er þér böls beðit.", "Stanza 126"],
    ["Ráðumk þér, Loddfáfnir, at þú ráð nemir, - njóta mundu, ef þú nemr, þér munu góð, ef þú getr -: hvar er þú böl vísir, segðu þér bölvi at ok gef-at þínum óvinum frið.", "Stanza 127"],
    ["Ráðumk þér, Loddfáfnir, at þú ráð nemir, - njóta mundu, ef þú nemr, þér munu góð, ef þú getr -: illu feginn verðu þú aldregi, en lát þér at góðu getið.", "Stanza 128"],
    ["Ráðumk þér, Loddfáfnir, at þú ráð nemir, - njóta mundu, ef þú nemr, þér munu góð, ef þú getr -: upp líta þú skaltat í orustu, - gjalti glíkir verða gumna synir - síðr þitt of heilli halir.", "Stanza 129"],
    ["Ráðumk þér, Loddfáfnir, at þú ráð nemir, - njóta mundu, ef þú nemr, þér munu góð, ef þú getr -: ef þú vilt þér góða konu at gamanrúnum fá ok fagna af feginsmálum, fögru skaltu heita ok láta fast vera; leiðist manngi gott, ef getr.", "Stanza 130"],
    ["Ráðumk þér, Loddfáfnir, at þú ráð nemir, - njóta mundu, ef þú nemr, þér munu góð, ef þú getr -: varan bið ek þig vera, en eigi ofvaran; ver þú við öl varastr ok við annars konu ok við þat it þriðja, at þig þjófar né leiki.", "Stanza 131"],
    ["Ráðumk þér, Loddfáfnir, at þú ráð nemir, - njóta mundu, ef þú nemr, þér munu góð, ef þú getr -: at háði né hlátri hafðu aldregi gest né gangananda.", "Stanza 132"],
    ["Oft vitu ógörla, þeir er inni sitja, hvers þeir eru kyns, er koma; er-at maðr svá góðr, at galli né fylgi, né svá illr, at einugi dugi.", "Stanza 133"],
    ["Ráðumk þér, Loddfáfnir, at þú ráð nemir, - njóta mundu, ef þú nemr, þér munu góð, ef þú getr -: at hárum þul hlæðu aldregi, oft er gott, þat er gamlir kveða; oft ór skörpum belg skilin orð koma, þeim er hangir með hám ok skollir með skrám ok völtir með vílmögum.", "Stanza 134"],
    ["Ráðumk þér, Loddfáfnir, at þú ráð nemir, - njóta mundu, ef þú nemr, þér munu góð, ef þú getr -: gest þú ne geyja né á grind hrækir, gæt þú vesals vegar.", "Stanza 135"],
    ["Rammt er þat tré, er ríða skal öllum at upploki; baug þú gef, eða þat biðja mun þér læs hvers á liðu.", "Stanza 136"],
    ["Ráðumk þér, Loddfáfnir, at þú ráð nemir, - njóta mundu, ef þú nemr, þér munu góð, ef þú getr -: hvars þú öl drekkir, kjós þú þér jarðar megin, því at jörð tekr við ölðri, en eldr við sóttum, eik við hirðistjöru, ax við fjölkynngi, höll við hýrógi, - við barti skal bítast - máni við afbrýði, beiti við bitsóttum, en við bölvi rúnar; fold skal við flóði taka.", "Stanza 137"],
    ["Veit ek, at ek hékk vindga meiði á nætr allar níu, geiri undaðr ok gefinn Óðni, sjálfr sjálfum mér, á þeim meiði, er manngi veit hvers af rótum renn.", "Stanza 138"],
    ["Við hleifi mik sældu né við hornigi, nýsta ek niðr, nam ek upp rúnar, æpandi nam, féll ek aftr þaðan.", "Stanza 139"],
    ["Fimbulljóð níu nam ek af inum frægja syni Bölþorns, Bestlu föður, ok ek drykk of gat ins dýra mjaðar, ausinn Óðreri.", "Stanza 140"],
    ["Þá nam ek frævask ok fróðr vera ok vaxa ok vel hafa; orð mér af orði orðs leitaði, verk mér af verki verks leitaði.", "Stanza 141"],
    ["Rúnar munt þú finna ok ráðna stafi, mjög stóra stafi, mjög stinna stafi, er fáði fimbulþulr ok gerðu ginnregin ok reist Hroptr rögna.", "Stanza 142"],
    ["Óðinn með ásum, en fyr álfum Dáinn, Dvalinn dvergum fyrir, Ásviðr jötnum fyrir, ek reist sjálfr sumar.", "Stanza 143"],
    ["Veistu hve rísta skal? Veistu hve ráða skal? Veistu hve fá skal? Veistu hve freista skal? Veistu hve biðja skal? Veistu hve blóta skal? Veistu hve senda skal? Veistu hve sóa skal?", "Stanza 144"],
    ["Betra er óbeðit en sé ofblóðit, ey sér til gjafar gjöf; betra er ósent en sé ofsóat. Svá Þundr of reist fyr þjóða rök, þar hann upp of reis, er hann aftr of kom.", "Stanza 145"],
    ["Þau kann ek galdrar, er kann-at þjóðans kona ok mannskis mögr. Hjálp heitir eitt, en þat þér hjálpa mun við sökum ok sorgum ok sútum görvöllum.", "Stanza 146"],
    ["Þat kann ek annat, er þurfu ýta synir, þeir er vilja læknar lifa.", "Stanza 147"],
    ["Þat kann ek it þriðja: ef mér verðr þörf mikil hafta við mína feðr, eggjar ek deyfi minna andskota, bítat þeim vápn né velir.", "Stanza 148"],
    ["Þat kann ek it fjrða: ef mér fyrðar bera bönd at limum, svá ek gel, at ek ganga má, sprettr mér af fótum fjöturr, en af höndum haft.", "Stanza 149"],
    ["Þat kann ek it fimmta: ef ek sé af fári skotinn flein í fólki vaða, flýgr-a hann svá stinnt, at ek stöðvig-a-k, ef ek hann sjónum of sé.", "Stanza 150"],
    ["Þat kann ek it sétta: ef mik særir þegn á rótum rásviðar, ok þann hal, er mik hefna kveðr, þann etr mein heldr en mik.", "Stanza 151"],
    ["Þat kann ek it sjöunda: ef ek sé hávan brinna sal of sessmögum, brennr-at svá breitt, at ek honum bjargig-a-k, þann kann ek galdr at gala.", "Stanza 152"],
    ["Þat kann ek it átta: er öllum er nytsamligt at nema; hvar er hatr vex með hildings sonum, þat má ek bæta brátt.", "Stanza 153"],
    ["Þat kann ek it níunda: ef mik nauðr um stendr at bjarga fari mínu á floti, vind ek kyrri vági á ok svæfik allan sæ.", "Stanza 154"],
    ["Þat kann ek it tíunda: ef ek sé túnriður leika lofti á, ek svá vinnk, at þær villar fara sinna heim huga, sinna heim hama.", "Stanza 155"],
    ["Þat kann ek it ellifta: ef ek skal til orustu leiða langvini, undir randir ek gel, en þeir með ríki fara heilir hildar til, heilir hildi frá, koma þeir heilir hvaðan.", "Stanza 156"],
    ["Þat kann ek it tólfta: ef ek sé á tré uppi vaggit virfilná, svá ek ríst ok í rúnum fá, at sá gengr gumi ok mælir við mik.", "Stanza 157"],
    ["Þat kann ek it þrettánda: ef ek skal þegn ungan verpa vatni á, mun-at hann falla, þótt hann í fólk komi, hnígr-at sá hjörum fyrir.", "Stanza 158"],
    ["Þat kann ek it fjórtánda: ef ek skal fyrða liði telja goð fyrir gumum, ása ok álfa ek kann allra skil, fár kann ósnotr svá.", "Stanza 159"],
    ["Þat kann ek it fimmtánda: er gól Þjóðreyrir dvergr fyr Dellings durum; afl gól hann ásum, en álfum frama, hyggju Hroftatý.", "Stanza 160"],
    ["Þat kann ek it sextánda: ef ek vil ins svinna mans hafa geð allt ok gaman, hugi ek hverfi hvítarmri mey ok sný ek öllum hennar sefa.", "Stanza 161"],
    ["Þat kann ek it sjöunda tánda: at mik mun seint firrast in unga mær. Ljóða þessa muntu, Loddfáfnir, lengi vanr vera; þó sé þér góð, ef þú getr, nýt, ef þú nemr, þörf, ef þú þiggr.", "Stanza 162"],
    ["Þat kann ek it átjánda: er ek æva kennig mey né manns konu - allt er betra, er einn um kann, þat fylgir ljóða lokum - nema þeirri einni, er mik armi verdr eða mín systir sé.", "Stanza 163"],
    ["Nú eru Háva mál kveðin Háva höllu í, allþörf ýta sonum, óþörf jötna sonum. Heill, sá er kvað! Heill, sá er kann! Njóti, sá er nam! Heilir, þeir er hlýddu!", "Stanza 164"]
];
